"""Builds scripts/search-index.js, the data for the site search page (/search/).

Indexes every published page (title, section, level, summary, headings and main text) plus each
glossary term as its own result. sync_layout.py runs this automatically, so the index stays current.
Run on its own:  python3 _scripts/build_search_index.py
"""
from pathlib import Path
from html import unescape
import json
import re

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "scripts" / "search-index.js"
SKIP_DIRS = {"_scripts", "assets", "scripts", "node_modules", ".git"}
SKIP_PAGES = {"search/index.html", "404.html"}
SECTIONS = {"": "Home", "foundations": "Foundations", "risk-management": "Risk management",
            "compliance": "Compliance", "governance": "Governance", "grc": "GRC systems", "standards": "Standards",
            "sectors": "Sectors", "learn": "Learn", "tools": "Tools", "news": "News",
            "glossary": "Glossary", "about": "About"}
MAX_TEXT = 6000


def clean(fragment):
    fragment = re.sub(r"<(script|style|svg|noscript)\b.*?</\1>", " ", fragment, flags=re.S)
    return re.sub(r"\s+", " ", unescape(re.sub(r"<[^>]+>", " ", fragment))).strip()


def first(pattern, s):
    m = re.search(pattern, s, re.S)
    return clean(m.group(1)) if m else ""


def build():
    docs = []
    for p in sorted(ROOT.rglob("*.html")):
        rel = p.relative_to(ROOT).as_posix()
        if rel.split("/")[0] in SKIP_DIRS or rel in SKIP_PAGES:
            continue
        s = p.read_text(encoding="utf-8")
        main = re.search(r"<main\b.*?</main>", s, re.S)
        if not main:
            continue
        body = main.group(0)
        url = "/" + rel[: -len("index.html")] if rel.endswith("index.html") else "/" + rel
        section = SECTIONS.get(rel.split("/")[0] if "/" in rel else "", "Other")
        title = first(r"<h1[^>]*>(.*?)</h1>", body) or first(r"<title>(.*?)</title>", s)
        summary = first(r'<p class="summary">(.*?)</p>', body) or first(r'<meta name="description" content="([^"]*)"', s)
        level = first(r'class="level level-[a-z]+">([A-Za-z]+)<', body)
        headings = " · ".join(clean(h) for h in re.findall(r"<h[23][^>]*>(.*?)</h[23]>", body, re.S))
        # main text without breadcrumb, related links, sources and glossary entries
        text_html = re.sub(r'<nav class="breadcrumb".*?</nav>', " ", body, flags=re.S)
        text_html = re.sub(r'<section class="(related|sources)".*?</section>', " ", text_html, flags=re.S)
        if rel == "glossary/index.html":
            text_html = re.sub(r'<div class="glossary">.*', " ", text_html, flags=re.S)
        text = clean(text_html)[:MAX_TEXT]
        docs.append({"t": title, "u": url, "s": section, "l": level, "d": summary, "h": headings, "x": text})

    # glossary terms as individual results
    g = (ROOT / "glossary" / "index.html").read_text(encoding="utf-8")
    for slug, dt, dd in re.findall(r'<div class="entry" id="([^"]+)">\s*<dt>(.*?)</dt>\s*<dd>(.*?)</dd>', g, re.S):
        definition = clean(re.sub(r'<br><span class="see">.*', "", dd, flags=re.S))
        docs.append({"t": clean(dt), "u": f"/glossary/#{slug}", "s": "Glossary term", "l": "", "d": definition, "h": "", "x": ""})

    js = "// Generated by _scripts/build_search_index.py. Do not edit by hand.\nwindow.SEARCH_INDEX = " + \
         json.dumps(docs, ensure_ascii=False, separators=(",", ":")) + ";\n"
    OUT.write_text(js, encoding="utf-8")
    return len(docs), len(js.encode("utf-8"))


if __name__ == "__main__":
    n, size = build()
    print(f"wrote scripts/search-index.js ({n} entries, {size // 1024} KB)")
