# Builds the shared GRC data model from _scripts/grc_model.py:
#   - scripts/grc-model-data.js (used by the interactive map and the GRC model builder)
#   - the relationships table on /grc/grc-data-model.html, between <!-- GRC-RELS:START --> and <!-- GRC-RELS:END -->
# Run: python3 _scripts/build_grc_model.py && python3 _scripts/sync_layout.py
import json, re, html
from pathlib import Path
from grc_model import NODES, EDGES, GROUPS
ROOT = Path(__file__).resolve().parent.parent
data = {'nodes': [dict(id=a, label=b, group=c, x=x, y=y, desc=d, when=w) for a, b, c, x, y, d, w in NODES],
        'edges': [dict(a=a, b=b, label=l) for a, b, l in EDGES], 'groups': GROUPS}
(ROOT / 'scripts' / 'grc-model-data.js').write_text(
    "// Generated by _scripts/build_grc_model.py from _scripts/grc_model.py. Do not edit by hand.\nwindow.GRC_MODEL = "
    + json.dumps(data, ensure_ascii=False, indent=1) + ";\n", encoding='utf-8')
lab = {n[0]: n[1] for n in NODES}
rows = '\n'.join(f'      <tr><td>{html.escape(lab[a])}</td><td>{html.escape(l)}</td><td>{html.escape(lab[b])}</td></tr>' for a, b, l in EDGES)
table = ('<!-- GRC-RELS:START (built by _scripts/build_grc_model.py) -->\n  <div class="table-wrap"><table>\n'
         '    <caption>Every relationship in the model, read left to right (for example "Board and committees approves Risk appetite and metrics").</caption>\n'
         '    <thead><tr><th>Object</th><th>Relationship</th><th>Linked object</th></tr></thead>\n    <tbody>\n'
         + rows + '\n    </tbody>\n  </table></div>\n  <!-- GRC-RELS:END -->')
p = ROOT / 'grc' / 'grc-data-model.html'
if p.exists():
    s = p.read_text(encoding='utf-8')
    s = re.sub(r'<!-- GRC-RELS:START.*?<!-- GRC-RELS:END -->', lambda m: table, s, flags=re.S)
    p.write_text(s, encoding='utf-8')
print(f'GRC model: {len(NODES)} objects, {len(EDGES)} relationships')
