"""Notable updates for the public "What's new" page (/whats-new/).

New pages are found automatically from git history, so only list UPDATES here:
substantive changes to existing pages, and site-wide changes (url = "").
Newest first is not required; the page sorts by date.
Run:  python3 _scripts/build_changelog.py && python3 _scripts/sync_layout.py
"""

# (ISO date, root-relative URL or "", what changed)
UPDATES = [
    ('2026-10-08', '/standards/aps-115.html', 'APS 115: deep review, adding how the 2026 capital changes affect operational risk capital'),
    ('2026-10-08', '/standards/aps-110-and-aps-210.html', 'APS 110 and APS 210: deep review, adding a worked capital ratio and the 2026 to 2027 bank capital and liquidity changes'),
    ('2026-10-08', '/standards/cps-190-and-cps-900.html', "CPS 190 and CPS 900: deep review, adding APRA's findings for super and a worked trustee trigger example"),
    ('2026-10-08', '/standards/cps-511.html', "CPS 511: deep review, adding SFI thresholds, a worked malus example and APRA's pre-implementation findings"),
    ('2026-10-08', '/standards/cps-510-and-cps-520.html', "CPS 510 and CPS 520: deep review, with a table of the June 2026 draft governance standard's main proposals"),
    ('2026-10-08', '/standards/cps-234.html', "CPS 234: deep review, adding APRA's 2024 and 2025 cyber letters and the overlapping incident reporting clocks"),
    ('2026-10-08', '/standards/cps-220.html', "CPS 220: deep review, adding a worked risk appetite breach example and what's changing around the standard"),
    ('2026-10-07', '/governance/conflicts-of-interest.html', "Conflicts of interest: deep review, adding a worked director's conflict example and board questions"),
    ('2026-10-07', '/standards/asic-rg-181.html', 'RG 181 (conflicts): deep review, adding common conflicts and how the rules have tightened'),
    ('2026-10-07', '/standards/asic-rg-104-and-rg-105.html', 'RG 104 and RG 105: deep review, adding the general obligations in more detail and common mistakes'),
    ('2026-10-07', '/compliance/financial-advice-regulation.html', 'Financial advice regulation: deep review, adding the August 2026 advice reform announcement'),
    ('2026-10-07', '/standards/asic-rg-271.html', 'RG 271 (complaints): deep review, adding the IDR timeframe table and IDR data reporting'),
    ('2026-10-07', '/compliance/consumer-protection.html', 'Consumer protection: deep review, with updated scams framework dates and lessons from Shield and First Guardian'),
    ('2026-10-07', '/standards/asic-rg-274.html', "RG 274 (DDO): deep review, adding ASIC's stop orders and penalties, common mistakes and board questions"),
    ('2026-10-07', '/compliance/misleading-or-deceptive-conduct.html', 'Misleading or deceptive conduct: deep review, adding the tests applied in recent greenwashing cases'),
    ('2026-10-07', '/compliance/disclosure-obligations.html', 'Disclosure obligations: deep review, adding greenwashing penalties, common mistakes and board questions'),
    ("2026-10-07", "", "New menu: Risk, Compliance, Governance, Your sector, Standards, Learn and Toolkit each open a panel of grouped topics, including \"what to do when\" guides."),
    ("2026-10-07", "/obligations/sectors.html", "New: obligations by sector. Pick super, banking, general, life or private health insurance, funds management, advice, credit or payments to see the regimes that usually apply, or compare sectors side by side."),
    ("2026-10-07", "/sectors/insurance.html", "Insurance now has three guides: general insurance, life insurance and private health insurance, with the insurance page kept as an overview."),
    ('2026-10-07', '/risk-management/enterprise-risk-management.html', 'Enterprise risk management page expanded: what CPS 220 and SPS 220 expect, common mistakes, board questions and FAQs.'),
    ('2026-10-07', '/compliance/compliance-monitoring-and-testing.html', 'Compliance monitoring page: example monitoring plan, common mistakes and board questions added.'),
    ('2026-10-07', '/risk-management/assurance-mapping.html', 'Assurance mapping page expanded: rating assurance quality, common mistakes, board questions and FAQs.'),
    ('2026-10-07', '/risk-management/kri-design-and-thresholds.html', 'KRI design page: example KRI catalogue, common mistakes and board questions added.'),
    ('2026-10-07', '/risk-management/risk-appetite-and-tolerance.html', 'Risk appetite page expanded: worked appetite metrics for a super fund, board questions and FAQs.'),
    ('2026-10-07', '/risk-management/risk-assessment-methodologies.html', 'Risk assessment methodologies page expanded: running an RCSA step by step, common mistakes, board questions and FAQs.'),
    ('2026-10-07', '/risk-management/control-testing-sampling.html', 'Control testing sampling page: common mistakes and board questions added.'),
    ('2026-10-07', '/risk-management/control-design-and-testing.html', 'Control design and testing page expanded: a worked control test, common mistakes, board questions and FAQs.'),
    ('2026-10-07', '/risk-management/operational-risk.html', 'Operational risk page expanded: example key risk indicators, common mistakes, board questions, FAQs and key dates.'),
    ('2026-10-07', '/risk-management/business-continuity.html', 'Business continuity page expanded: roles, common mistakes, board questions and FAQs.'),
    ('2026-10-07', '/risk-management/service-provider-exit-and-concentration.html', 'Service provider exit page expanded: an exit plan on a page, common mistakes and board questions.'),
    ('2026-10-07', '/risk-management/third-party-risk.html', 'Third-party risk page expanded: monitoring material providers, common mistakes, board questions, FAQs and key dates.'),
    ('2026-10-07', '/risk-management/mapping-critical-operations.html', 'Mapping critical operations page expanded: keeping maps current, common mistakes, board questions and FAQs.'),
    ('2026-10-07', '/risk-management/setting-cps-230-tolerance-levels.html', 'Setting CPS 230 tolerance levels page expanded: tolerances versus recovery objectives, a tolerance statement template, board questions and FAQs.'),
    ('2026-10-07', '/standards/cps-230.html', 'CPS 230 page expanded: the 2026 exemptions in detail, minimum critical operations, a worked example, how APRA supervises, board questions and FAQs.'),
    ('2026-10-07', '/risk-management/issue-and-action-management.html', 'Issue and action management page expanded: regulator expectations, register fields, a worked example, risk acceptance, reporting measures, common mistakes and board questions.'),
    ('2026-10-07', '/risk-management/root-cause-analysis.html', 'Root cause analysis page expanded: what regulators expect, a step-by-step method, a report structure, spotting themes across incidents, common mistakes and board questions.'),
    ('2026-10-07', '/compliance/remediation-calculations.html', 'Remediation calculations page expanded: special cases such as rollovers, deaths, switches and insurance, oversight measures, common mistakes, and the calculator updated for the current RBA cash rate.'),
    ('2026-10-07', '/standards/asic-rg-277.html', "RG 277 page expanded: calculating lost earnings, review periods, paying former customers, a worked example, ASIC's findings to 2026, common mistakes, board questions, key dates and FAQs."),
    ('2026-10-02', '/compliance/breach-significance-analysis.html', "Breach significance analysis page expanded: how ASIC's 2025 relief changes the analysis, and a new worked case on long-running investigations."),
    ('2026-10-02', '/standards/asic-rg-78.html', 'RG 78 page expanded: the key ideas in the guide, what a report contains, a worked example applying each test, common mistakes, key dates and FAQs.'),
    ('2026-10-02', '/compliance/breach-reporting.html', "Breach reporting page expanded: ASIC's 2025 relief in detail, what a breach assessment should record, ASIC's findings and the Mercer Super penalty, the AUSTRAC IFTI transition, common mistakes, key dates and FAQs."),
    ('2026-10-02', '/risk-management/incident-and-breach-management.html', "Incident and breach management page expanded: an example severity scale, what to record, ASIC's findings on slow breach identification, the Mercer Super penalty, the 2025 reporting relief, common mistakes, board questions and key dates."),
    ('2026-10-02', '/sectors/behavioural-economics-of-super.html', 'Behavioural economics of super page expanded: how the system is built around defaults, what it means for trustees, and key dates.'),
    ('2026-10-02', '/risk-management/super-liquidity-stress-testing.html', "Liquidity stress testing page expanded: a worked 30-day coverage check, APRA's liquidity findings, private markets data, common mistakes, board questions and key dates."),
    ('2026-10-02', '/sectors/unit-pricing.html', 'Unit pricing page expanded: a worked error calculation, how unit pricing is governed, outsourced pricing under CPS 230, common mistakes, board questions, key dates and FAQs.'),
    ('2026-10-02', '/sectors/fund-mergers-and-successor-fund-transfers.html', 'Fund mergers page expanded: the merger process stage by stage, tax relief, performance test histories, the 2026 ACCC merger regime, common mistakes, board questions and key dates.'),
    ('2026-10-02', '/standards/asic-rg-97.html', "RG 97 page expanded: super fee rules beyond disclosure, common mistakes, fee governance questions, key dates, FAQs, and the latest on stamp duty averaging and ASIC's 2026–27 review."),
    ('2026-10-02', '/sectors/superannuation.html', 'Superannuation trustee governance page expanded: insurance in super, recent enforcement cases, a key dates table, Payday Super and Division 296, board questions and FAQs.'),
    ("2026-10-02", "/standards/sps-530.html", "SPS 530 page expanded in depth: every requirement explained, valuation policy and revaluation triggers, liquidity and stress testing, APRA's 2023 to 2026 findings on unlisted valuations, and APRA's June 2026 proposals after the Shield and First Guardian collapses."),
    ("2026-10-02", "", "Tables in articles now line up with the text column on large screens."),
    ("2026-10-02", "/standards/sps-515.html", "SPS 515 page rewritten in depth: every requirement of the 2025 version explained, APRA's crackdown on super fund spending and what it found, how SPS 515 fits with the SIS Act, a worked example, common mistakes, board questions, FAQs and a timeline."),
    ("2026-10-02", "/about/roadmap.html", "New deep review roadmap: every article is being re-checked line by line and expanded, one phase per article, with progress shown on the home page."),
    ("2026-10-01", "/learn/videos.html", "All 14 explainer videos now have a voiceover that reads the captions aloud. Captions and transcripts stay, so they still work with the sound off."),
    ("2026-10-01", "", "Guides now link straight to their playbook and board briefing (\"Put it into practice\"), and news moves to a monthly regulatory roundup."),
    ("2026-10-01", "/governance/board-briefings.html", "New board briefings: printable two-page briefings for directors on CPS 230, FAR, breach reporting, CPS 234 and AML/CTF, with questions to ask management."),
    ("2026-10-01", "/about/roadmap.html", "New site roadmap: see what we are improving, stage by stage. Also a simpler menu, a new Topics page and a new home page."),
    ("2026-10-01", "/learn/my-learning.html", "Learning pathways now work like courses: a Mark as read button and step-by-step next links on every page in a pathway, and a new My learning page with your progress and a printable record of learning."),
    ("2026-10-01", "/obligations/", "New Obligations library: 117 plain-English obligation summaries from 37 Australian regimes, with control objectives, evidence, related risks and notification deadlines. Search, filter by organisation type and download as Excel or CSV."),
    ("2026-10-01", "/playbooks/", "New Playbooks section: step-by-step guides for responding to an incident, assessing a breach, running a remediation, onboarding a material service provider, reviewing disclosure, testing a control and your first 90 days, each with a tickable checklist."),
    ("2026-10-01", "/about/editorial-standards.html", "Every content page now shows its review status (Checked against sources, or Expert reviewed) and has a Suggest a correction link. New page explaining how we check content."),
    ("2026-10-01", "/grc/model-builder.html", "GRC model builder rebuilt: a five-step wizard (or six ready-made examples) that produces a fully linked model: obligations from 37 regimes tied to risks, controls and KRIs, notification clocks, committees and roles, the data model, a maturity radar and roadmap, consistency checks, and an Excel workbook with about 20 sheets."),
    ("2026-10-01", "/grc/", "New GRC systems section: how complex organisations design and establish an integrated governance, risk and compliance system, the risk hierarchy from enterprise to Level 3, obligations and control architecture, an interactive map of how everything links, the operating model, technology, and a GRC model builder tool."),
    ("2026-10-01", "", "New artwork and a better desktop layout: all 27 graphics redone as abstract studio pieces in glass, aluminium and ceramic; wider pages on large screens, larger text, diagrams and tables that step out of the text column, and an \"On this page\" sidebar on wide screens."),
    ("2026-10-01", "", "Design polish: 11 new 3D graphics on 23 key topic pages (from CPS 230 to privacy and super), smooth fade-in as you scroll, an \"On this page\" bar on longer articles, and a \"by the numbers\" section on the home page."),
    ("2026-10-01", "/news/regulatory-tracker.html", "RBA card surcharging and interchange changes moved to In force (from 1 October 2026)."),
    ("2026-09-30", "", "New look for the whole site: a clean, light design with large tiles, our own high-definition 3D graphics for every section, a new icon, and all 14 explainer videos re-made to match."),
    ("2026-09-30", "/learn/advanced-study-program.html", "New Advanced study program: a free 12-module, university-style course built from the Advanced pages, with learning outcomes, required peer-reviewed readings, seminar questions and essay questions."),
    ("2026-09-30", "", "14 new university-level pages on the research behind risk, compliance and governance: theories of risk and regulation, governance theories, whether ERM works, the three lines, internal audit, misconduct, pay and risk-taking, whistleblowing, fraud theory, super behaviour, and the economics of cyber, climate and AML/CTF."),
    ("2026-09-30", "/learn/quizzes.html", "New University-level research quiz, a Research flashcard deck, 12 new glossary terms, and the new pages added to the learning pathways."),
    ("2026-09-30", "", "All 25 Advanced pages upgraded to university level: learning outcomes, a Theory and research section grounded in peer-reviewed studies, critical perspectives, seminar questions, further reading and APA references."),
    ("2026-09-30", "/learn/research-library.html", "New Research library: over 100 checked research sources behind the Advanced pages, grouped by topic with plain-English summaries."),
    ("2026-09-30", "/learn/videos.html", "New Videos page: 14 short explainer videos with captions and full transcripts, from the risk management loop and the Three Lines model to misleading conduct, root causes, unit pricing errors and the denominator effect, plus official videos from AUSTRAC and the ACNC."),
    ("2026-09-30", "", "Explainer videos added to 33 topic pages, next to the detail they explain. Each video can be downloaded for training, and official regulator videos only load from YouTube when you press play."),
    ("2026-09-28", "/learn/by-level.html", "New Browse by level page, with a clear definition of Beginner, Intermediate and Advanced, and every page grouped by level."),
    ("2026-09-28", "", "A new Advanced track: 17 new Advanced pages and case studies, from the legal tests for misleading conduct and directors' duties cases to APS 115 capital, KRI thresholds, root cause analysis, unit pricing and fund mergers, most with interactive calculators or simulators."),
    ("2026-09-28", "/learn/quizzes.html", "New Advanced topics quiz, two multi-regime Advanced scenarios, seven new glossary terms and 13 new Advanced flashcards."),
    ("2026-09-28", "/learn/pathways.html", "Added Advanced stages for the new pages to every learning pathway, and 'Going deeper' links from 19 Intermediate pages."),
    ("2026-09-28", "/compliance/breach-reporting.html", "Corrected the super trustee breach reporting timeframe (SIS Act s 29JA) to \"as soon as practicable, and within 30 days\" across the site and the incident report template."),
    ("2026-09-28", "", "Site-wide review: accessibility fixes (heading order and table headers), updated section descriptions, and consistency checks of regulatory deadlines across pages."),
    ("2026-09-28", "/learn/pathways.html", "Refreshed the learning pathways with the new standards, templates, case studies and scenarios, and added a pathway for banking, insurance and other sectors."),
    ("2026-09-28", "/learn/flashcards.html", "Three new flashcard decks: newer glossary terms, advanced concepts, and key dates for new and changing regimes. The standards deck now covers 32 standards and guides."),
    ("2026-09-28", "/learn/quizzes.html", "Added 55 quiz questions covering every page added since the last quiz update, plus a new News and current affairs quiz."),
    ("2026-09-28", "/learn/scenarios.html", "Six new scenario simulations: a privacy data breach, a marketing campaign review, a related-party conflict, a CPS 230 tolerance breach, an AML suspicion and an advice file review."),
    ("2026-09-28", "/tools/", "Added eight free templates: obligations register, control testing workpaper, RCSA, KRI library, example risk appetite statement, board risk report, material service provider register and remediation program tracker."),
    ("2026-09-28", "/sectors/", "Added six sector pages: credit and non-bank lenders, financial advice licensees, payments and fintech, listed companies, the Commonwealth public sector, and not-for-profits and charities."),
    ("2026-09-28", "/case-studies/", "New Case studies section: the Hayne Royal Commission, APRA's inquiry into CBA, AUSTRAC v CBA and Westpac, Optus and Medibank, HIH Insurance, and Shield and First Guardian, each with a timeline, lessons and a quiz."),
    ("2026-09-27", "/standards/", "Added 15 new explainers, including CPS 511, SPS 515, SPS 530, CPS 190 and CPS 900, RG 181, RG 270, ISO 22301, ISO 37301, ISO/IEC 42001 and the Essential Eight."),
    ("2026-09-27", "/learn/pathways.html", "Added the new risk, governance, cyber and standards pages to the learning pathways."),
    ("2026-09-27", "/governance/ai-governance.html", "Added APRA's April 2026 letter to industry on AI risk management."),
    ("2026-09-27", "/news/regulatory-tracker.html", "Added mandatory climate reporting, further financial advice reforms, the proposed modern slavery offence and the foreign bribery failure to prevent offence."),
    ("2026-09-27", "/learn/pathways.html", "Added an Advanced stage to the risk, compliance, governance and superannuation pathways."),
    ("2026-09-27", "/start-here/", "Added a \"Go deeper\" route through the seven new Advanced topics."),
    ("2026-09-27", "/glossary/", "Added VaR, expected shortfall, reverse stress testing, ICAAP, diversification benefit and tolerable deviation rate."),
    ("2026-09-27", "", "New look: the whole site moved to a dark, futuristic design, with fonts hosted on the site itself so no third-party requests are made."),
    ("2026-09-27", "/governance/financial-accountability-regime.html", "Added the regulators' proposed simplifications to the Financial Accountability Regime."),
    ("2026-09-27", "/compliance/consumer-protection.html", "Updated the Scams Prevention Framework timetable."),
    ("2026-09-27", "/glossary/", "Added 34 terms, including ADI, responsible entity, CET1, hawking, significant dealing and SMSF, and linked them from the pages that use them."),
    ("2026-09-27", "", "Added link previews for sharing, a browser-tab icon, a sitemap and a friendly page-not-found page, and made the faintest text easier to read."),
    ("2026-09-27", "", "Yearly review system: every page now shows when its next review is due, and pages checked by the site's subject-matter expert will carry an \"Expert reviewed\" badge."),
]
