"""Notable updates for the public "What's new" page (/whats-new/).

New pages are found automatically from git history, so only list UPDATES here:
substantive changes to existing pages, and site-wide changes (url = "").
Newest first is not required; the page sorts by date.
Run:  python3 _scripts/build_changelog.py && python3 _scripts/sync_layout.py
"""

# (ISO date, root-relative URL or "", what changed)
UPDATES = [
    ('2026-10-10', '/risk-management/economics-of-cyber-risk.html', 'New explainer video: How much to spend on security? The Gordon-Loeb model, with a worked example and the model\'s limits, captions, a voiceover and a full transcript.'),
    ('2026-10-10', '/risk-management/theories-of-risk.html', 'New explainer video: Normal accidents and high reliability. Perrow\'s complexity and coupling, high reliability practices and what they suggest for operational resilience, with captions, a voiceover and a full transcript.'),
    ('2026-10-10', '/compliance/aml-ctf-fundamentals.html', 'AML/CTF: confirmed the 31 March 2026 and 1 July 2026 start dates against the amending Act, and added that tranche 2 businesses already providing a new service before 1 July 2026 had until 29 July 2026 to enrol.'),
    ('2026-10-09', '/compliance/theories-of-regulation.html', 'New explainer video: The enforcement pyramid. Responsive regulation in about a minute, with captions, a voiceover and a full transcript; also on the enforcement and penalties page and the Watch page.'),
    ('2026-10-09', '/learn/videos.html', 'CPS 230 in 90 seconds: re-rendered so the 20-business-day notice label says it applies to agreements for services a critical operation relies on, matching CPS 230 paragraph 60(a).'),
    ('2026-10-09', '/about/fact-register.html', 'Key facts register: 64 facts. Added the super guarantee rate (12%), the FAR deferral share (40%) and the CPS 511 CEO deferral share (60%), and confirmed eight more against the official text, including the $364 penalty unit, the SPS 515 and CPS 190 start dates and the climate reporting phase-in.'),
    ('2026-10-09', '/governance/remuneration-governance.html', 'Remuneration: made the CPS 511 deferral rules precise (40% over five years applies to senior managers and executive directors; highly paid material risk-takers defer 40% over four years) and added a material risk-taker option to the deferral calculator. CPS 511 page: clawback lasts at least two years after payment or vesting.'),
    ('2026-10-09', '/sectors/not-for-profits-and-charities.html', 'Charities: corrected the number of ACNC Governance Standards from five to six. Standard 6 requires a charity named in a National Redress Scheme application to take reasonable steps to join the Scheme (checked against the ACNC Regulations 2022).'),
    ('2026-10-09', '/risk-management/cyber-risk.html', 'Ransomware payment reporting: the turnover threshold is turnover above $3 million (not "$3 million or more"), and the 72-hour deadline is now confirmed from the Cyber Security Act 2024 and its Rules.'),
    ('2026-10-09', '/sectors/life-insurance.html', 'Insurance and advice: added that since 9 July 2025 an adviser giving personal advice on general, life risk or consumer credit insurance needs the client\'s informed consent before receiving a commission (Corporations Act s 963BB).'),
    ('2026-10-09', '/standards/cps-220.html', 'CPS 220 and SPS 220: super trustees also give APRA an annual risk management declaration, signed by two directors (SPS 220 paragraphs 32 to 34). Also corrected SPS 510 tenure and board composition details on the governance pages.'),
    ('2026-10-08', '/compliance/privacy-law.html', 'Privacy law: added that the draft Privacy Amendment (Personal Data Protection) Bill 2026 would require a statement to the Privacy Commissioner within 72 hours of believing there has been an eligible data breach, and a new duty to reduce harm from breaches (checked against the exposure draft).'),
    ('2026-10-08', '/standards/cps-230.html', 'CPS 230: corrected the significant financial institution (SFI) section. Since 1 July 2026 CPS 230 applies in full to every APRA-regulated entity, SFI definitions sit in CPS 001 and other standards, and the bank SFI threshold is $30 billion (up from $20 billion), with a new top tier above $300 billion. CPS 511, APS 110 and CPS 220 pages, the glossary, the tracker and the GRC model builder updated to match.'),
    ('2026-10-09', '/obligations/', 'Obligations library: individual obligations with their legal citations, 572 in all across all 39 regimes, now including the super trustee standards (SPS 220, 510, 515, 520, 521, 530), CPS 511, CPS 190 and CPS 900, APS 210, the SIS Act covenants and performance test, fee disclosure (RG 97), responsible entity risk management (RG 259), FAR, insurance, life and private health insurance, consumer credit, sanctions, anti-bribery, the Scams Prevention Framework, climate reporting, ransomware reporting, charities, the PGPA Act, product disclosure, listed company disclosure and AI (the new privacy policy rules for automated decisions from 10 December 2026). Each was checked against the official text. Included in the Excel and CSV downloads and the GRC model builder.'),
    ('2026-10-08', '/risk-management/third-party-risk.html', 'CPS 230: made the 20-business-day APRA notice more precise. It applies to agreements for services relied on to undertake a critical operation (paragraph 60(a)), not to every material arrangement.'),
    ('2026-10-08', '/about/fact-register.html', 'Key facts register: added 16 notification deadlines and thresholds (CPS 230, CPS 234, ASIC reportable situations, data breaches, ransomware payments, AUSTRAC reports, complaint response times, the privacy small business threshold, the modern slavery threshold and the CET1 minimum). The regulatory tracker, playbooks and board briefings now take their dates and deadlines from the register.'),
    ('2026-10-08', '/obligations/', 'Obligations library: added private health insurance (community rating, premium approval, waiting periods, notice of detrimental changes, the Ombudsman) and life insurance (statutory funds, commission caps, the Life Code, income protection), now 131 obligations from 39 regimes. Also in the GRC model builder.'),
    ('2026-10-08', '/sectors/private-health-insurance.html', 'Private health insurance: added the rule on notice of detrimental changes and updated the name of the consumer information statement (private health information statements replaced standard information statements in 2019).'),
    ('2026-10-08', '/about/fact-register.html', 'New Key facts register: the main regulatory dates, amounts and limits on the site, each with its official source and when and how it was last checked. Pages now take these facts from one place, and a weekly automatic check watches regulator announcements'),
    ('2026-10-08', '/standards/sps-530.html', 'SPS 530: corrected the date of APRA\'s proposals to strengthen investment governance (released 30 September 2026, submissions close 3 February 2027) and added the detail of the eight proposed areas'),
    ('2026-10-08', '/about/roadmap.html', 'Deep review complete: all 137 articles re-checked against current law and regulator guidance, and expanded'),
    ('2026-10-08', '/risk-management/human-factors-and-bias.html', 'Human factors and bias: deep review, adding a worked pre-mortem'),
    ('2026-10-08', '/risk-management/climate-risk-research.html', 'Climate risk research: deep review, adding implications for super trustees'),
    ('2026-10-08', '/risk-management/economics-of-cyber-risk.html', 'Economics of cyber risk: deep review, adding a worked Gordon-Loeb calculation'),
    ('2026-10-08', '/compliance/fraud-theory.html', 'Fraud theory: deep review, adding an insider fraud scenario'),
    ('2026-10-08', '/compliance/aml-ctf-effectiveness.html', 'AML/CTF effectiveness: deep review, adding outcome-focused measures'),
    ('2026-10-08', '/compliance/misconduct-in-financial-services-research.html', 'Misconduct research: deep review, applying the findings to adviser onboarding and monitoring'),
    ('2026-10-08', '/governance/whistleblowing-research.html', 'Whistleblowing research: deep review, adding design responses for each stage of speaking up'),
    ('2026-10-08', '/governance/remuneration-incentives-and-risk-taking.html', 'Remuneration, incentives and risk-taking: deep review, applying the multitasking problem'),
    ('2026-10-08', '/governance/internal-audit-effectiveness.html', 'Internal audit effectiveness: deep review, adding indicators for audit committees'),
    ('2026-10-08', '/governance/three-lines-research-and-critique.html', 'Three lines research and critique: deep review, applying the critique to a chain of assumed assurance'),
    ('2026-10-08', '/risk-management/does-erm-work.html', 'Does ERM work: deep review, adding how a board might test its own ERM'),
    ('2026-10-08', '/risk-management/theories-of-risk.html', 'Theories of risk: deep review, adding Australian examples of each theory'),
    ('2026-10-08', '/governance/corporate-governance-theories.html', 'Corporate governance theories: deep review, applying four theories to a super fund merger decision'),
    ('2026-10-08', '/compliance/theories-of-regulation.html', 'Theories of regulation: deep review, adding Australian examples at each level of the enforcement pyramid'),
    ('2026-10-08', '/case-studies/hih-insurance-collapse.html', 'HIH collapse: deep review, adding the reforms that followed'),
    ('2026-10-08', '/case-studies/shield-and-first-guardian.html', 'Shield and First Guardian: deep review, adding the 2026 developments'),
    ('2026-10-08', '/case-studies/asic-cyber-cases-ri-advice-and-fiig.html', 'RI Advice and FIIG: deep review, adding FAQs on s 912A and APRA-regulated entities'),
    ('2026-10-08', '/case-studies/optus-medibank-data-breaches.html', 'Optus and Medibank: deep review, adding where the privacy court cases stand'),
    ('2026-10-08', '/case-studies/austrac-cba-westpac.html', 'AUSTRAC v CBA and Westpac: deep review, adding later AUSTRAC cases and the reforms'),
    ('2026-10-08', '/case-studies/apra-cba-prudential-inquiry.html', "CBA prudential inquiry: deep review, mapping the inquiry's findings to today's standards"),
    ('2026-10-08', '/case-studies/hayne-royal-commission.html', 'Hayne Royal Commission: deep review, adding the reforms that followed and when they started'),
    ('2026-10-08', '/foundations/core-frameworks-compared.html', 'Core frameworks compared: deep review, adding a guide to which framework fits which question'),
    ('2026-10-08', '/foundations/three-lines-model.html', "Three lines model: deep review, adding a worked example of each line's role"),
    ('2026-10-08', '/foundations/regulatory-landscape.html', "Regulatory landscape: deep review, adding recent changes to regulators' roles"),
    ('2026-10-08', '/foundations/what-is-governance.html', 'What is governance: deep review, adding a worked example of good and weak governance'),
    ('2026-10-08', '/foundations/what-is-compliance.html', 'What is compliance: deep review, adding a worked example following one obligation'),
    ('2026-10-08', '/foundations/what-is-risk-management.html', 'What is risk management: deep review, adding an everyday worked example and FAQs'),
    ('2026-10-08', '/grc/grc-for-complex-groups.html', 'GRC for complex groups: deep review, adding a worked design example for a multi-entity group'),
    ('2026-10-08', '/grc/grc-technology.html', 'GRC technology: deep review, adding common mistakes and board questions'),
    ('2026-10-08', '/grc/governance-and-operating-model.html', 'GRC governance and operating model: deep review, adding a worked escalation example'),
    ('2026-10-08', '/grc/grc-data-model.html', 'GRC data model: deep review, adding common mistakes'),
    ('2026-10-08', '/grc/risk-taxonomy-and-hierarchy.html', 'Risk taxonomy and hierarchy: deep review, adding common mistakes and FAQs'),
    ('2026-10-08', '/grc/control-framework-architecture.html', 'Control framework architecture: deep review, adding a worked control description'),
    ('2026-10-08', '/grc/obligations-architecture.html', 'Obligations architecture: deep review, adding a worked obligation record'),
    ('2026-10-08', '/grc/establishing-a-grc-system.html', 'Establishing a GRC system: deep review, adding an illustrative 12-month plan'),
    ('2026-10-08', '/grc/what-is-a-grc-system.html', 'What is a GRC system: deep review, adding a worked example of a breach flowing through the system'),
    ('2026-10-08', '/sectors/public-sector.html', 'Public sector: deep review, adding a worked shared risk example'),
    ('2026-10-08', '/sectors/not-for-profits-and-charities.html', "Not-for-profits and charities: deep review, adding a worked list of a small charity's top risks"),
    ('2026-10-08', '/sectors/listed-companies.html', 'Listed companies: deep review, adding a worked continuous disclosure example and the 5th edition timeline'),
    ('2026-10-08', '/sectors/payments-and-fintech.html', 'Payments and fintech: deep review, adding the status of the payments licensing reforms'),
    ('2026-10-08', '/sectors/credit-and-non-bank-lenders.html', 'Credit and non-bank lenders: deep review, adding a worked responsible lending assessment'),
    ('2026-10-08', '/sectors/financial-advice-licensees.html', 'Financial advice licensees: deep review, adding the 2026-27 CSLR levy and a worked fee monitoring example'),
    ('2026-10-08', '/standards/asic-rg-259.html', "RG 259: deep review, adding a worked summary of a responsible entity's main risks"),
    ('2026-10-08', '/sectors/managed-investment-schemes.html', 'Managed investment schemes: deep review, adding a worked liquidity mismatch example and the CSLR special levy'),
    ('2026-10-08', '/sectors/private-health-insurance.html', 'Private health insurance: deep review, adding a worked example on waiting periods when switching'),
    ('2026-10-08', '/sectors/life-insurance.html', 'Life insurance: deep review, adding a worked claim and disclosure example'),
    ('2026-10-08', '/sectors/general-insurance.html', 'General insurance: deep review, adding a worked pricing promise review'),
    ('2026-10-08', '/sectors/insurance.html', 'Insurance overview: deep review, adding common weak spots and board questions'),
    ('2026-10-08', '/sectors/banking.html', "Banking and ADIs: deep review, adding a worked example of APRA's debt-to-income limit"),
    ('2026-10-08', '/standards/asic-regulatory-guides.html', 'ASIC regulatory guides: deep review, adding how to read a regulatory guide'),
    ('2026-10-08', '/standards/global-internal-audit-standards.html', 'Global Internal Audit Standards: deep review, adding key requirements and topical requirement dates'),
    ('2026-10-08', '/standards/iso-42001.html', 'ISO/IEC 42001: deep review, adding a worked example of starting an AI management system'),
    ('2026-10-08', '/standards/iso-37001.html', 'ISO 37001: deep review, adding what changed in the 2025 edition'),
    ('2026-10-08', '/standards/essential-eight.html', "Essential Eight: deep review, adding ASD's 2026 consultation on the new Essentials series"),
    ('2026-10-08', '/standards/iso-27001.html', 'ISO/IEC 27001: deep review, adding how certification works'),
    ('2026-10-08', '/standards/iso-22301.html', 'ISO 22301: deep review, adding the steps to build a business continuity management system'),
    ('2026-10-08', '/standards/iso-37301.html', 'ISO 37301: deep review, adding a staged build example and a mapping to Australian expectations'),
    ('2026-10-08', '/standards/coso.html', 'COSO: deep review, adding a worked control evaluation using the five components'),
    ('2026-10-08', '/standards/iso-31000.html', 'ISO 31000: deep review, adding a worked example of the risk management process'),
    ('2026-10-08', '/risk-management/risk-aggregation-and-correlation.html', 'Risk aggregation and correlation: deep review, adding a worked diversification example'),
    ('2026-10-08', '/risk-management/quantitative-operational-risk.html', 'Quantitative operational risk: deep review, adding a worked reading of a loss distribution'),
    ('2026-10-08', '/risk-management/scenario-analysis-and-stress-testing.html', "Scenario analysis and stress testing: deep review, adding APRA's first System Risk Stress Test results"),
    ('2026-10-08', '/risk-management/change-project-and-reputational-risk.html', 'Change, project and reputational risk: deep review, adding a worked administration platform migration example'),
    ('2026-10-08', '/risk-management/model-risk.html', 'Model risk: deep review, adding a worked model tiering example'),
    ('2026-10-08', '/risk-management/credit-market-and-liquidity-risk.html', 'Credit, market and liquidity risk: deep review, adding a worked expected loss example'),
    ('2026-10-08', '/risk-management/climate-risk.html', "Climate risk: deep review, adding APRA's 2026 insurance climate vulnerability assessment"),
    ('2026-10-08', '/risk-management/cyber-risk.html', "Cyber risk: deep review, adding ASD's latest threat figures and a worked ransomware example"),
    ('2026-10-08', '/compliance/interpreting-legislation.html', 'Interpreting legislation: deep review, adding a worked example breaking an obligation into elements'),
    ('2026-10-08', '/compliance/designing-a-compliance-program.html', 'Designing a compliance program: deep review, adding a worked first 90 days at a small licensee'),
    ('2026-10-08', '/compliance/enforcement-and-penalties.html', 'Enforcement and penalties: deep review, adding recent outcomes for context'),
    ('2026-10-08', '/compliance/licensing-basics.html', 'Licensing basics: deep review, adding a worked example on whether an app needs a licence'),
    ('2026-10-08', '/compliance/climate-related-financial-disclosures.html', "Climate-related financial disclosures: deep review, adding ASIC's findings on the first sustainability reports"),
    ('2026-10-08', '/compliance/modern-slavery.html', 'Modern slavery: deep review, adding a worked supplier assessment'),
    ('2026-10-08', '/compliance/privacy-law.html', 'Privacy law: deep review, updated for the tranche 2 exposure draft and a worked data breach example'),
    ('2026-10-08', '/risk-management/fraud-risk.html', 'Fraud risk: deep review, adding a worked assessment of member account takeover fraud'),
    ('2026-10-08', '/compliance/anti-bribery-and-corruption.html', 'Anti-bribery and corruption: deep review, adding a worked gift decision and third-party red flags'),
    ('2026-10-08', '/compliance/sanctions-compliance.html', 'Sanctions compliance: deep review, adding current penalty amounts and how sanctions are enforced'),
    ('2026-10-08', '/compliance/aml-ctf-fundamentals.html', 'AML/CTF fundamentals: deep review, adding current AUSTRAC cases and a worked tranche 2 example'),
    ('2026-10-08', '/governance/ai-governance.html', 'AI governance: deep review, adding a worked assessment of an AI use case'),
    ('2026-10-08', '/governance/directors-duties-case-law.html', "Directors' duties case law: deep review, adding the Star case penalties and appeals"),
    ('2026-10-08', '/governance/internal-audit.html', 'Internal audit: deep review, adding the third-party topical requirement and a worked finding rating'),
    ('2026-10-08', '/standards/asic-rg-270.html', 'RG 270: deep review, adding what makes a whistleblower policy work in practice'),
    ('2026-10-08', '/governance/whistleblower-protections.html', "Whistleblower protections: deep review, updated for Treasury's 2026 review of the whistleblower laws"),
    ('2026-10-08', '/governance/risk-culture-assessment.html', 'Risk culture assessment: deep review, adding a worked example of triangulating evidence'),
    ('2026-10-08', '/governance/culture-and-conduct.html', 'Culture and conduct: deep review, adding a worked example on reading culture from everyday data'),
    ('2026-10-08', '/governance/remuneration-governance.html', 'Remuneration governance: deep review, adding a remuneration committee calendar and common mistakes'),
    ('2026-10-08', '/governance/reasonable-steps-and-consequence-management.html', 'Reasonable steps and consequence management: deep review, adding a consequence management matrix'),
    ('2026-10-08', '/governance/board-risk-reporting.html', 'Board risk reporting: deep review, adding a worked dashboard example and lessons from the Star case'),
    ('2026-10-08', '/governance/board-structure-and-accountability.html', 'Board structure and accountability: deep review, adding a worked example of how a big decision moves through the system'),
    ('2026-10-08', '/governance/financial-accountability-regime.html', 'FAR: deep review, adding the 2026 streamlining changes and a worked example tracing accountability'),
    ('2026-10-08', '/standards/aps-115.html', 'APS 115: deep review, adding how the 2026 capital changes affect operational risk capital'),
    ('2026-10-08', '/standards/aps-110-and-aps-210.html', 'APS 110 and APS 210: deep review, adding a worked capital ratio and the 2026 to 2027 bank capital and liquidity changes'),
    ('2026-10-08', '/standards/cps-190-and-cps-900.html', "CPS 190 and CPS 900: deep review, adding APRA's findings for super and a worked trustee trigger example"),
    ('2026-10-08', '/standards/cps-511.html', "CPS 511: deep review, adding SFI thresholds, a worked malus example and APRA's pre-implementation findings"),
    ('2026-10-08', '/standards/cps-510-and-cps-520.html', "CPS 510 and CPS 520: deep review, with a table of the June 2026 draft governance standard's main proposals"),
    ('2026-10-08', '/standards/cps-234.html', "CPS 234: deep review, adding APRA's 2024 and 2025 cyber letters and the overlapping incident reporting clocks"),
    ('2026-10-08', '/standards/cps-220.html', "CPS 220: deep review, adding a worked risk appetite breach example and what's changing around the standard"),
    ('2026-10-07', '/governance/conflicts-of-interest.html', "Conflicts of interest: deep review, adding a worked director's conflict example and board questions"),
    ('2026-10-07', '/standards/asic-rg-181.html', 'RG 181 (conflicts): deep review, adding common conflicts and how the rules have tightened'),
    ('2026-10-07', '/standards/asic-rg-104-and-rg-105.html', 'RG 104 and RG 105: deep review, adding the general obligations in more detail and common mistakes'),
    ('2026-10-07', '/compliance/financial-advice-regulation.html', 'Financial advice regulation: deep review, adding the August 2026 advice reform announcement'),
    ('2026-10-07', '/standards/asic-rg-271.html', 'RG 271 (complaints): deep review, adding the IDR timeframe table and IDR data reporting'),
    ('2026-10-07', '/compliance/consumer-protection.html', 'Consumer protection: deep review, with updated scams framework dates and lessons from Shield and First Guardian'),
    ('2026-10-07', '/standards/asic-rg-274.html', "RG 274 (DDO): deep review, adding ASIC's stop orders and penalties, common mistakes and board questions"),
    ('2026-10-07', '/compliance/misleading-or-deceptive-conduct.html', 'Misleading or deceptive conduct: deep review, adding the tests applied in recent greenwashing cases'),
    ('2026-10-07', '/compliance/disclosure-obligations.html', 'Disclosure obligations: deep review, adding greenwashing penalties, common mistakes and board questions'),
    ("2026-10-07", "", "New menu: Risk, Compliance, Governance, Your sector, Standards, Learn and Toolkit each open a panel of grouped topics, including \"what to do when\" guides."),
    ("2026-10-07", "/obligations/sectors.html", "New: obligations by sector. Pick super, banking, general, life or private health insurance, funds management, advice, credit or payments to see the regimes that usually apply, or compare sectors side by side."),
    ("2026-10-07", "/sectors/insurance.html", "Insurance now has three guides: general insurance, life insurance and private health insurance, with the insurance page kept as an overview."),
    ('2026-10-07', '/risk-management/enterprise-risk-management.html', 'Enterprise risk management page expanded: what CPS 220 and SPS 220 expect, common mistakes, board questions and FAQs.'),
    ('2026-10-07', '/compliance/compliance-monitoring-and-testing.html', 'Compliance monitoring page: example monitoring plan, common mistakes and board questions added.'),
    ('2026-10-07', '/risk-management/assurance-mapping.html', 'Assurance mapping page expanded: rating assurance quality, common mistakes, board questions and FAQs.'),
    ('2026-10-07', '/risk-management/kri-design-and-thresholds.html', 'KRI design page: example KRI catalogue, common mistakes and board questions added.'),
    ('2026-10-07', '/risk-management/risk-appetite-and-tolerance.html', 'Risk appetite page expanded: worked appetite metrics for a super fund, board questions and FAQs.'),
    ('2026-10-07', '/risk-management/risk-assessment-methodologies.html', 'Risk assessment methodologies page expanded: running an RCSA step by step, common mistakes, board questions and FAQs.'),
    ('2026-10-07', '/risk-management/control-testing-sampling.html', 'Control testing sampling page: common mistakes and board questions added.'),
    ('2026-10-07', '/risk-management/control-design-and-testing.html', 'Control design and testing page expanded: a worked control test, common mistakes, board questions and FAQs.'),
    ('2026-10-07', '/risk-management/operational-risk.html', 'Operational risk page expanded: example key risk indicators, common mistakes, board questions, FAQs and key dates.'),
    ('2026-10-07', '/risk-management/business-continuity.html', 'Business continuity page expanded: roles, common mistakes, board questions and FAQs.'),
    ('2026-10-07', '/risk-management/service-provider-exit-and-concentration.html', 'Service provider exit page expanded: an exit plan on a page, common mistakes and board questions.'),
    ('2026-10-07', '/risk-management/third-party-risk.html', 'Third-party risk page expanded: monitoring material providers, common mistakes, board questions, FAQs and key dates.'),
    ('2026-10-07', '/risk-management/mapping-critical-operations.html', 'Mapping critical operations page expanded: keeping maps current, common mistakes, board questions and FAQs.'),
    ('2026-10-07', '/risk-management/setting-cps-230-tolerance-levels.html', 'Setting CPS 230 tolerance levels page expanded: tolerances versus recovery objectives, a tolerance statement template, board questions and FAQs.'),
    ('2026-10-07', '/standards/cps-230.html', 'CPS 230 page expanded: the 2026 exemptions in detail, minimum critical operations, a worked example, how APRA supervises, board questions and FAQs.'),
    ('2026-10-07', '/risk-management/issue-and-action-management.html', 'Issue and action management page expanded: regulator expectations, register fields, a worked example, risk acceptance, reporting measures, common mistakes and board questions.'),
    ('2026-10-07', '/risk-management/root-cause-analysis.html', 'Root cause analysis page expanded: what regulators expect, a step-by-step method, a report structure, spotting themes across incidents, common mistakes and board questions.'),
    ('2026-10-07', '/compliance/remediation-calculations.html', 'Remediation calculations page expanded: special cases such as rollovers, deaths, switches and insurance, oversight measures, common mistakes, and the calculator updated for the current RBA cash rate.'),
    ('2026-10-07', '/standards/asic-rg-277.html', "RG 277 page expanded: calculating lost earnings, review periods, paying former customers, a worked example, ASIC's findings to 2026, common mistakes, board questions, key dates and FAQs."),
    ('2026-10-02', '/compliance/breach-significance-analysis.html', "Breach significance analysis page expanded: how ASIC's 2025 relief changes the analysis, and a new worked case on long-running investigations."),
    ('2026-10-02', '/standards/asic-rg-78.html', 'RG 78 page expanded: the key ideas in the guide, what a report contains, a worked example applying each test, common mistakes, key dates and FAQs.'),
    ('2026-10-02', '/compliance/breach-reporting.html', "Breach reporting page expanded: ASIC's 2025 relief in detail, what a breach assessment should record, ASIC's findings and the Mercer Super penalty, the AUSTRAC IFTI transition, common mistakes, key dates and FAQs."),
    ('2026-10-02', '/risk-management/incident-and-breach-management.html', "Incident and breach management page expanded: an example severity scale, what to record, ASIC's findings on slow breach identification, the Mercer Super penalty, the 2025 reporting relief, common mistakes, board questions and key dates."),
    ('2026-10-02', '/sectors/behavioural-economics-of-super.html', 'Behavioural economics of super page expanded: how the system is built around defaults, what it means for trustees, and key dates.'),
    ('2026-10-02', '/risk-management/super-liquidity-stress-testing.html', "Liquidity stress testing page expanded: a worked 30-day coverage check, APRA's liquidity findings, private markets data, common mistakes, board questions and key dates."),
    ('2026-10-02', '/sectors/unit-pricing.html', 'Unit pricing page expanded: a worked error calculation, how unit pricing is governed, outsourced pricing under CPS 230, common mistakes, board questions, key dates and FAQs.'),
    ('2026-10-02', '/sectors/fund-mergers-and-successor-fund-transfers.html', 'Fund mergers page expanded: the merger process stage by stage, tax relief, performance test histories, the 2026 ACCC merger regime, common mistakes, board questions and key dates.'),
    ('2026-10-02', '/standards/asic-rg-97.html', "RG 97 page expanded: super fee rules beyond disclosure, common mistakes, fee governance questions, key dates, FAQs, and the latest on stamp duty averaging and ASIC's 2026–27 review."),
    ('2026-10-02', '/sectors/superannuation.html', 'Superannuation trustee governance page expanded: insurance in super, recent enforcement cases, a key dates table, Payday Super and Division 296, board questions and FAQs.'),
    ("2026-10-02", "/standards/sps-530.html", "SPS 530 page expanded in depth: every requirement explained, valuation policy and revaluation triggers, liquidity and stress testing, APRA's 2023 to 2026 findings on unlisted valuations, and APRA's 2026 proposals after the Shield and First Guardian collapses."),
    ("2026-10-02", "", "Tables in articles now line up with the text column on large screens."),
    ("2026-10-02", "/standards/sps-515.html", "SPS 515 page rewritten in depth: every requirement of the 2025 version explained, APRA's crackdown on super fund spending and what it found, how SPS 515 fits with the SIS Act, a worked example, common mistakes, board questions, FAQs and a timeline."),
    ("2026-10-02", "/about/roadmap.html", "New deep review roadmap: every article is being re-checked line by line and expanded, one phase per article, with progress shown on the home page."),
    ("2026-10-01", "/learn/videos.html", "All 14 explainer videos now have a voiceover that reads the captions aloud. Captions and transcripts stay, so they still work with the sound off."),
    ("2026-10-01", "", "Guides now link straight to their playbook and board briefing (\"Put it into practice\"), and news moves to a monthly regulatory roundup."),
    ("2026-10-01", "/governance/board-briefings.html", "New board briefings: printable two-page briefings for directors on CPS 230, FAR, breach reporting, CPS 234 and AML/CTF, with questions to ask management."),
    ("2026-10-01", "/about/roadmap.html", "New site roadmap: see what we are improving, stage by stage. Also a simpler menu, a new Topics page and a new home page."),
    ("2026-10-01", "/learn/my-learning.html", "Learning pathways now work like courses: a Mark as read button and step-by-step next links on every page in a pathway, and a new My learning page with your progress and a printable record of learning."),
    ("2026-10-01", "/obligations/", "New Obligations library: 117 plain-English obligation summaries from 37 Australian regimes, with control objectives, evidence, related risks and notification deadlines. Search, filter by organisation type and download as Excel or CSV."),
    ("2026-10-01", "/playbooks/", "New Playbooks section: step-by-step guides for responding to an incident, assessing a breach, running a remediation, onboarding a material service provider, reviewing disclosure, testing a control and your first 90 days, each with a tickable checklist."),
    ("2026-10-01", "/about/editorial-standards.html", "Every content page now shows its review status (Checked against sources, or Expert reviewed) and has a Suggest a correction link. New page explaining how we check content."),
    ("2026-10-01", "/grc/model-builder.html", "GRC model builder rebuilt: a five-step wizard (or six ready-made examples) that produces a fully linked model: obligations from 37 regimes tied to risks, controls and KRIs, notification clocks, committees and roles, the data model, a maturity radar and roadmap, consistency checks, and an Excel workbook with about 20 sheets."),
    ("2026-10-01", "/grc/", "New GRC systems section: how complex organisations design and establish an integrated governance, risk and compliance system, the risk hierarchy from enterprise to Level 3, obligations and control architecture, an interactive map of how everything links, the operating model, technology, and a GRC model builder tool."),
    ("2026-10-01", "", "New artwork and a better desktop layout: all 27 graphics redone as abstract studio pieces in glass, aluminium and ceramic; wider pages on large screens, larger text, diagrams and tables that step out of the text column, and an \"On this page\" sidebar on wide screens."),
    ("2026-10-01", "", "Design polish: 11 new 3D graphics on 23 key topic pages (from CPS 230 to privacy and super), smooth fade-in as you scroll, an \"On this page\" bar on longer articles, and a \"by the numbers\" section on the home page."),
    ("2026-10-01", "/news/regulatory-tracker.html", "RBA card surcharging and interchange changes moved to In force (from 1 October 2026)."),
    ("2026-09-30", "", "New look for the whole site: a clean, light design with large tiles, our own high-definition 3D graphics for every section, a new icon, and all 14 explainer videos re-made to match."),
    ("2026-09-30", "/learn/advanced-study-program.html", "New Advanced study program: a free 12-module, university-style course built from the Advanced pages, with learning outcomes, required peer-reviewed readings, seminar questions and essay questions."),
    ("2026-09-30", "", "14 new university-level pages on the research behind risk, compliance and governance: theories of risk and regulation, governance theories, whether ERM works, the three lines, internal audit, misconduct, pay and risk-taking, whistleblowing, fraud theory, super behaviour, and the economics of cyber, climate and AML/CTF."),
    ("2026-09-30", "/learn/quizzes.html", "New University-level research quiz, a Research flashcard deck, 12 new glossary terms, and the new pages added to the learning pathways."),
    ("2026-09-30", "", "All 25 Advanced pages upgraded to university level: learning outcomes, a Theory and research section grounded in peer-reviewed studies, critical perspectives, seminar questions, further reading and APA references."),
    ("2026-09-30", "/learn/research-library.html", "New Research library: over 100 checked research sources behind the Advanced pages, grouped by topic with plain-English summaries."),
    ("2026-09-30", "/learn/videos.html", "New Videos page: 14 short explainer videos with captions and full transcripts, from the risk management loop and the Three Lines model to misleading conduct, root causes, unit pricing errors and the denominator effect, plus official videos from AUSTRAC and the ACNC."),
    ("2026-09-30", "", "Explainer videos added to 33 topic pages, next to the detail they explain. Each video can be downloaded for training, and official regulator videos only load from YouTube when you press play."),
    ("2026-09-28", "/learn/by-level.html", "New Browse by level page, with a clear definition of Beginner, Intermediate and Advanced, and every page grouped by level."),
    ("2026-09-28", "", "A new Advanced track: 17 new Advanced pages and case studies, from the legal tests for misleading conduct and directors' duties cases to APS 115 capital, KRI thresholds, root cause analysis, unit pricing and fund mergers, most with interactive calculators or simulators."),
    ("2026-09-28", "/learn/quizzes.html", "New Advanced topics quiz, two multi-regime Advanced scenarios, seven new glossary terms and 13 new Advanced flashcards."),
    ("2026-09-28", "/learn/pathways.html", "Added Advanced stages for the new pages to every learning pathway, and 'Going deeper' links from 19 Intermediate pages."),
    ("2026-09-28", "/compliance/breach-reporting.html", "Corrected the super trustee breach reporting timeframe (SIS Act s 29JA) to \"as soon as practicable, and within 30 days\" across the site and the incident report template."),
    ("2026-09-28", "", "Site-wide review: accessibility fixes (heading order and table headers), updated section descriptions, and consistency checks of regulatory deadlines across pages."),
    ("2026-09-28", "/learn/pathways.html", "Refreshed the learning pathways with the new standards, templates, case studies and scenarios, and added a pathway for banking, insurance and other sectors."),
    ("2026-09-28", "/learn/flashcards.html", "Three new flashcard decks: newer glossary terms, advanced concepts, and key dates for new and changing regimes. The standards deck now covers 32 standards and guides."),
    ("2026-09-28", "/learn/quizzes.html", "Added 55 quiz questions covering every page added since the last quiz update, plus a new News and current affairs quiz."),
    ("2026-09-28", "/learn/scenarios.html", "Six new scenario simulations: a privacy data breach, a marketing campaign review, a related-party conflict, a CPS 230 tolerance breach, an AML suspicion and an advice file review."),
    ("2026-09-28", "/tools/", "Added eight free templates: obligations register, control testing workpaper, RCSA, KRI library, example risk appetite statement, board risk report, material service provider register and remediation program tracker."),
    ("2026-09-28", "/sectors/", "Added six sector pages: credit and non-bank lenders, financial advice licensees, payments and fintech, listed companies, the Commonwealth public sector, and not-for-profits and charities."),
    ("2026-09-28", "/case-studies/", "New Case studies section: the Hayne Royal Commission, APRA's inquiry into CBA, AUSTRAC v CBA and Westpac, Optus and Medibank, HIH Insurance, and Shield and First Guardian, each with a timeline, lessons and a quiz."),
    ("2026-09-27", "/standards/", "Added 15 new explainers, including CPS 511, SPS 515, SPS 530, CPS 190 and CPS 900, RG 181, RG 270, ISO 22301, ISO 37301, ISO/IEC 42001 and the Essential Eight."),
    ("2026-09-27", "/learn/pathways.html", "Added the new risk, governance, cyber and standards pages to the learning pathways."),
    ("2026-09-27", "/governance/ai-governance.html", "Added APRA's April 2026 letter to industry on AI risk management."),
    ("2026-09-27", "/news/regulatory-tracker.html", "Added mandatory climate reporting, further financial advice reforms, the proposed modern slavery offence and the foreign bribery failure to prevent offence."),
    ("2026-09-27", "/learn/pathways.html", "Added an Advanced stage to the risk, compliance, governance and superannuation pathways."),
    ("2026-09-27", "/start-here/", "Added a \"Go deeper\" route through the seven new Advanced topics."),
    ("2026-09-27", "/glossary/", "Added VaR, expected shortfall, reverse stress testing, ICAAP, diversification benefit and tolerable deviation rate."),
    ("2026-09-27", "", "New look: the whole site moved to a dark, futuristic design, with fonts hosted on the site itself so no third-party requests are made."),
    ("2026-09-27", "/governance/financial-accountability-regime.html", "Added the regulators' proposed simplifications to the Financial Accountability Regime."),
    ("2026-09-27", "/compliance/consumer-protection.html", "Updated the Scams Prevention Framework timetable."),
    ("2026-09-27", "/glossary/", "Added 34 terms, including ADI, responsible entity, CET1, hawking, significant dealing and SMSF, and linked them from the pages that use them."),
    ("2026-09-27", "", "Added link previews for sharing, a browser-tab icon, a sitemap and a friendly page-not-found page, and made the faintest text easier to read."),
    ("2026-09-27", "", "Yearly review system: every page now shows when its next review is due, and pages checked by the site's subject-matter expert will carry an \"Expert reviewed\" badge."),
]
