# Shared GRC data model: objects (nodes) and relationships (edges). Used for the data model page and the model builder.
NODES = [
 # id, label, group, x, y, description, needed-when (regime/feature flag or '' for always)
 ('board', 'Board and committees', 'gov', 450, 40, 'Sets direction, approves the risk appetite and key frameworks, and oversees management through committees such as the board risk and audit committees.', ''),
 ('strategy', 'Strategy and objectives', 'gov', 250, 40, 'What the organisation is trying to achieve. Risks are defined relative to these objectives, and enterprise risks are the biggest threats to them.', ''),
 ('appetite', 'Risk appetite and metrics', 'gov', 650, 40, 'The board-approved statement of how much risk the organisation will accept, with tolerances and metrics for each Level 1 risk category.', ''),
 ('policy', 'Frameworks and policies', 'gov', 850, 40, 'The documents that set the rules: risk management framework, compliance framework, policies, standards and procedures.', ''),
 ('accountable', 'Accountable persons', 'gov', 60, 40, 'Executives accountable for parts of the business. Under FAR these are registered accountable persons with accountability statements and a map.', 'far'),
 ('entity', 'Legal entities and business units', 'org', 60, 180, 'The organisation hierarchy: legal entities, divisions, business units and teams. Every other object is tagged to it, so views can be cut by entity or unit.', ''),
 ('process', 'Processes', 'org', 60, 300, 'The process hierarchy (for example level 1 value chains down to level 3 procedures). Risks and controls attach to processes.', ''),
 ('critops', 'Critical operations and tolerances', 'org', 60, 420, 'Under CPS 230, the operations whose disruption would have a material adverse impact, each with board-approved tolerance levels and mapped resources.', 'cps230'),
 ('provider', 'Service providers', 'org', 60, 540, 'Third parties the organisation relies on, including material service providers under CPS 230 and their own key suppliers (fourth parties).', ''),
 ('asset', 'Information assets', 'org', 250, 540, 'Systems and data the organisation relies on. CPS 234 requires information assets to be classified and protected according to their criticality and sensitivity.', 'cps234'),
 ('risk', 'Risks (enterprise → Level 3)', 'core', 330, 240, 'The risk hierarchy: enterprise risks, Level 1 categories (material risks), Level 2 sub-types and Level 3 specific risks, each with inherent and residual ratings and an owner.', ''),
 ('obligation', 'Obligations', 'core', 570, 240, 'Atomic requirements from laws, prudential standards, regulatory guides, codes, contracts and policies, with applicability, owner and criticality.', ''),
 ('objective', 'Control objectives', 'core', 450, 340, 'Statements of what must be true for a risk to be managed or an obligation met. The bridge between risks or obligations and controls.', ''),
 ('control', 'Controls', 'core', 450, 440, 'The common control library: each control described once (who, what, when, how, evidence), classified, and linked to everything it supports.', ''),
 ('assessment', 'Risk and control assessments', 'act', 250, 340, 'Periodic first-line self-assessments (RCSA) and second-line reviews that rate risks and controls.', ''),
 ('test', 'Control testing and assurance', 'act', 650, 440, 'Design and operating effectiveness testing by the first line, second line and internal audit, coordinated through an assurance map.', ''),
 ('issue', 'Issues and actions', 'act', 650, 540, 'Weaknesses found by testing, audits, incidents or regulators, with owners, due dates, and validation before closure.', ''),
 ('incident', 'Incidents, breaches and losses', 'act', 450, 540, 'Events that happened: operational incidents, compliance breaches, near misses and losses, assessed for significance and reportability.', ''),
 ('kri', 'Key risk indicators', 'act', 250, 440, 'Metrics that signal changes in risk, with thresholds linked to appetite and triggers for escalation.', ''),
 ('change', 'Regulatory change', 'act', 850, 240, 'Horizon scanning and impact assessment of new and changing obligations, tracked through to updated controls.', ''),
 ('report', 'Reporting', 'gov', 850, 440, 'Dashboards and reports for management committees, the board and regulators, built from the linked data rather than assembled by hand.', ''),
 ('aml', 'AML/CTF program and risk assessment', 'core', 850, 340, 'For reporting entities under the AML/CTF Act: the money laundering and terrorism financing risk assessment and the AML/CTF program that responds to it.', 'aml'),
]
EDGES = [
 ('board', 'appetite', 'approves'), ('board', 'policy', 'approves'), ('board', 'strategy', 'sets'),
 ('strategy', 'risk', 'threatened by enterprise risks'), ('strategy', 'appetite', 'bounded by'),
 ('appetite', 'risk', 'sets tolerances for Level 1 risks'), ('appetite', 'kri', 'is measured by'),
 ('policy', 'objective', 'sets standards for'), ('policy', 'obligation', 'creates internal obligations'),
 ('accountable', 'entity', 'is accountable for'), ('accountable', 'risk', 'owns'), ('accountable', 'obligation', 'owns'),
 ('entity', 'process', 'performs'), ('entity', 'obligation', 'is subject to'),
 ('process', 'critops', 'makes up'), ('process', 'risk', 'is exposed to'), ('process', 'asset', 'uses'),
 ('critops', 'provider', 'depends on'), ('critops', 'risk', 'is exposed to'),
 ('provider', 'risk', 'gives rise to'), ('provider', 'control', 'operates some'),
 ('asset', 'risk', 'is exposed to'),
 ('risk', 'objective', 'is mitigated through'), ('obligation', 'objective', 'is met through'), ('obligation', 'risk', 'non-compliance is a'),
 ('objective', 'control', 'is achieved by'), ('control', 'process', 'operates in'),
 ('control', 'test', 'is tested by'), ('test', 'issue', 'raises'), ('issue', 'control', 'fixes'),
 ('assessment', 'risk', 'rates'), ('assessment', 'control', 'rates'),
 ('kri', 'risk', 'monitors'),
 ('incident', 'risk', 'is a crystallised'), ('incident', 'control', 'reveals failures of'), ('incident', 'obligation', 'may breach'),
 ('incident', 'critops', 'may disrupt'), ('incident', 'issue', 'raises'),
 ('change', 'obligation', 'updates'),
 ('report', 'board', 'informs'), ('report', 'risk', 'summarises'), ('report', 'incident', 'includes'), ('report', 'test', 'includes'),
 ('aml', 'obligation', 'implements'), ('aml', 'risk', 'assesses financial crime'), ('aml', 'control', 'specifies'),
]
GROUPS = {'gov': 'Governance', 'org': 'Organisation and operations', 'core': 'Core libraries', 'act': 'Activities'}
