"""Regulatory changes tracker data, used by _scripts/build_tracker.py to build news/regulatory-tracker.html.

Each entry:
  title, regulator, status (one of STATUSES), when (key dates in plain words),
  sectors (any of: super, bank, insurer, afsl, mis, listed, all),
  summary (plain English), page (RiskLens page or ""), source (label, official URL).
Keep AS_AT current whenever entries are checked. Only include facts checked against an official
or reputable source.
"""

AS_AT = "8 October 2026"

STATUSES = ["In force", "Finalised, starts soon", "Proposed or consultation", "Under review", "Report or guidance"]

ENTRIES = [
    # ---------------- APRA
    ("CPS 230 Operational Risk Management", "APRA", "In force", "Since {fact:cps230-start}",
     ["bank", "insurer", "super"],
     "Cross-industry standard for operational risk, business continuity and service provider management.",
     "/standards/cps-230.html", ("APRA: CPS 230", "https://www.apra.gov.au/standards/cps-230")),
    ("CPS 230 targeted amendments", "APRA", "In force", "Finalised {fact:cps230-amendments-finalised}; effective {fact:cps230-amendments-effective}",
     ["bank", "insurer", "super"],
     "Limited exemptions from some contract requirements for certain non-traditional service providers, plus updates to guidance and the material service provider register template.",
     "/standards/cps-230.html", ("APRA: final targeted amendments", "https://www.apra.gov.au/final-targeted-amendments-to-cps-230-operational-risk-management")),
    ("Draft CPS 510 Governance (consolidated)", "APRA", "Proposed or consultation",
     "Consultation closed {fact:cps510-consultation-closed}; final expected Q4 2026; to apply from early 2028",
     ["bank", "insurer", "super"],
     "One cross-industry standard replacing CPS/SPS 510, CPS/SPS 520 and SPS 521. Proposals include a 12-year default tenure limit for non-executive directors and a minimum of five directors for super trustees.",
     "/news/draft-cps-510-governance-overhaul.html", ("APRA: proposed changes to governance", "https://www.apra.gov.au/consultations/proposed-changes-governance")),
    ("Phase-out of Additional Tier 1 capital", "APRA", "Finalised, starts soon", "From {fact:at1-removal-start}; existing instruments expected to be gone by 2032",
     ["bank"],
     "Bank hybrid capital (AT1) removed from the capital framework, replaced mainly by Common Equity Tier 1 and Tier 2 capital.",
     "/sectors/banking.html", ("APRA: AT1 phase-out finalised", "https://www.apra.gov.au/news-and-publications/apra-finalises-changes-to-phase-out-additional-tier-1-capital-instruments")),
    ("Three-tier proportionality for banks", "APRA", "In force", "Confirmed 27 May 2026; in force since {fact:three-tier-start}",
     ["bank"],
     "Banks with total assets above {fact:adi-sfi-threshold} are significant financial institutions (up from $20 billion), banks above {fact:msfi-threshold} form a new top tier, and a bank moving up a tier gets 12 months to adjust. Definitions are in CPS 001.",
     "/standards/aps-110-and-aps-210.html", ("APRA: three-tiered approach to proportionality in banking", "https://www.apra.gov.au/news-and-publications/apra-formalises-three-tiered-approach-proportionality-banking-prudential")),
    ("Debt-to-income limit on home lending", "APRA", "In force", "Since {fact:dti-limit-start}",
     ["bank"],
     "No more than {fact:dti-limit-share} of an ADI's new mortgage lending may be at a debt-to-income ratio of six or more (measured separately for owner-occupier and investor lending).",
     "/sectors/banking.html", ("APRA: DTI limits", "https://www.apra.gov.au/news-and-publications/apra-limit-high-debt-income-home-loans-constrain-riskier-lending")),
    ("SPS 515 Strategic Planning and Member Outcomes (strengthened)", "APRA", "In force", "Since {fact:sps515-strengthened-start}",
     ["super"],
     "Links strategy and business planning to member outcomes, with annual business performance reviews.",
     "/sectors/superannuation.html", ("APRA: SPS 515", "https://www.apra.gov.au/standards/sps-515")),
    ("CPS 190 Recovery and Exit Planning", "APRA", "In force", "ADIs and insurers since 1 January 2024; RSE licensees since {fact:cps190-rse-start}",
     ["bank", "insurer", "super"],
     "Plans for responding to severe financial stress and for an orderly exit if needed.",
     "/sectors/banking.html", ("APRA: CPS 190", "https://www.apra.gov.au/standards/cps-190")),
    ("Letter to industry on artificial intelligence", "APRA", "Report or guidance", "Published {fact:ai-letter}",
     ["bank", "insurer", "super"],
     "APRA called for a step-change in AI-related risk management, with expectations on cyber and information security, governance, supplier risk, and change management and assurance, including for AI agents.",
     "/governance/ai-governance.html", ("APRA: step-change in AI-related risk management", "https://www.apra.gov.au/news-and-publications/apra-calls-step-change-ai-related-risk-management-and-governance")),
    ("Strengthening super investment governance (draft SPS 530)", "APRA", "Proposed or consultation",
     "Released {fact:sps530-proposals-released}; submissions close {fact:sps530-submissions-close}; final expected first half of 2027; proposed start {fact:sps530-proposed-start}",
     ["super"],
     "Member-level limits on concentrated holdings in higher-risk investments (within an APRA ceiling), stronger management of investment-related conflicts, resources matched to the investment menu, and codified expectations on onboarding, monitoring, remediation, valuations and accountability. Expected to affect platform trustees most.",
     "/standards/sps-530.html", ("APRA: proposals to strengthen trustee investment governance", "https://www.apra.gov.au/news-and-publications/apra-releases-proposals-strengthen-trustee-investment-governance")),
    ("Lower standardised credit risk weights for banks", "APRA", "Proposed or consultation",
     "Consultation opened 29 June 2026; APRA aims to finalise in the second half of 2026; proposed start {fact:risk-weights-proposed-start}",
     ["bank"],
     "Lower risk weights for some lending, including large public infrastructure, high-quality unrated corporates and residential land and construction lending. Part of a staged roadmap that also covers liquidity and market risk.",
     "/standards/aps-110-and-aps-210.html", ("APRA: changes to bank risk weights", "https://www.apra.gov.au/news-and-publications/apra-consults-changes-bank-risk-weights-designed-support-lending-and")),
    ("System Risk Stress Test results", "APRA", "Report or guidance", "Published {fact:srst-results}; bank liquidity changes to be consulted on from the second half of 2026",
     ["bank", "super"],
     "APRA's first system-wide stress test of the four major banks and six large super funds. All withstood a severe liquidity shock; APRA flagged concentration, shared service providers and similar behavioural assumptions as amplifiers.",
     "/risk-management/scenario-analysis-and-stress-testing.html", ("APRA: System Risk Stress Test findings", "https://www.apra.gov.au/news-and-publications/apra-publishes-findings-inaugural-system-risk-stress-test")),
    ("Insurance Climate Vulnerability Assessment", "APRA", "Report or guidance", "Published March 2026",
     ["insurer"],
     "Modelled home insurance to 2050 with five large insurers: under both scenarios the share of homes without adequate insurance rose from about one in seven to about one in four.",
     "/risk-management/climate-risk.html", ("APRA: Mind the Gap", "https://www.apra.gov.au/mind-gap-an-insurance-climate-vulnerability-assessment")),
    # ---------------- APRA and ASIC
    ("Financial Accountability Regime simplification", "APRA and ASIC", "Proposed or consultation",
     "Announced 16 June 2026; consultation on the first rule changes ran 2 September to {fact:far-streamlining-close}, with changes expected to take effect in early 2027; ASIC responsible manager evidence changes from October 2026; some changes need legislation",
     ["bank", "insurer", "super"],
     "Proposals to remove the key functions requirements, drop direct reports from some accountability maps, raise notification thresholds, provide statements and maps on request only, and allow more time to register accountable persons.",
     "/governance/financial-accountability-regime.html", ("ASIC: 26-204MR consultation on FAR streamlining", "https://www.asic.gov.au/about-asic/news-centre/find-a-media-release/2026-releases/26-204mr-asic-and-apra-commence-consultation-on-far-streamlining")),
    ("Financial Accountability Regime for insurers and super", "APRA and ASIC", "In force", "Since {fact:far-insurers-super-start} (ADIs since {fact:far-adi-start})",
     ["bank", "insurer", "super"],
     "Accountable persons, accountability statements and maps, deferred remuneration and consequences for failures.",
     "/governance/financial-accountability-regime.html", ("APRA: Financial Accountability Regime", "https://www.apra.gov.au/financial-accountability-regime")),
    # ---------------- ASIC
    ("Reportable situations relief (investigation period)", "ASIC", "In force", "Since 27 June 2025",
     ["afsl", "super", "bank", "insurer", "mis"],
     "ASIC relief extends the period before an investigation into a possible significant breach becomes reportable from 30 to 60 days, among other relief.",
     "/standards/asic-rg-78.html", ("ASIC: further relief under the reportable situations regime", "https://www.asic.gov.au/about-asic/news-centre/news-items/asic-gives-further-relief-for-licensees-under-the-reportable-situations-regime")),
    ("RG 181 Managing conflicts of interest (reissued)", "ASIC", "Report or guidance", "Reissued 16 December 2025",
     ["afsl", "super", "bank", "insurer", "mis"],
     "ASIC's first major update to its conflicts guidance for AFS licensees since 2004, signalling higher expectations.",
     "/governance/conflicts-of-interest.html", ("ASIC: RG 181", "https://www.asic.gov.au/regulatory-resources/find-a-document/regulatory-guides/rg-181-afs-licensing-managing-conflicts-of-interest")),
    ("Report 833: platform trustees' monitoring of risks to retirement savings", "ASIC", "Report or guidance", "Published {fact:rep833-published}",
     ["super"],
     "Review of six platform trustees found persistent gaps in monitoring advice fee deductions, unusual fees and investments, and high-risk switching.",
     "/news/super-platform-trustees-asic-rep-833.html", ("ASIC: 26-135MR", "https://www.asic.gov.au/about-asic/news-centre/find-a-media-release/2026-releases/26-135mr-asic-calls-platform-trustees-to-account-over-persistent-failures-to-safeguard-super-savings")),
    ("Report 820: private credit surveillance", "ASIC", "Report or guidance", "Published 5 November 2025; surveillance continuing in 2026",
     ["mis"],
     "Found weaker practices in conflicts, fees and margins, valuation and transparency, and terminology across private credit funds.",
     "/sectors/managed-investment-schemes.html", ("ASIC: REP 820", "https://www.asic.gov.au/regulatory-resources/find-a-document/reports/rep-820-private-credit-surveillance-report-retail-and-wholesale-surveillance/")),
    ("2026–27 supervisory priorities", "ASIC", "Report or guidance", "Published 30 September 2026",
     ["super", "bank", "insurer", "afsl"],
     "Sector priorities for banking, super, general and life insurance and markets. For super: a new review of trustees' oversight of advice fee deductions, the next phase of the member services review, and retirement income covenant performance. Also AI, scams and cyber resilience.",
     "/foundations/regulatory-landscape.html", ("ASIC: 26-232MR", "https://www.asic.gov.au/about-asic/news-centre/find-a-media-release/2026-releases/26-232mr-asic-releases-2026-27-supervisory-priorities-to-support-better-regulation-and-give-industry-greater-certainty")),
    ("Report 839: review of the first sustainability reports", "ASIC", "Report or guidance", "Published {fact:rep839-published}",
     ["listed", "super", "mis", "bank", "insurer"],
     "Review of 40 Group 1 reports: more and more comparable climate information than voluntary reporting, but room to improve forward-looking disclosures; some disclaimers inconsistent with the law's purpose.",
     "/compliance/climate-related-financial-disclosures.html", ("ASIC: sustainability reporting", "https://www.asic.gov.au/regulatory-resources/sustainability-reporting/")),
    # ---------------- Government / Treasury
    ("Payday Super", "Government and ATO", "In force", "Since {fact:payday-super-start}",
     ["super"],
     "Employers pay super with wages; contributions must generally reach the fund within seven business days of payday.",
     "/sectors/superannuation.html", ("APRA: Payday Super readiness", "https://www.apra.gov.au/payday-super-readiness")),
    ("Super performance test review", "Treasury", "Under review", "Consultation ran 7 May to 19 June 2026; outcome pending",
     ["super"],
     "Options to strengthen the annual performance test, including treatment of assets without a suitable market benchmark.",
     "/sectors/superannuation.html", ("Treasury consultation", "https://consult.treasury.gov.au/c2026-763205")),
    ("CSLR 2026–27 special levy", "Treasury", "Proposed or consultation",
     "Revised levy estimate {fact:cslr-fy27-estimate}; consultation on sharing the special levy closed in early October 2026; decision pending",
     ["afsl", "mis", "super"],
     "About {fact:cslr-advice-fy27} of the estimate relates to financial advice, well above the $20 million annual cap for advice licensees. Treasury proposed spreading the excess across advice licensees, responsible entities of managed investment schemes and other retail-facing sub-sectors.",
     "/sectors/financial-advice-licensees.html", ("Treasury: CSLR 2026–27 special levy", "https://consult.treasury.gov.au/c2026-805258")),
    ("Statutory review of corporate and tax whistleblower laws", "Treasury", "Under review",
     "Consultation ran 2 June to {fact:whistleblower-review-close}; report to government to follow",
     ["all"],
     "Review of whether the whistleblower protections work in practice, including whether disclosures to regulators other than ASIC and APRA should be protected.",
     "/governance/whistleblower-protections.html", ("Treasury: review of tax and corporate whistleblowing", "https://ministers.treasury.gov.au/ministers/daniel-mulino-2025/media-releases/review-tax-and-corporate-whistleblowing")),
    ("Mandatory climate-related financial disclosures", "ASIC and Treasury", "In force",
     "Group 1 from years starting 1 January 2025; Group 2 (including $5b+ super funds and schemes) from {fact:climate-group2-start}; Group 3 from {fact:climate-group3-start}",
     ["listed", "super", "mis", "bank", "insurer"],
     "Sustainability reports with climate statements under AASB S2, phased in by size, with assurance ramping up to reasonable assurance for years starting 1 July 2030.",
     "/compliance/climate-related-financial-disclosures.html", ("ASIC: RG 280 Sustainability reporting", "https://download.asic.gov.au/media/j4rhwyiz/rg280-published-31-march-2025.pdf")),
    ("Delivering Better Financial Outcomes: further advice reforms", "Treasury", "Proposed or consultation",
     "Tranche 1 in force since 10 January 2025; remaining reforms confirmed {fact:advice-reforms-announced}; legislation not yet passed",
     ["afsl", "super"],
     "Targeted changes to the best interests duty to enable scaled advice, streamlined statements of advice, a review of the Code of Ethics, and a new class of adviser initially limited to APRA-regulated super funds and life insurers for three years.",
     "/compliance/financial-advice-regulation.html", ("ASIC: DBFO package", "https://www.asic.gov.au/regulatory-resources/financial-services/regulatory-reforms/delivering-better-financial-outcomes-dbfo-package")),
    ("Modern slavery: failure to prevent offence and civil penalties", "Attorney-General's Department", "Proposed or consultation",
     "Announced 16 July 2026; consultation closed 25 September 2026; legislation and timing to be confirmed, with a 12 to 18 month implementation period proposed",
     ["all"],
     "A proposed criminal offence for companies with revenue over $100 million that fail to prevent modern slavery in their supply chains (with a reasonable steps defence), plus civil penalties for reporting failures.",
     "/compliance/modern-slavery.html", ("Anti-Slavery Commissioner: Government's move to strengthen laws", "https://www.antislaverycommissioner.gov.au/news/anti-slavery-commissioner-welcomes-governments-move-strengthen-modern-slavery-laws")),
    # ---------------- Financial crime, scams, privacy
    ("Failure to prevent foreign bribery offence", "Attorney-General's Department", "In force", "Since 8 September 2024",
     ["all"],
     "Companies are criminally liable if an associate bribes a foreign public official for their benefit, unless they had adequate procedures to prevent it.",
     "/compliance/anti-bribery-and-corruption.html", ("AGD: Foreign bribery", "https://www.ag.gov.au/crime/foreign-bribery")),
    ("AML/CTF reforms", "AUSTRAC", "In force", "Existing reporting entities from {fact:aml-reformed-obligations-start}; tranche 2 sectors from {fact:aml-tranche2-start}",
     ["all"],
     "Modernised obligations for existing reporting entities, and the regime extended to lawyers, accountants, real estate professionals and others. AUSTRAC has been contacting, and in September 2026 began issuing infringement notices to, businesses that should have enrolled but hadn't.",
     "/compliance/aml-ctf-fundamentals.html", ("AUSTRAC", "https://www.austrac.gov.au/")),
    ("Scams Prevention Framework", "ACCC and ASIC", "Finalised, starts soon",
     "Sectors designated May 2026; AFCA membership required for regulated services from {fact:scams-afca-membership}; most obligations from {fact:scams-main-obligations} (codes start on the later of that date and registration)",
     ["bank"],
     "Banks, telcos and digital platforms must prevent, detect, disrupt, report and respond to scams, with ASIC overseeing banks.",
     "/compliance/consumer-protection.html", ("ACCC: Scams Prevention Framework", "https://www.accc.gov.au/about-us/scams-prevention-framework")),
    ("Privacy Act reforms (first tranche)", "OAIC", "Finalised, starts soon",
     "Statutory tort in force since 10 June 2025; automated decision-making transparency from {fact:privacy-adm-start}; Children's Online Privacy Code by 10 December 2026",
     ["all"],
     "New right to sue for serious invasions of privacy, transparency duties for automated decisions, and a children's privacy code. Further reform is expected.",
     "/compliance/privacy-law.html", ("OAIC", "https://www.oaic.gov.au/privacy/australian-privacy-principles")),
    ("Privacy Act reforms (second tranche)", "Attorney-General's Department", "Proposed or consultation",
     "Exposure draft released {fact:privacy-tranche2-draft}; consultation closed {fact:privacy-tranche2-close}; bill planned for introduction by December 2026",
     ["all"],
     "Draft Privacy Amendment (Personal Data Protection) Bill 2026, centred on a requirement that handling personal information be lawful, fair and reasonable, with consent becoming one factor rather than a gateway in many cases.",
     "/compliance/privacy-law.html", ("AGD: privacy reform consultation", "https://consultations.ag.gov.au/rights-and-protections/privacy-reform/")),
    ("Evolution of the Essential Eight", "Australian Signals Directorate", "Under review",
     "Consultation closed {fact:essential-eight-consult-close}; the November 2023 maturity model still applies; no retirement date confirmed",
     ["all"],
     "The Essential Eight would become the first chapter, Essentials for enterprise IT, of a new Essentials series based on the Information Security Manual.",
     "/standards/essential-eight.html", ("ASD: consultation on evolution of Essential Eight", "https://www.cyber.gov.au/about-us/view-all-content/news/consultation-on-evolution-of-essential-eight")),
    # ---------------- Payments and fintech
    ("Removal of card surcharges and lower interchange fees", "RBA", "In force", "Most changes since 1 October 2026; foreign card interchange cap and some transparency measures from 1 April 2027",
     ["bank", "all"],
     "Surcharging removed on eftpos, Mastercard and Visa card payments, with lower interchange fee caps and more fee transparency.",
     "/sectors/payments-and-fintech.html", ("RBA: conclusions paper", "https://rba.gov.au/media-releases/2026/mr-26-10.html")),
    ("Payments licensing reforms (Tranche 1)", "Treasury", "Proposed or consultation", "Exposure draft March 2026 (consultation closed April 2026); Treasury intends to introduce a bill in 2026; proposed start 12 months after Royal Assent",
     ["bank", "afsl"],
     "Brings payment service providers into the AFS licensing regime, with APRA prudential supervision of large stored value facilities.",
     "/sectors/payments-and-fintech.html", ("Treasury: payments licensing reforms", "https://treasury.gov.au/policy-topics/banking-and-finance/payments-licensing-reforms")),
    ("Digital assets framework", "Treasury and ASIC", "Finalised, starts soon", "Law since April 2026; implementation and ASIC standards to follow",
     ["afsl"],
     "Operators of digital asset platforms and tokenised custody platforms must hold an AFSL and meet platform-specific standards.",
     "/sectors/payments-and-fintech.html", ("Parliament: Digital Assets Framework Bill", "https://www.aph.gov.au/Parliamentary_Business/Bills_Legislation/Bills_Search_Results/Result?bId=r7411")),
    ("Consumer Data Right: non-bank lenders", "Treasury and ACCC", "In force", "Product data from 13 July 2026; consumer data from 9 November 2026 (initial providers)",
     ["afsl"],
     "Non-bank lenders join the Consumer Data Right, allowing customers to share their data with accredited recipients.",
     "/sectors/payments-and-fintech.html", ("CDR: non-bank lenders sector", "https://www.cdr.gov.au/rollout/cdr-non-bank-lenders-sector")),
    # ---------------- Industry codes and standards
    ("General Insurance Code of Practice redraft", "Insurance Council of Australia", "Proposed or consultation",
     "Lodgement with ASIC now targeted for late October 2026 (delayed twice); about 24 months' transition after ASIC approval",
     ["insurer"],
     "Redrafted code proposed to be enforceable in consumer contracts, with new commitments such as automatic acceptance of some home and motor claims left undecided after 12 months.",
     "/sectors/general-insurance.html", ("ICA: Code of Practice", "https://insurancecouncil.com.au/code-of-practice/")),
    ("Life Insurance Code of Practice review", "Council of Australian Life Insurers", "Under review", "Final report 30 June 2026 (85 recommendations); industry response and code changes to follow",
     ["insurer"],
     "Independent review of the Life Code by Peter Kell, covering mental health, customer vulnerability, claims handling and sales practices, conducted in a way intended to support a possible application for ASIC approval.",
     "/sectors/life-insurance.html", ("Life Code review", "https://lifecodereview.org.au/")),
    ("ASX Corporate Governance Principles, 5th edition", "ASX", "Proposed or consultation", "Consultation draft 21 July 2026 (submissions closed {fact:asx-5th-consult-close}); recommendation to the ASX board expected by the end of 2026; proposed to apply from financial years starting 1 July 2027",
     ["listed"],
     "Update to the principles and recommendations that listed entities report against on an \"if not, why not\" basis. Keeps the eight principles, simplifies some areas and strengthens expectations on culture oversight.",
     "/sectors/listed-companies.html", ("ASX: Corporate Governance Principles and Recommendations", "https://www.asx.com.au/about/regulation/corporate-governance-principles-and-recommendations")),
]
