"""Regulatory changes tracker data, used by _scripts/build_tracker.py to build news/regulatory-tracker.html.

Each entry:
  title, regulator, status (one of STATUSES), when (key dates in plain words),
  sectors (any of: super, bank, insurer, afsl, mis, listed, all),
  summary (plain English), page (RiskLens page or ""), source (label, official URL).
Keep AS_AT current whenever entries are checked. Only include facts checked against an official
or reputable source.
"""

AS_AT = "27 September 2026"

STATUSES = ["In force", "Finalised, starts soon", "Proposed or consultation", "Under review", "Report or guidance"]

ENTRIES = [
    # ---------------- APRA
    ("CPS 230 Operational Risk Management", "APRA", "In force", "Since 1 July 2025",
     ["bank", "insurer", "super"],
     "Cross-industry standard for operational risk, business continuity and service provider management.",
     "/standards/cps-230.html", ("APRA: CPS 230", "https://www.apra.gov.au/standards/cps-230")),
    ("CPS 230 targeted amendments", "APRA", "In force", "Finalised 30 April 2026; effective 1 July 2026",
     ["bank", "insurer", "super"],
     "Limited exemptions from some contract requirements for certain non-traditional service providers, plus updates to guidance and the material service provider register template.",
     "/standards/cps-230.html", ("APRA: final targeted amendments", "https://www.apra.gov.au/final-targeted-amendments-to-cps-230-operational-risk-management")),
    ("Draft CPS 510 Governance (consolidated)", "APRA", "Proposed or consultation",
     "Consultation closed 28 August 2026; final expected Q4 2026; to apply from early 2028",
     ["bank", "insurer", "super"],
     "One cross-industry standard replacing CPS/SPS 510, CPS/SPS 520 and SPS 521. Proposals include a 12-year default tenure limit for non-executive directors and a minimum of five directors for super trustees.",
     "/news/draft-cps-510-governance-overhaul.html", ("APRA: proposed changes to governance", "https://www.apra.gov.au/consultations/proposed-changes-governance")),
    ("Phase-out of Additional Tier 1 capital", "APRA", "Finalised, starts soon", "From 1 January 2027; existing instruments expected to be gone by 2032",
     ["bank"],
     "Bank hybrid capital (AT1) removed from the capital framework, replaced mainly by Common Equity Tier 1 and Tier 2 capital.",
     "/sectors/banking.html", ("APRA: AT1 phase-out finalised", "https://www.apra.gov.au/news-and-publications/apra-finalises-changes-to-phase-out-additional-tier-1-capital-instruments")),
    ("Debt-to-income limit on home lending", "APRA", "In force", "From February 2026",
     ["bank"],
     "No more than 20% of an ADI's new mortgage lending may be at a debt-to-income ratio of six or more (measured separately for owner-occupier and investor lending).",
     "/sectors/banking.html", ("APRA: DTI limits", "https://www.apra.gov.au/news-and-publications/apra-limit-high-debt-income-home-loans-constrain-riskier-lending")),
    ("SPS 515 Strategic Planning and Member Outcomes (strengthened)", "APRA", "In force", "Since 1 July 2025",
     ["super"],
     "Links strategy and business planning to member outcomes, with annual business performance reviews.",
     "/sectors/superannuation.html", ("APRA: SPS 515", "https://www.apra.gov.au/standards/sps-515")),
    ("CPS 190 Recovery and Exit Planning", "APRA", "In force", "ADIs and insurers since 1 January 2024; RSE licensees since 1 January 2025",
     ["bank", "insurer", "super"],
     "Plans for responding to severe financial stress and for an orderly exit if needed.",
     "/sectors/banking.html", ("APRA: CPS 190", "https://www.apra.gov.au/standards/cps-190")),
    ("Letter to industry on artificial intelligence", "APRA", "Report or guidance", "Published 30 April 2026",
     ["bank", "insurer", "super"],
     "APRA called for a step-change in AI-related risk management, with expectations on cyber and information security, governance, supplier risk, and change management and assurance, including for AI agents.",
     "/governance/ai-governance.html", ("APRA: step-change in AI-related risk management", "https://www.apra.gov.au/news-and-publications/apra-calls-step-change-ai-related-risk-management-and-governance")),
    # ---------------- APRA and ASIC
    ("Financial Accountability Regime simplification", "APRA and ASIC", "Proposed or consultation",
     "Announced June 2026; ASIC responsible manager evidence changes from October 2026; some changes need legislation",
     ["bank", "insurer", "super"],
     "Proposals to provide accountability statements and maps on request only, allow more time to register accountable persons, remove key functions requirements and raise notification thresholds.",
     "/governance/financial-accountability-regime.html", ("APRA: FAR changes to reduce burden", "https://www.apra.gov.au/news-and-publications/apra-and-asic-announce-far-changes-reduce-administrative-burden")),
    ("Financial Accountability Regime for insurers and super", "APRA and ASIC", "In force", "Since 15 March 2025 (ADIs since 15 March 2024)",
     ["bank", "insurer", "super"],
     "Accountable persons, accountability statements and maps, deferred remuneration and consequences for failures.",
     "/governance/financial-accountability-regime.html", ("APRA: Financial Accountability Regime", "https://www.apra.gov.au/financial-accountability-regime")),
    # ---------------- ASIC
    ("Reportable situations relief (investigation period)", "ASIC", "In force", "Since 27 June 2025",
     ["afsl", "super", "bank", "insurer", "mis"],
     "ASIC relief extends the period before an investigation into a possible significant breach becomes reportable from 30 to 60 days, among other relief.",
     "/standards/asic-rg-78.html", ("ASIC: further relief under the reportable situations regime", "https://www.asic.gov.au/about-asic/news-centre/news-items/asic-gives-further-relief-for-licensees-under-the-reportable-situations-regime")),
    ("RG 181 Managing conflicts of interest (reissued)", "ASIC", "Report or guidance", "Reissued 16 December 2025",
     ["afsl", "super", "bank", "insurer", "mis"],
     "ASIC's first major update to its conflicts guidance for AFS licensees since 2004, signalling higher expectations.",
     "/governance/conflicts-of-interest.html", ("ASIC: RG 181", "https://www.asic.gov.au/regulatory-resources/find-a-document/regulatory-guides/rg-181-afs-licensing-managing-conflicts-of-interest")),
    ("Report 833: platform trustees' monitoring of risks to retirement savings", "ASIC", "Report or guidance", "Published 29 June 2026",
     ["super"],
     "Review of six platform trustees found persistent gaps in monitoring advice fee deductions, unusual fees and investments, and high-risk switching.",
     "/news/super-platform-trustees-asic-rep-833.html", ("ASIC: 26-135MR", "https://www.asic.gov.au/about-asic/news-centre/find-a-media-release/2026-releases/26-135mr-asic-calls-platform-trustees-to-account-over-persistent-failures-to-safeguard-super-savings")),
    ("Report 820: private credit surveillance", "ASIC", "Report or guidance", "Published 5 November 2025; surveillance continuing in 2026",
     ["mis"],
     "Found weaker practices in conflicts, fees and margins, valuation and transparency, and terminology across private credit funds.",
     "/sectors/managed-investment-schemes.html", ("ASIC: REP 820", "https://www.asic.gov.au/regulatory-resources/find-a-document/reports/rep-820-private-credit-surveillance-report-retail-and-wholesale-surveillance/")),
    # ---------------- Government / Treasury
    ("Payday Super", "Government and ATO", "In force", "Since 1 July 2026",
     ["super"],
     "Employers pay super with wages; contributions must generally reach the fund within seven business days of payday.",
     "/sectors/superannuation.html", ("APRA: Payday Super readiness", "https://www.apra.gov.au/payday-super-readiness")),
    ("Super performance test review", "Treasury", "Under review", "Consultation ran 7 May to 19 June 2026; outcome pending",
     ["super"],
     "Options to strengthen the annual performance test, including treatment of assets without a suitable market benchmark.",
     "/sectors/superannuation.html", ("Treasury consultation", "https://consult.treasury.gov.au/c2026-763205")),
    ("Mandatory climate-related financial disclosures", "ASIC and Treasury", "In force",
     "Group 1 from years starting 1 January 2025; Group 2 (including $5b+ super funds and schemes) from 1 July 2026; Group 3 from 1 July 2027",
     ["listed", "super", "mis", "bank", "insurer"],
     "Sustainability reports with climate statements under AASB S2, phased in by size, with assurance ramping up to reasonable assurance for years starting 1 July 2030.",
     "/compliance/climate-related-financial-disclosures.html", ("ASIC: RG 280 Sustainability reporting", "https://download.asic.gov.au/media/j4rhwyiz/rg280-published-31-march-2025.pdf")),
    ("Delivering Better Financial Outcomes: further advice reforms", "Treasury", "Proposed or consultation",
     "Tranche 1 in force since 10 January 2025; further tranches announced in 2026, timing not yet settled",
     ["afsl", "super"],
     "Proposals include replacing Statements of Advice with advice records and clarifying advice super funds can provide; changes to the best interests duty and a new class of adviser remain uncertain.",
     "/compliance/financial-advice-regulation.html", ("ASIC: DBFO package", "https://www.asic.gov.au/regulatory-resources/financial-services/regulatory-reforms/delivering-better-financial-outcomes-dbfo-package")),
    ("Modern slavery: failure to prevent offence and civil penalties", "Attorney-General's Department", "Proposed or consultation",
     "Announced 16 July 2026; consultation closed 25 September 2026; 12 to 18 month implementation period proposed",
     ["all"],
     "A proposed criminal offence for companies with revenue over $100 million that fail to prevent modern slavery in their supply chains (with a reasonable steps defence), plus civil penalties for reporting failures.",
     "/compliance/modern-slavery.html", ("Anti-Slavery Commissioner: Government's move to strengthen laws", "https://www.antislaverycommissioner.gov.au/news/anti-slavery-commissioner-welcomes-governments-move-strengthen-modern-slavery-laws")),
    # ---------------- Financial crime, scams, privacy
    ("Failure to prevent foreign bribery offence", "Attorney-General's Department", "In force", "Since 8 September 2024",
     ["all"],
     "Companies are criminally liable if an associate bribes a foreign public official for their benefit, unless they had adequate procedures to prevent it.",
     "/compliance/anti-bribery-and-corruption.html", ("AGD: Foreign bribery", "https://www.ag.gov.au/crime/foreign-bribery")),
    ("AML/CTF reforms", "AUSTRAC", "In force", "Existing reporting entities from 31 March 2026; tranche 2 sectors from 1 July 2026",
     ["all"],
     "Modernised obligations for existing reporting entities, and the regime extended to lawyers, accountants, real estate professionals and others.",
     "/compliance/aml-ctf-fundamentals.html", ("AUSTRAC", "https://www.austrac.gov.au/")),
    ("Scams Prevention Framework", "ACCC and ASIC", "Finalised, starts soon",
     "Sectors designated May 2026; AFCA scam complaints from 1 July 2026; rules from 1 September 2026; most obligations expected from March 2027",
     ["bank"],
     "Banks, telcos and digital platforms must prevent, detect, disrupt, report and respond to scams, with ASIC overseeing banks.",
     "/compliance/consumer-protection.html", ("ACCC: Scams Prevention Framework", "https://www.accc.gov.au/about-us/scams-prevention-framework")),
    ("Privacy Act reforms (first tranche)", "OAIC", "Finalised, starts soon",
     "Statutory tort in force since 10 June 2025; automated decision-making transparency from 10 December 2026; Children's Online Privacy Code by 10 December 2026",
     ["all"],
     "New right to sue for serious invasions of privacy, transparency duties for automated decisions, and a children's privacy code. Further reform is expected.",
     "/compliance/privacy-law.html", ("OAIC", "https://www.oaic.gov.au/privacy/australian-privacy-principles")),
    # ---------------- Industry codes and standards
    ("General Insurance Code of Practice redraft", "Insurance Council of Australia", "Proposed or consultation",
     "Lodgement with ASIC expected late October 2026; about 24 months' transition after approval",
     ["insurer"],
     "Redrafted code proposed to be enforceable in consumer contracts, with new commitments such as automatic acceptance of some home and motor claims left undecided after 12 months.",
     "/sectors/insurance.html", ("ICA: Code of Practice", "https://insurancecouncil.com.au/code-of-practice/")),
    ("Life Insurance Code of Practice review", "Council of Australian Life Insurers", "Under review", "Independent review 2025–26; final report due mid-2026",
     ["insurer"],
     "Independent review of the Life Code, conducted in a way intended to support a possible application for ASIC approval.",
     "/sectors/insurance.html", ("Life Code review", "https://lifecodereview.org.au/")),
    ("ASX Corporate Governance Principles, 5th edition", "ASX", "Proposed or consultation", "Consultation draft 21 July 2026 (submissions closed 14 September 2026); reporting expected from financial years ending 30 June or 31 December 2028",
     ["listed"],
     "Update to the principles and recommendations that listed entities report against on an \"if not, why not\" basis.",
     "/foundations/what-is-governance.html", ("ASX: Corporate Governance Principles and Recommendations", "https://www.asx.com.au/about/regulation/corporate-governance-principles-and-recommendations")),
]
