// Hand-written flashcard decks for /learn/flashcards.html. The glossary deck is
// generated separately into glossary-cards.js by _scripts/build_glossary.py.
// Keep numbers consistent with the linked pages; update both together.
window.FLASH_DECKS = [
  {
    id: "numbers",
    title: "Key numbers and deadlines",
    cards: [
      { front: "CPS 230: disruption to a critical operation outside tolerance. When must APRA be told?", back: "As soon as possible, and no later than 24 hours.", link: "/standards/cps-230.html" },
      { front: "CPS 230: material operational risk incident. Notification deadline?", back: "As soon as possible, and no later than 72 hours after becoming aware.", link: "/standards/cps-230.html" },
      { front: "CPS 230: new or materially changed material service provider arrangement. Notify APRA within?", back: "20 business days.", link: "/risk-management/third-party-risk.html" },
      { front: "CPS 234: material information security incident. Notification deadline?", back: "As soon as possible, and no later than 72 hours after becoming aware.", link: "/standards/cps-234.html" },
      { front: "CPS 234: material control weakness that can't be fixed in time. Notify APRA within?", back: "10 business days after becoming aware.", link: "/standards/cps-234.html" },
      { front: "ASIC reportable situations: deadline to report a significant breach?", back: "30 calendar days after first knowing of, or being reckless about, reasonable grounds.", link: "/standards/asic-rg-78.html" },
      { front: "Reportable situations: how long can an investigation run before it is itself reportable (with ASIC relief)?", back: "More than 60 days (the Act says 30; ASIC relief extended it from 27 June 2025).", link: "/standards/asic-rg-78.html" },
      { front: "RG 271: maximum IDR response time for most complaints?", back: "30 calendar days. Most super complaints: 45 calendar days.", link: "/standards/asic-rg-271.html" },
      { front: "DDO: significant dealing inconsistent with the TMD. Notify ASIC within?", back: "10 business days of becoming aware.", link: "/standards/asic-rg-274.html" },
      { front: "RG 277: former customers owed up to what amount can receive a residual remediation payment without reasonable endeavours to locate them?", back: "$5 or less (including interest).", link: "/standards/asic-rg-277.html" },
      { front: "FAR: minimum deferral of accountable persons' variable remuneration?", back: "At least 40% for at least four years (subject to exceptions).", link: "/governance/financial-accountability-regime.html" },
      { front: "FAR start dates?", back: "ADIs: 15 March 2024. Insurers and super trustees: 15 March 2025.", link: "/governance/financial-accountability-regime.html" },
      { front: "CPS 511: minimum deferral for the CEO of a significant financial institution?", back: "60% of variable remuneration, deferred over six years.", link: "/governance/remuneration-governance.html" },
      { front: "CPS 230 significant financial institution threshold for an RSE licensee?", back: "$30 billion in assets. (ADIs $20b; general and life insurers $10b; private health insurers $3b.)", link: "/standards/cps-230.html" },
      { front: "When did CPS 230 commence?", back: "1 July 2025.", link: "/standards/cps-230.html" },
      { front: "How many Australian Privacy Principles are there?", back: "13.", link: "/compliance/privacy-law.html" },
      { front: "Privacy Act: turnover threshold above which most businesses are covered?", back: "Annual turnover over $3 million (some smaller businesses are also covered).", link: "/compliance/privacy-law.html" },
      { front: "ISO/IEC 27001:2022 Annex A: how many controls, in how many themes?", back: "93 controls in 4 themes: organisational (37), people (8), physical (14), technological (34).", link: "/standards/iso-27001.html" },
      { front: "COSO ERM (2017) and COSO Internal Control (2013): components and principles?", back: "ERM: 5 components, 20 principles. Internal Control: 5 components, 17 principles.", link: "/standards/coso.html" },
      { front: "Financial Claims Scheme limit?", back: "Up to $250,000 per account holder per ADI.", link: "/sectors/banking.html" },
      { front: "APRA mortgage serviceability buffer?", back: "At least 3 percentage points above the loan rate.", link: "/sectors/banking.html" },
      { front: "Liquidity Coverage Ratio minimum?", back: "100%: high-quality liquid assets must cover net cash outflows over a 30-day stress.", link: "/sectors/banking.html" },
      { front: "Managed investment schemes: when is a compliance committee required?", back: "When fewer than half of the responsible entity's directors are external.", link: "/sectors/managed-investment-schemes.html" },
      { front: "Heat map score bands used on this site?", back: "1–4 Low, 5–9 Medium, 10–14 High, 15–25 Extreme (likelihood × consequence).", link: "/learn/risk-heat-map.html" }
    ]
  },
  {
    id: "standards",
    title: "Standards and guides: what's it about?",
    cards: [
      { front: "CPS 220", back: "APRA's Risk Management standard: a risk management framework, risk appetite statement, risk management strategy, and risk management and compliance functions.", link: "/standards/cps-220.html" },
      { front: "CPS 230", back: "APRA's Operational Risk Management standard: operational risk, business continuity and material service providers.", link: "/standards/cps-230.html" },
      { front: "CPS 234", back: "APRA's Information Security standard: information security capability, controls, testing and incident notification.", link: "/standards/cps-234.html" },
      { front: "CPS 511", back: "APRA's Remuneration standard: remuneration frameworks that support risk management and good outcomes, with deferral and adjustment of variable pay.", link: "/standards/cps-511.html" },
      { front: "CPS 190", back: "APRA's Recovery and Exit Planning standard: plans for responding to severe financial stress.", link: "/standards/cps-190-and-cps-900.html" },
      { front: "SPS 515", back: "APRA's Strategic Planning and Member Outcomes standard for super trustees.", link: "/standards/sps-515.html" },
      { front: "SPS 530", back: "APRA's Investment Governance standard for super trustees, including liquidity, stress testing and valuation.", link: "/standards/sps-530.html" },
      { front: "SPS 521", back: "APRA's Conflicts of Interest standard for super trustees.", link: "/governance/conflicts-of-interest.html" },
      { front: "APS 210", back: "APRA's Liquidity standard for ADIs (including the LCR and NSFR).", link: "/sectors/banking.html" },
      { front: "RG 78", back: "ASIC's guide to breach reporting (the reportable situations regime) for AFS and credit licensees.", link: "/standards/asic-rg-78.html" },
      { front: "RG 271", back: "ASIC's guide to internal dispute resolution (complaints handling), with enforceable paragraphs.", link: "/standards/asic-rg-271.html" },
      { front: "RG 274", back: "ASIC's guide to the design and distribution obligations (target market determinations).", link: "/standards/asic-rg-274.html" },
      { front: "RG 277", back: "ASIC's guide to consumer remediation.", link: "/standards/asic-rg-277.html" },
      { front: "RG 97", back: "ASIC's guide to disclosing fees and costs in PDSs and periodic statements.", link: "/compliance/disclosure-obligations.html" },
      { front: "RG 132", back: "ASIC's guide to funds management compliance and oversight (compliance plans and committees).", link: "/sectors/managed-investment-schemes.html" },
      { front: "RG 270", back: "ASIC's guide to whistleblower policies.", link: "/standards/asic-rg-270.html" },
      { front: "ISO 31000", back: "International risk management guidance: principles, framework and process. Not certifiable.", link: "/standards/iso-31000.html" },
      { front: "ISO/IEC 27001", back: "International standard for information security management systems. Certifiable.", link: "/standards/iso-27001.html" },
      { front: "SIS Act s 52", back: "The covenants in every super fund's governing rules, including the best financial interests duty.", link: "/sectors/superannuation.html" },
      { front: "Corporations Act s 912A", back: "AFS licensees' general obligations, including efficiently, honestly and fairly and adequate compliance arrangements.", link: "/compliance/licensing-basics.html" },
      { front: "CPS 510 and CPS 520", back: "APRA's Governance and Fit and Proper standards: board composition and committees, and fit and proper assessments of responsible persons. A single cross-industry replacement is in draft.", link: "/standards/cps-510-and-cps-520.html" },
      { front: "APS 110 and APS 210", back: "APRA's capital adequacy and liquidity standards for banks (ADIs).", link: "/standards/aps-110-and-aps-210.html" },
      { front: "RG 97", back: "ASIC's guide to fees and costs disclosure in PDSs and periodic statements.", link: "/standards/asic-rg-97.html" },
      { front: "RG 104 and RG 105", back: "ASIC's guides to AFS licensees' general obligations and organisational competence (responsible managers).", link: "/standards/asic-rg-104-and-rg-105.html" },
      { front: "RG 181", back: "ASIC's guide to managing conflicts of interest for AFS licensees.", link: "/standards/asic-rg-181.html" },
      { front: "RG 259", back: "ASIC's guide to risk management systems for responsible entities and other fund operators.", link: "/standards/asic-rg-259.html" },
      { front: "ISO 22301", back: "International standard for business continuity management systems. Certifiable.", link: "/standards/iso-22301.html" },
      { front: "ISO 37301", back: "International standard for compliance management systems, building on Australia's AS 3806. Certifiable.", link: "/standards/iso-37301.html" },
      { front: "ISO 37001", back: "International standard for anti-bribery management systems. Certifiable.", link: "/standards/iso-37001.html" },
      { front: "ISO/IEC 42001", back: "International standard for AI management systems. Certifiable.", link: "/standards/iso-42001.html" },
      { front: "Essential Eight", back: "The Australian Signals Directorate's eight baseline cyber mitigation strategies, assessed at maturity levels Zero to Three.", link: "/standards/essential-eight.html" },
      { front: "Global Internal Audit Standards", back: "The IIA's standards for internal audit, in effect from 9 January 2025: five domains and fifteen principles.", link: "/standards/global-internal-audit-standards.html" }
    ]
  },
  {
    id: "advanced",
    title: "Advanced concepts",
    cards: [
      { front: "Frequency and severity", back: "The two parts of a loss distribution model: how many loss events happen in a year, and how big each one is.", link: "/risk-management/quantitative-operational-risk.html" },
      { front: "Why operational loss averages mislead", back: "Losses are heavy-tailed: most are small but a rare few are enormous and dominate the total.", link: "/risk-management/quantitative-operational-risk.html" },
      { front: "Value-at-risk (VaR) vs expected shortfall", back: "VaR is a bad year at a chosen confidence level. Expected shortfall is the average of the years worse than that.", link: "/risk-management/quantitative-operational-risk.html" },
      { front: "Diversification benefit", back: "The reduction in total risk because risks don't all go wrong together. It can vanish in a crisis, when correlations rise.", link: "/risk-management/risk-aggregation-and-correlation.html" },
      { front: "Why heat-map scores can't be added", back: "They are rankings, not measurements, so sums or averages look precise but don't measure total risk.", link: "/risk-management/risk-aggregation-and-correlation.html" },
      { front: "Reverse stress testing", back: "Starting from failure and working back to the scenarios that could cause it.", link: "/risk-management/scenario-analysis-and-stress-testing.html" },
      { front: "Severe but plausible", back: "The standard for stress scenarios: bad enough to test resilience, realistic enough to be taken seriously.", link: "/risk-management/scenario-analysis-and-stress-testing.html" },
      { front: "Setting tolerance levels 'outside in'", back: "Start from the harm to customers, legal obligations and the system, not from what current systems can achieve.", link: "/risk-management/setting-cps-230-tolerance-levels.html" },
      { front: "Tolerable deviation rate", back: "The highest rate of control failure you can accept and still rely on the control.", link: "/risk-management/control-testing-sampling.html" },
      { front: "Upper deviation limit", back: "Given what a sample found, how high the true deviation rate could be at a chosen confidence level. Compare it with the tolerable rate.", link: "/risk-management/control-testing-sampling.html" },
      { front: "Deemed-significant breach", back: "A breach that is automatically significant under s 912D(4), such as one causing material loss or damage to clients, whatever its size.", link: "/compliance/breach-significance-analysis.html" },
      { front: "Closure vs validation", back: "Closure: the owner says an issue is fixed. Validation: someone independent confirms the fix works.", link: "/risk-management/issue-and-action-management.html" },
      { front: "Combined assurance", back: "Coordinating first-line, second-line, internal audit and external assurance so the board gets one joined-up picture.", link: "/risk-management/assurance-mapping.html" },
      { front: "Triangulating risk culture", back: "Combining what people say (surveys), what they do (behavioural data) and what the organisation has built (systems and incentives).", link: "/governance/risk-culture-assessment.html" },
      { front: "Model risk tiering", back: "Ranking models by materiality and complexity so the most important get the most validation and oversight.", link: "/risk-management/model-risk.html" },
      { front: "Model drift", back: "A model's performance degrading over time because the data or environment has changed since it was built.", link: "/risk-management/model-risk.html" },
      { front: "Dominant message (ACCC v TPG, 2013)", back: "The main impression an ad creates. Fine print that contradicts a prominent headline may not correct it.", link: "/compliance/misleading-or-deceptive-conduct.html" },
      { front: "Representations about future matters", back: "Taken to be misleading if made without reasonable grounds (ASIC Act s 12BB; Corporations Act s 769C).", link: "/compliance/misleading-or-deceptive-conduct.html" },
      { front: "Business judgment rule: the four conditions", back: "Good faith and proper purpose; no material personal interest; informed to the extent reasonably believed appropriate; rational belief it is in the company's best interests (s 180(2)).", link: "/governance/directors-duties-case-law.html" },
      { front: "Maximum civil penalty for a company (s 1317G)", back: "Greatest of 50,000 penalty units, 3 × benefit obtained or detriment avoided, or 10% of annual turnover capped at 2.5 million penalty units. A penalty unit is $364 from 1 July 2026.", link: "/compliance/enforcement-and-penalties.html" },
      { front: "Main purpose of civil penalties", back: "Deterrence, specific and general (Pattinson, High Court, 2022).", link: "/compliance/enforcement-and-penalties.html" },
      { front: "APS 115 capital tiers", back: "12% of the business indicator up to $1.5 billion, 15% from $1.5 billion to $45 billion, 18% above. Multiply by 12.5 for risk-weighted assets.", link: "/standards/aps-115.html" },
      { front: "Latent conditions (Swiss cheese model)", back: "Weaknesses built into systems and decisions, often long before an incident, that line up with front-line errors.", link: "/risk-management/root-cause-analysis.html" },
      { front: "Pre-mortem", back: "Before deciding, imagine the decision has failed badly and explain why. Counters optimism and groupthink.", link: "/risk-management/human-factors-and-bias.html" },
      { front: "FAR Act s 22: reasonable steps include", back: "Appropriate governance, control and risk management; safeguards against inappropriate delegation; procedures to identify and remediate problems.", link: "/governance/reasonable-steps-and-consequence-management.html" },
      { front: "RBA cash rate + 6%", back: "A rate ASIC indicates can be used for foregone returns where actual returns can't be worked out and it benefits consumers (RG 277).", link: "/compliance/remediation-calculations.html" },
      { front: "Unit pricing error threshold in RG 94", back: "0.30% of the unit price has commonly been used. Whether relying on it fits trustees' duties is debated.", link: "/sectors/unit-pricing.html" },
      { front: "Stressed exit", back: "Leaving a service provider when it has failed or can't be relied on: little cooperation, little time.", link: "/risk-management/service-provider-exit-and-concentration.html" },
      { front: "Acts Interpretation Act s 15AA", back: "Prefer the interpretation that best achieves the purpose or object of the Act.", link: "/compliance/interpreting-legislation.html" }
    ]
  },
  {
    id: "dates",
    title: "Key dates: new and changing regimes (2026)",
    cards: [
      { front: "Payday Super started", back: "1 July 2026. Contributions must generally reach the fund within seven business days of payday.", link: "/news/2026-09-regulatory-roundup.html" },
      { front: "AML/CTF tranche 2 started", back: "1 July 2026, bringing lawyers, accountants, real estate professionals and others into the regime. Changed obligations for existing reporting entities began on 31 March 2026.", link: "/compliance/aml-ctf-fundamentals.html" },
      { front: "CPS 230 commenced", back: "1 July 2025. APRA's targeted amendments took effect on 1 July 2026.", link: "/standards/cps-230.html" },
      { front: "Mandatory climate reporting: Group 1, 2 and 3 start dates", back: "Financial years starting on or after 1 January 2025 (Group 1), 1 July 2026 (Group 2) and 1 July 2027 (Group 3).", link: "/compliance/climate-related-financial-disclosures.html" },
      { front: "Failure to prevent foreign bribery offence commenced", back: "8 September 2024.", link: "/compliance/anti-bribery-and-corruption.html" },
      { front: "National Anti-Corruption Commission began operating", back: "1 July 2023.", link: "/compliance/anti-bribery-and-corruption.html" },
      { front: "Buy now pay later became regulated credit", back: "10 June 2025.", link: "/sectors/credit-and-non-bank-lenders.html" },
      { front: "Card surcharges removed on designated networks", back: "Mostly from 1 October 2026 (RBA reforms).", link: "/sectors/payments-and-fintech.html" },
      { front: "Privacy: automated decision-making transparency", back: "Privacy policies must explain substantially automated decisions from 10 December 2026.", link: "/governance/ai-governance.html" },
      { front: "APRA phase-out of Additional Tier 1 capital", back: "Begins 1 January 2027.", link: "/standards/aps-110-and-aps-210.html" },
      { front: "IIA Global Internal Audit Standards effective", back: "9 January 2025. Cybersecurity topical requirement from February 2026.", link: "/standards/global-internal-audit-standards.html" },
      { front: "Commonwealth Fraud and Corruption Control Framework", back: "In effect since 1 July 2024.", link: "/sectors/public-sector.html" },
      { front: "Draft CPS 510 (governance): expected timing", back: "Final standard expected late 2026, applying from early 2028. Still a draft.", link: "/news/draft-cps-510-governance-overhaul.html" },
      { front: "Scams Prevention Framework rules", back: "Started 1 September 2026. Most obligations expected to apply from March 2027.", link: "/compliance/consumer-protection.html" }
    ]
  }
];

// Glossary terms added since the flashcards launched (September 2026). Shown as their own deck.
window.GLOSSARY_NEW = ["business-judgment-rule", "denominator-effect", "dominant-message", "run-rule", "substitutability", "successor-fund-transfer", "unit-price", "adi", "assurance-map", "at1", "awareness", "beneficial-assumption", "cet1", "claims-handling", "compliance-committee", "compliance-plan", "cps-511", "deemed-significant-breach", "deferred-sales-model", "distribution-condition", "diversification-benefit", "dti-limit", "essential-eight", "expected-shortfall", "financial-hardship", "fraud-triangle", "greenwashing", "hawking", "icaap", "information-asset", "isms", "issue", "key-function", "lcr", "macroprudential-policy", "managed-investment-scheme", "model-risk", "product-intervention-power", "recovery-and-exit-planning", "responsible-entity", "responsible-manager", "reverse-stress-testing", "review-trigger", "sampling", "scams-prevention-framework", "sfi", "significant-dealing", "smsf", "sps-515", "tolerable-deviation-rate", "utmost-good-faith", "var", "vulnerable-customer"];
