// Generated by _scripts/build_glossary.py. Do not edit by hand.
window.GLOSSARY_CARDS = [
{
"slug": "accountability-map",
"term": "Accountability map",
"abbr": "",
"def": "Under the Financial Accountability Regime, a document showing the key roles and responsibilities across an accountable entity and its group, and who is accountable for each."
},
{
"slug": "accountability-statement",
"term": "Accountability statement",
"abbr": "",
"def": "Under the Financial Accountability Regime, a document describing the specific parts of the business an individual accountable person is responsible for."
},
{
"slug": "accountable-person",
"term": "Accountable person",
"abbr": "",
"def": "Under the Financial Accountability Regime, a director or senior executive with actual or effective senior responsibility for a key part of a bank, insurer or super trustee. Accountable persons must be registered with APRA and meet specific accountability obligations."
},
{
"slug": "at1",
"term": "Additional Tier 1 capital",
"abbr": "AT1",
"def": "Bank capital instruments, often called hybrids, that can be converted into shares or written off if a bank gets into trouble. APRA has decided to phase them out from 1 January 2027, replacing them mainly with CET1 and Tier 2 capital."
},
{
"slug": "agency-theory",
"term": "Agency theory",
"abbr": "",
"def": "A theory of governance that treats managers as agents of the owners (principals) who may pursue their own interests. It explains the use of monitoring, independent boards and incentive pay to align managers with owners."
},
{
"slug": "aml-ctf",
"term": "Anti-money laundering and counter-terrorism financing",
"abbr": "AML/CTF",
"def": "The laws and controls that stop criminals using legitimate businesses to hide the proceeds of crime or fund terrorism. In Australia the main law is the Anti-Money Laundering and Counter-Terrorism Financing Act 2006 (Cth), administered by AUSTRAC."
},
{
"slug": "assurance",
"term": "Assurance",
"abbr": "",
"def": "An objective check that gives decision-makers confidence that something (a control, a process, a report) is working as intended. Internal audit provides independent assurance; management and second-line functions can also provide assurance."
},
{
"slug": "assurance-map",
"term": "Assurance map",
"abbr": "",
"def": "A picture showing, for each key risk, which assurance providers (management, risk and compliance, internal audit and external parties) check it, how much and how well, to reveal gaps and duplication."
},
{
"slug": "atomic-obligation",
"term": "Atomic obligation",
"abbr": "",
"def": "An obligation broken down to a single, specific requirement that one owner can be accountable for and that can be tested, rather than a whole Act or standard."
},
{
"slug": "accc",
"term": "Australian Competition and Consumer Commission",
"abbr": "ACCC",
"def": "The national regulator for competition, fair trading and consumer protection. It enforces the Competition and Consumer Act 2010 (Cth), including the Australian Consumer Law, across most of the economy."
},
{
"slug": "credit-licence",
"term": "Australian credit licence",
"abbr": "ACL",
"def": "The licence a business needs from ASIC to engage in consumer credit activities, such as lending or broking, under the National Consumer Credit Protection Act 2009 (Cth)."
},
{
"slug": "afca",
"term": "Australian Financial Complaints Authority",
"abbr": "AFCA",
"def": "The free, independent external dispute resolution scheme for consumers and small businesses who can't resolve a complaint with their financial firm. Financial firms must be members by law or licence condition."
},
{
"slug": "afsl",
"term": "Australian financial services licence",
"abbr": "AFSL",
"def": "The licence a business needs from ASIC to carry on a financial services business in Australia, such as giving financial product advice or dealing in financial products. Licensees must meet ongoing general obligations, including acting efficiently, honestly and fairly."
},
{
"slug": "app",
"term": "Australian Privacy Principles",
"abbr": "APPs",
"def": "The 13 principles in the Privacy Act 1988 (Cth) that govern how Australian Government agencies and most larger private organisations collect, use, disclose, store and secure personal information."
},
{
"slug": "apra",
"term": "Australian Prudential Regulation Authority",
"abbr": "APRA",
"def": "The \"prudential\" regulator. APRA supervises banks and other authorised deposit-taking institutions, insurers, friendly societies and most superannuation funds, with a focus on keeping them financially sound so they can meet their promises to depositors, policyholders and members."
},
{
"slug": "asic",
"term": "Australian Securities and Investments Commission",
"abbr": "ASIC",
"def": "The corporate, markets, financial services and consumer credit regulator. ASIC focuses on conduct: whether companies and licensees treat consumers and investors fairly and obey the law."
},
{
"slug": "austrac",
"term": "Australian Transaction Reports and Analysis Centre",
"abbr": "AUSTRAC",
"def": "Australia's financial intelligence agency and AML/CTF regulator. Businesses that provide \"designated services\" must enrol with AUSTRAC, run an AML/CTF program and report certain transactions and suspicious matters."
},
{
"slug": "adi",
"term": "Authorised deposit-taking institution",
"abbr": "ADI",
"def": "A bank, building society or credit union authorised by APRA under the Banking Act 1959 (Cth) to take deposits from the public. ADIs must meet APRA's prudential standards on capital, liquidity, risk management and governance."
},
{
"slug": "authorised-representative",
"term": "Authorised representative",
"abbr": "",
"def": "A person or company authorised by an AFS licensee to provide financial services on the licensee's behalf. The licensee remains responsible for its representatives' conduct."
},
{
"slug": "awareness",
"term": "Awareness (reporting clock)",
"abbr": "",
"def": "The point from which most breach and incident reporting deadlines are counted. It is usually when the organisation first knows, or is reckless about, reasonable grounds to believe a reportable event has happened, not when an investigation is finished. Recording this date accurately is essential."
},
{
"slug": "beneficial-assumption",
"term": "Beneficial assumption",
"abbr": "",
"def": "In remediation, an assumption made in the customer's favour where records are missing or incomplete, so gaps in data don't leave people under-compensated."
},
{
"slug": "best-financial-interests-duty",
"term": "Best financial interests duty",
"abbr": "",
"def": "The covenant in the SIS Act (s 52(2)(c)) requiring super trustees to perform their duties and exercise their powers in the best financial interests of members. The word \"financial\" was added from 1 July 2021."
},
{
"slug": "best-interests-duty",
"term": "Best interests duty",
"abbr": "",
"def": "The obligation on financial advisers giving personal advice to retail clients to act in the client's best interests (Corporations Act s 961B), and related duties to give appropriate advice and prioritise the client's interests."
},
{
"slug": "board",
"term": "Board",
"abbr": "",
"def": "The group of directors elected to oversee a company or trustee. The board sets direction and risk appetite, appoints and monitors senior management, and is ultimately accountable for the organisation. Also called the governing body."
},
{
"slug": "board-risk-committee",
"term": "Board risk committee",
"abbr": "",
"def": "A committee of the board that oversees the risk management framework and risk profile in more detail than the full board can. APRA requires larger regulated entities to have one."
},
{
"slug": "bow-tie-analysis",
"term": "Bow-tie analysis",
"abbr": "",
"def": "A diagram that puts a risk event in the middle, its causes on the left and its consequences on the right. Preventive controls sit between causes and event; mitigating controls sit between event and consequences. The shape looks like a bow tie."
},
{
"slug": "breach",
"term": "Breach",
"abbr": "",
"def": "A failure to comply with an obligation, such as a law, licence condition, regulatory standard or internal policy. Some breaches must be reported to a regulator."
},
{
"slug": "breach-register",
"term": "Breach register",
"abbr": "",
"def": "A log of actual and possible breaches, recording what happened, the assessment, whether it was reportable, and how it was fixed. It helps an organisation spot patterns and show regulators how breaches were handled."
},
{
"slug": "bcp",
"term": "Business continuity plan",
"abbr": "BCP",
"def": "A documented plan for keeping important services running, or getting them back quickly, when something disrupts normal operations (for example a cyber attack, system outage, pandemic or loss of a key supplier)."
},
{
"slug": "bia",
"term": "Business impact analysis",
"abbr": "BIA",
"def": "A structured look at what would happen if a business process or service were disrupted: how quickly harm builds up, what the process depends on, and how fast it must be restored. It is the starting point for business continuity planning."
},
{
"slug": "business-judgment-rule",
"term": "Business judgment rule",
"abbr": "",
"def": "A protection in s 180(2) of the Corporations Act for directors and officers who make a business decision in good faith and for a proper purpose, without a material personal interest, having informed themselves appropriately, and rationally believing it is in the company's best interests. It only covers the duty of care and diligence."
},
{
"slug": "claims-handling",
"term": "Claims handling and settling services",
"abbr": "",
"def": "Helping a person make an insurance claim, or managing or settling claims on behalf of an insurer. Since 1 January 2022 this is a financial service that needs an AFS licence (with some exceptions), bringing claims conduct under ASIC's oversight."
},
{
"slug": "clawback",
"term": "Clawback",
"abbr": "",
"def": "Recovering variable remuneration that has already been paid or vested, for example after later-discovered misconduct or risk failures. Compare malus."
},
{
"slug": "cet1",
"term": "Common Equity Tier 1 capital",
"abbr": "CET1",
"def": "The highest-quality form of bank capital, made up mainly of ordinary shares and retained earnings. It absorbs losses first while the bank keeps operating, and is the main focus of capital ratios."
},
{
"slug": "compliance",
"term": "Compliance",
"abbr": "",
"def": "Meeting your obligations: the laws, regulations, licence conditions, industry codes, contracts and internal policies that apply to you. A compliance function helps the business identify its obligations, build them into how it works, and check they are being met."
},
{
"slug": "compliance-committee",
"term": "Compliance committee",
"abbr": "",
"def": "A committee a responsible entity must have if fewer than half of its directors are external. Most members must be external. It monitors compliance with the compliance plan and reports breaches to the responsible entity (and to ASIC if not dealt with)."
},
{
"slug": "compliance-obligation",
"term": "Compliance obligation",
"abbr": "",
"def": "A specific requirement the organisation must (or has chosen to) meet, for example a section of an Act, a clause of a prudential standard or a commitment in an industry code."
},
{
"slug": "compliance-plan",
"term": "Compliance plan",
"abbr": "",
"def": "A document every registered managed investment scheme must have, setting out the measures the responsible entity will apply to make sure it complies with the Corporations Act and the scheme's constitution. It is lodged with ASIC and audited every year."
},
{
"slug": "compliance-risk",
"term": "Compliance risk",
"abbr": "",
"def": "The risk of legal or regulatory penalties, financial loss or damage to reputation because the organisation fails to meet its obligations."
},
{
"slug": "concentration-risk",
"term": "Concentration risk",
"abbr": "",
"def": "The risk that comes from relying too heavily on one thing, such as one borrower, industry, supplier or system, so that a single failure has an outsized impact."
},
{
"slug": "conduct-risk",
"term": "Conduct risk",
"abbr": "",
"def": "The risk that the way an organisation or its people behave leads to poor outcomes for customers or members, or harms market integrity."
},
{
"slug": "conflict-of-interest",
"term": "Conflict of interest",
"abbr": "",
"def": "A situation where a person's or organisation's own interests could influence, or be seen to influence, a decision they are meant to make in someone else's interest."
},
{
"slug": "consequence",
"term": "Consequence",
"abbr": "",
"def": "The outcome of an event and how much it affects objectives, for example financial loss, harm to customers, regulatory action or reputational damage. Often called impact or severity."
},
{
"slug": "control",
"term": "Control",
"abbr": "",
"def": "Any measure that changes a risk: a process, policy, system setting, check or approval that makes a bad event less likely or reduces its impact."
},
{
"slug": "control-design-effectiveness",
"term": "Control design effectiveness",
"abbr": "",
"def": "Whether a control, if it works as described, is actually capable of managing the risk it is meant to manage. A well-designed control targets the right cause, at the right time, with the right coverage."
},
{
"slug": "control-environment",
"term": "Control environment",
"abbr": "",
"def": "The overall attitude, structures and standards that shape how seriously controls are taken across an organisation, including tone from leaders, accountability and competence. It is the foundation component of the COSO internal control framework."
},
{
"slug": "control-objective",
"term": "Control objective",
"abbr": "",
"def": "A statement of what must be true for a risk to be managed or an obligation to be met (for example, only authorised changes are made to pricing systems). Controls are mapped to control objectives, which are mapped to risks and obligations."
},
{
"slug": "control-operating-effectiveness",
"term": "Control operating effectiveness",
"abbr": "",
"def": "Whether a control actually operated as designed, consistently, over a period of time. Tested by checking evidence from a sample of occasions the control should have run."
},
{
"slug": "control-owner",
"term": "Control owner",
"abbr": "",
"def": "The person accountable for making sure a control is designed properly, performed and evidenced."
},
{
"slug": "control-testing",
"term": "Control testing",
"abbr": "",
"def": "Checking whether controls are well designed and working in practice, using methods such as walkthroughs, inspection of evidence, re-performance and data analysis."
},
{
"slug": "core-obligation",
"term": "Core obligation",
"abbr": "",
"def": "Under ASIC's reportable situations regime, the set of key obligations (including the general licensee obligations and key financial services laws) whose significant breach must be reported."
},
{
"slug": "coso",
"term": "COSO",
"abbr": "",
"def": "The Committee of Sponsoring Organizations of the Treadway Commission, a US private-sector body. It publishes two widely used frameworks: Internal Control – Integrated Framework (2013) and Enterprise Risk Management – Integrating with Strategy and Performance (2017)."
},
{
"slug": "cps-230",
"term": "CPS 230",
"abbr": "",
"def": "APRA's cross-industry prudential standard on operational risk management, in force from 1 July 2025. It covers operational risk, business continuity and management of service providers, and replaced earlier standards on outsourcing and business continuity."
},
{
"slug": "cps-511",
"term": "CPS 511 Remuneration",
"abbr": "",
"def": "APRA's prudential standard on remuneration for banks, insurers and super trustees. It requires remuneration frameworks to support sound risk management and long-term outcomes, gives risk and conduct real weight in variable pay, and sets deferral and clawback requirements for significant financial institutions."
},
{
"slug": "credit-risk",
"term": "Credit risk",
"abbr": "",
"def": "The risk of loss because a borrower or counterparty does not pay what it owes, in full or on time."
},
{
"slug": "critical-operation",
"term": "Critical operation",
"abbr": "",
"def": "Under APRA's CPS 230, a process or service that, if disrupted beyond tolerance, would have a material adverse impact on depositors, policyholders, members or the entity's role in the financial system. Regulated entities must identify them and set tolerance levels for them."
},
{
"slug": "cdd",
"term": "Customer due diligence",
"abbr": "CDD",
"def": "Checking who a customer is and understanding the ML/TF risk they pose, before and during the relationship. Often called \"know your customer\" (KYC). A core AML/CTF obligation."
},
{
"slug": "dti-limit",
"term": "Debt-to-income limit",
"abbr": "DTI limit",
"def": "A macroprudential limit on how much new home lending a bank can do to borrowers whose total debt is high compared with their income. APRA's limit, from February 2026, caps new lending at a debt-to-income ratio of six or more at 20% of an ADI's new mortgage lending."
},
{
"slug": "deemed-significant-breach",
"term": "Deemed significant breach",
"abbr": "",
"def": "A breach of a core obligation that the law automatically treats as significant, and therefore reportable to ASIC, without a significance assessment. Examples include breaches of civil penalty provisions (unless excluded), serious offences, and breaches that cause or are likely to cause material loss or damage to clients."
},
{
"slug": "default-effect",
"term": "Default effect",
"abbr": "",
"def": "The tendency of people to stick with a pre-set option rather than make an active choice. It explains why default super funds, contribution rates and investment options have such a large influence on outcomes."
},
{
"slug": "deferred-sales-model",
"term": "Deferred sales model",
"abbr": "",
"def": "The rules for add-on insurance sold alongside a car or other major purchase. The insurance generally cannot be sold until a waiting period has passed after the main sale, giving the customer time to consider whether they need it."
},
{
"slug": "denominator-effect",
"term": "Denominator effect",
"abbr": "",
"def": "When listed assets fall in value faster than unlisted assets are revalued, unlisted assets become a larger share of a portfolio without any new investment. Outflows paid from liquid assets make it larger still."
},
{
"slug": "ddo",
"term": "Design and distribution obligations",
"abbr": "DDO",
"def": "Rules (Part 7.8A of the Corporations Act, from 5 October 2021) requiring issuers to design financial products for a defined target market and take reasonable steps so that products reach the right consumers."
},
{
"slug": "design-authority",
"term": "Design authority",
"abbr": "",
"def": "A small group that owns a GRC system's taxonomies, methodology, data model and reference lists, and approves any changes to them, so the system stays consistent over time."
},
{
"slug": "designated-service",
"term": "Designated service",
"abbr": "",
"def": "A service listed in the AML/CTF Act (such as opening an account, making a loan or, from 1 July 2026, certain legal, accounting and real estate services). Providing one makes a business a reporting entity."
},
{
"slug": "detective-control",
"term": "Detective control",
"abbr": "",
"def": "A control that finds a problem after it has happened, such as a reconciliation, exception report or review. Compare preventive control."
},
{
"slug": "disclosable-matter",
"term": "Disclosable matter",
"abbr": "",
"def": "Under the Corporations Act whistleblower regime, information about misconduct or an improper state of affairs relating to a company, which qualifies a disclosure for protection."
},
{
"slug": "distribution-condition",
"term": "Distribution condition",
"abbr": "",
"def": "A condition in a target market determination that limits how a product can be sold, such as only through certain channels or only after certain checks, to make it more likely it reaches the intended customers."
},
{
"slug": "diversification-benefit",
"term": "Diversification benefit",
"abbr": "",
"def": "The amount by which a combined risk measure is lower than the simple sum of individual risks, because the risks are unlikely to all go wrong at once. It depends on correlation assumptions and can shrink sharply in a crisis."
},
{
"slug": "dominant-message",
"term": "Dominant message",
"abbr": "",
"def": "The main impression a communication creates, for example through its headline. Courts assess whether conduct is misleading by the overall impression, and fine print may not correct a misleading dominant message."
},
{
"slug": "due-diligence",
"term": "Due diligence",
"abbr": "",
"def": "Reasonable investigation before a decision, for example checking a potential service provider's financial health, security and track record before signing a contract."
},
{
"slug": "ehf",
"term": "Efficiently, honestly and fairly",
"abbr": "",
"def": "The overarching general obligation on AFS and credit licensees to do all things necessary to ensure their financial services are provided efficiently, honestly and fairly. It has been a civil penalty provision since 2019."
},
{
"slug": "eligible-whistleblower",
"term": "Eligible whistleblower",
"abbr": "",
"def": "A person who can qualify for protection under the Corporations Act whistleblower regime, such as a current or former officer, employee, supplier or associate of the company, or their relatives or dependants."
},
{
"slug": "emerging-risk",
"term": "Emerging risk",
"abbr": "",
"def": "A new or changing risk that is not yet well understood or measured, such as a new technology, regulatory direction or climate-related change."
},
{
"slug": "enterprise-risk",
"term": "Enterprise risk",
"abbr": "",
"def": "One of the few most significant risks to an organisation's strategy, viability or reputation, viewed top-down across risk categories and usually owned by executives and overseen by the board."
},
{
"slug": "erm",
"term": "Enterprise risk management",
"abbr": "ERM",
"def": "Managing risk across the whole organisation in a joined-up way, linked to strategy, rather than in separate silos. ERM looks at how risks interact and at the organisation's total risk profile."
},
{
"slug": "essential-eight",
"term": "Essential Eight",
"abbr": "",
"def": "The Australian Signals Directorate's baseline set of eight cyber security mitigation strategies, such as patching, multi-factor authentication and backups, assessed against maturity levels from zero to three."
},
{
"slug": "expected-shortfall",
"term": "Expected shortfall",
"abbr": "ES",
"def": "The average loss in the worst outcomes beyond a chosen confidence level. For example, 99% expected shortfall is the average of the worst 1% of years. Unlike VaR, it looks into the tail."
},
{
"slug": "externality",
"term": "Externality",
"abbr": "",
"def": "A cost or benefit of an activity that falls on someone other than the party carrying it out. In cyber security, for example, a breach may harm customers more than the firm that could have prevented it."
},
{
"slug": "far",
"term": "Financial Accountability Regime",
"abbr": "FAR",
"def": "A law that sets accountability obligations for banks, insurers and superannuation trustees and their directors and most senior executives (accountable persons). It is jointly administered by APRA and ASIC. It started for banks on 15 March 2024 and for insurers and super trustees on 15 March 2025."
},
{
"slug": "financial-hardship",
"term": "Financial hardship",
"abbr": "",
"def": "When a customer can't meet their repayments or other financial obligations, for example because of illness, job loss or a disaster. Credit providers must respond to hardship notices under the National Credit Code, and industry codes set further expectations for banks and insurers."
},
{
"slug": "fsg",
"term": "Financial Services Guide",
"abbr": "FSG",
"def": "A document given to retail clients explaining who the provider is, what services they offer, how they are paid and how to complain."
},
{
"slug": "first-line",
"term": "First line",
"abbr": "",
"def": "In the Three Lines model, the people and teams who deliver products and services and own and manage the risks in their day-to-day work."
},
{
"slug": "fourth-party",
"term": "Fourth party",
"abbr": "",
"def": "A supplier's supplier: a company that your service provider relies on (a subcontractor). Problems at a fourth party can disrupt you even though you have no contract with them."
},
{
"slug": "fraud-triangle",
"term": "Fraud triangle",
"abbr": "",
"def": "A model explaining why people commit fraud: pressure (a motive), opportunity (weak controls) and rationalisation (self-justification). Controls act mainly on opportunity."
},
{
"slug": "governance",
"term": "Governance",
"abbr": "",
"def": "The system by which an organisation is directed, controlled and held to account: who decides what, how decisions are made and checked, and how those in charge answer for results."
},
{
"slug": "grc",
"term": "Governance, risk and compliance (GRC)",
"abbr": "GRC",
"def": "The integrated set of frameworks, people, processes, data and technology an organisation uses to set direction, manage risk and meet its obligations, so that all three share one set of objectives, risks, obligations, controls and evidence."
},
{
"slug": "greenwashing",
"term": "Greenwashing",
"abbr": "",
"def": "Making a product or organisation look more environmentally friendly, sustainable or ethical than it really is. Misleading sustainability claims can breach the prohibitions on misleading conduct, and ASIC has taken several greenwashing cases to court."
},
{
"slug": "hawking",
"term": "Hawking",
"abbr": "",
"def": "Offering financial products to retail clients during an unsolicited contact, such as a cold call. It has been prohibited in most cases since October 2021."
},
{
"slug": "heat-map",
"term": "Heat map",
"abbr": "",
"def": "A colour-coded chart that plots risks by likelihood and consequence so the most serious ones stand out (usually red). A visual form of risk matrix."
},
{
"slug": "heavy-tailed-distribution",
"term": "Heavy-tailed distribution",
"abbr": "",
"def": "A pattern of losses in which extreme events are far more likely than a normal (bell-curve) distribution would suggest. Most losses are small, but a few very large ones dominate the total. Operational and cyber losses are typically heavy-tailed."
},
{
"slug": "high-reliability-organisation",
"term": "High-reliability organisation (HRO)",
"abbr": "HRO",
"def": "An organisation that operates in hazardous conditions for long periods with very few serious failures, for example through preoccupation with failure, deference to expertise and strong learning."
},
{
"slug": "incident",
"term": "Incident",
"abbr": "",
"def": "An event that has caused, or could have caused, loss, harm or disruption, for example a system outage, processing error, fraud or data breach. Not every incident is a breach of an obligation, and not every breach starts as an obvious incident."
},
{
"slug": "independent-director",
"term": "Independent director",
"abbr": "",
"def": "A non-executive director who is free of business or other relationships that could materially interfere with the exercise of their independent judgement."
},
{
"slug": "information-asset",
"term": "Information asset",
"abbr": "",
"def": "Information, and the technology that stores or processes it, that has value to the organisation, such as customer data, systems and applications. Under CPS 234, entities must classify information assets by how critical and sensitive they are and protect them accordingly."
},
{
"slug": "isms",
"term": "Information security management system",
"abbr": "ISMS",
"def": "The set of policies, processes, roles and controls an organisation uses to manage information security risk in a structured, continually improving way. ISO/IEC 27001 is the international standard for building and certifying one."
},
{
"slug": "inherent-risk",
"term": "Inherent risk",
"abbr": "",
"def": "The level of a risk before taking account of controls (or assuming the controls fail). Different organisations define it slightly differently, so check the definition in use."
},
{
"slug": "internal-audit",
"term": "Internal audit",
"abbr": "",
"def": "An independent function, reporting to the board or audit committee, that gives objective assurance and advice on whether governance, risk management and controls are working. The third line in the Three Lines model."
},
{
"slug": "icaap",
"term": "Internal capital adequacy assessment process",
"abbr": "ICAAP",
"def": "The process a bank or insurer uses to assess how much capital it needs for its risks, now and in stress, and how it will maintain it. APRA's capital standards require it to include stress testing."
},
{
"slug": "internal-control",
"term": "Internal control",
"abbr": "",
"def": "The processes an organisation puts in place to give reasonable confidence that it will achieve its objectives for operations, reporting and compliance."
},
{
"slug": "idr",
"term": "Internal dispute resolution",
"abbr": "IDR",
"def": "A financial firm's own complaints handling process. ASIC's Regulatory Guide 271 sets standards and maximum response times."
},
{
"slug": "iso-31000",
"term": "ISO 31000",
"abbr": "",
"def": "The international guideline on risk management, published by the International Organization for Standardization. The current edition is ISO 31000:2018. It sets out principles, a framework and a process. It is guidance, so organisations cannot be certified against it."
},
{
"slug": "issue",
"term": "Issue (control weakness)",
"abbr": "",
"def": "A weakness in controls, processes or systems that needs fixing, whether or not harm has happened yet. Issues are rated, owned and tracked through actions until fixed and validated."
},
{
"slug": "key-control",
"term": "Key control",
"abbr": "",
"def": "A control that, on its own or with a few others, is essential to managing a significant risk. Key controls usually get the most testing attention."
},
{
"slug": "key-function",
"term": "Key function (FAR)",
"abbr": "",
"def": "Under the Financial Accountability Regime, a business function listed in the rules (such as risk management or compliance) for which someone must hold accountable-person responsibility. The regulators have proposed removing the key functions requirements as part of simplifying FAR."
},
{
"slug": "kri",
"term": "Key risk indicator",
"abbr": "KRI",
"def": "A measure that gives early warning that a risk is rising, for example staff turnover in a critical team, system downtime or the number of overdue complaints. KRIs usually have thresholds that trigger escalation."
},
{
"slug": "likelihood",
"term": "Likelihood",
"abbr": "",
"def": "How probable it is that an event will happen within a set time period. It can be described in words (\"rare\", \"likely\"), as a frequency or as a probability."
},
{
"slug": "lcr",
"term": "Liquidity Coverage Ratio",
"abbr": "LCR",
"def": "A bank liquidity measure: high-quality liquid assets divided by the net cash outflows expected over a 30-day severe stress. Larger ADIs must keep it at or above 100%, so they could survive a month of stress without outside help."
},
{
"slug": "liquidity-risk",
"term": "Liquidity risk",
"abbr": "",
"def": "The risk that an organisation cannot pay its obligations when they fall due, or can only do so at excessive cost, because it cannot get cash quickly enough."
},
{
"slug": "macroprudential-policy",
"term": "Macroprudential policy",
"abbr": "",
"def": "Rules aimed at the stability of the financial system as a whole rather than individual institutions, for example limits on risky types of home lending across all banks. In Australia APRA sets these, working with the other Council of Financial Regulators agencies."
},
{
"slug": "malus",
"term": "Malus",
"abbr": "",
"def": "Reducing or cancelling variable remuneration that has been awarded but not yet paid or vested, for example because of poor risk or conduct outcomes. Compare clawback."
},
{
"slug": "managed-investment-scheme",
"term": "Managed investment scheme",
"abbr": "MIS",
"def": "An arrangement where people pool money to be invested or used for a common purpose, with the scheme run by someone else rather than the investors themselves. Managed funds and many property and credit funds are examples. Schemes offered to retail investors generally must be registered with ASIC."
},
{
"slug": "market-risk",
"term": "Market risk",
"abbr": "",
"def": "The risk of loss from movements in market prices such as interest rates, exchange rates, share prices and commodity prices."
},
{
"slug": "material-personal-interest",
"term": "Material personal interest",
"abbr": "",
"def": "A director's own interest in a matter being considered by the board that is significant enough to require disclosure under the Corporations Act, and in public companies generally prevents them voting on it."
},
{
"slug": "material-risk",
"term": "Material risk",
"abbr": "",
"def": "A risk that could have a material impact on an organisation, its customers or members. CPS 220 requires an APRA-regulated entity's risk management framework to cover all material risks, which usually become the top level of its risk taxonomy."
},
{
"slug": "material-service-provider",
"term": "Material service provider",
"abbr": "",
"def": "Under APRA's CPS 230, a service provider that an entity relies on to carry out a critical operation, or that exposes it to material operational risk. These arrangements attract extra requirements such as formal agreements and notifying APRA."
},
{
"slug": "materiality",
"term": "Materiality",
"abbr": "",
"def": "Whether something is significant enough to matter to a decision, a report or a regulator. Many reporting obligations only apply to \"material\" or \"significant\" matters, which requires judgement."
},
{
"slug": "member-outcomes-assessment",
"term": "Member outcomes assessment",
"abbr": "",
"def": "The annual assessment super trustees must make under the SIS Act of whether they are promoting members' financial interests, covering matters such as fees, returns, investment risk and insurance. It must be published on the fund's website."
},
{
"slug": "model-risk",
"term": "Model risk",
"abbr": "",
"def": "The risk of loss or harm from decisions based on models, including statistical, actuarial and AI models, that are wrong or used inappropriately."
},
{
"slug": "mysuper",
"term": "MySuper",
"abbr": "",
"def": "A simple, low-cost default super product with restrictions on fees and features. Members who don't choose a fund or investment option are generally placed in a MySuper product."
},
{
"slug": "near-miss",
"term": "Near miss",
"abbr": "",
"def": "An event that could have caused loss or harm but didn't, often through luck or a last-minute catch. Near misses are valuable warning signs and are usually recorded like incidents."
},
{
"slug": "non-executive-director",
"term": "Non-executive director",
"abbr": "NED",
"def": "A board member who is not part of the organisation's management. Non-executive directors provide oversight and challenge."
},
{
"slug": "normal-accident-theory",
"term": "Normal accident theory",
"abbr": "",
"def": "The theory, associated with Charles Perrow, that serious accidents are to be expected in systems that are both interactively complex and tightly coupled, however good their safety measures."
},
{
"slug": "ndb",
"term": "Notifiable data breach",
"abbr": "NDB",
"def": "Under the Privacy Act 1988 (Cth), a data breach involving personal information that is likely to result in serious harm to an individual. The organisation must notify affected individuals and the OAIC."
},
{
"slug": "obligations-register",
"term": "Obligations register",
"abbr": "",
"def": "A list of the compliance obligations that apply to an organisation, usually mapped to the owners, processes and controls that make sure each one is met."
},
{
"slug": "oaic",
"term": "Office of the Australian Information Commissioner",
"abbr": "OAIC",
"def": "The regulator for privacy and freedom of information. It oversees the Privacy Act 1988 (Cth) and the Notifiable Data Breaches scheme."
},
{
"slug": "operational-resilience",
"term": "Operational resilience",
"abbr": "",
"def": "The ability to keep delivering critical services through a disruption, and to recover quickly, rather than only trying to prevent disruption in the first place."
},
{
"slug": "operational-risk",
"term": "Operational risk",
"abbr": "",
"def": "The risk of loss or harm from inadequate or failed internal processes, people or systems, or from external events. It includes things like fraud, errors, IT failures, legal and compliance failures, and supplier problems."
},
{
"slug": "outsourcing",
"term": "Outsourcing",
"abbr": "",
"def": "Using another company to perform an activity the organisation would otherwise do itself. The organisation stays responsible for the outcome even though someone else does the work."
},
{
"slug": "performance-test",
"term": "Performance test (super)",
"abbr": "",
"def": "APRA's annual test of MySuper and trustee-directed super products against benchmarks. Trustees of failing products must tell members, and a product that fails two years in a row can't take new members."
},
{
"slug": "physical-risk",
"term": "Physical risk (climate)",
"abbr": "",
"def": "Financial risk from the physical effects of climate change, such as floods, bushfires, heatwaves and rising sea levels, which can damage assets and disrupt operations."
},
{
"slug": "policy",
"term": "Policy",
"abbr": "",
"def": "A formal statement of the principles and rules an organisation has decided to follow on a topic. Procedures then set out the step-by-step way to carry the policy out."
},
{
"slug": "preventive-control",
"term": "Preventive control",
"abbr": "",
"def": "A control that stops a problem happening in the first place, such as an approval, a system restriction or segregation of duties. Compare detective control."
},
{
"slug": "pds",
"term": "Product Disclosure Statement",
"abbr": "PDS",
"def": "A document that must generally be given to a retail client before they acquire a financial product, explaining its features, benefits, risks, fees and costs."
},
{
"slug": "product-intervention-power",
"term": "Product intervention power",
"abbr": "",
"def": "ASIC's power to temporarily ban or restrict a financial or credit product, or how it is sold, where it has caused or is likely to cause significant consumer detriment. It has been used, for example, on short-term credit and some high-risk investment products."
},
{
"slug": "prudential-standard",
"term": "Prudential standard",
"abbr": "",
"def": "A legally binding rule made by APRA that regulated entities must follow, for example CPS 220 Risk Management or CPS 230 Operational Risk Management. APRA also issues non-binding prudential practice guides (such as CPG 230) that explain its expectations."
},
{
"slug": "psychological-safety",
"term": "Psychological safety",
"abbr": "",
"def": "A shared belief within a team that it is safe to speak up, ask questions, admit mistakes and challenge others without fear of punishment or embarrassment."
},
{
"slug": "recovery-and-exit-planning",
"term": "Recovery and exit planning",
"abbr": "",
"def": "Planning in advance how an entity could recover from severe financial stress, or leave the market in an orderly way if it can't. APRA's CPS 190 requires this of significant financial institutions."
},
{
"slug": "rpo",
"term": "Recovery point objective",
"abbr": "RPO",
"def": "The maximum amount of data (measured in time) you can afford to lose. An RPO of one hour means backups must be no more than an hour old."
},
{
"slug": "rto",
"term": "Recovery time objective",
"abbr": "RTO",
"def": "The target maximum time to restore a process or system after a disruption."
},
{
"slug": "regulatory-capture",
"term": "Regulatory capture",
"abbr": "",
"def": "When a regulator comes to act in the interests of the industry it regulates rather than the public, for example through close relationships, shared views or the movement of staff between them."
},
{
"slug": "regulatory-change",
"term": "Regulatory change management",
"abbr": "",
"def": "The process for spotting new or changed obligations, assessing their impact, implementing the changes and confirming they were made."
},
{
"slug": "remediation",
"term": "Remediation",
"abbr": "",
"def": "Fixing a problem and its effects: correcting the cause so it doesn't happen again, and putting affected customers or members back in the position they should have been in (for example through refunds with interest)."
},
{
"slug": "reportable-situation",
"term": "Reportable situation",
"abbr": "",
"def": "Under the Corporations Act and the National Consumer Credit Protection Act, a category of breaches and other matters that financial services and credit licensees must report to ASIC. Most must be reported within 30 calendar days."
},
{
"slug": "reporting-entity",
"term": "Reporting entity",
"abbr": "",
"def": "A business that provides a designated service under the AML/CTF Act and so must enrol with AUSTRAC, maintain an AML/CTF program and report to AUSTRAC."
},
{
"slug": "residual-risk",
"term": "Residual risk",
"abbr": "",
"def": "The level of risk that remains after taking account of the controls in place. It is compared with risk appetite to decide whether more action is needed."
},
{
"slug": "responsible-entity",
"term": "Responsible entity",
"abbr": "RE",
"def": "The public company, holding an AFS licence, that operates a registered managed investment scheme and owes legal duties to its members, including acting in their best interests. It stays responsible for the scheme even when it outsources tasks such as custody or investment management."
},
{
"slug": "responsible-manager",
"term": "Responsible manager",
"abbr": "",
"def": "A person nominated by an AFS licensee who is directly responsible for significant day-to-day decisions about its financial services, and whose knowledge and skills demonstrate the licensee's organisational competence."
},
{
"slug": "responsive-regulation",
"term": "Responsive regulation",
"abbr": "",
"def": "An approach in which regulators start with persuasion and cooperation and escalate to tougher sanctions only when a firm does not respond, often pictured as an enforcement pyramid."
},
{
"slug": "reverse-stress-testing",
"term": "Reverse stress testing",
"abbr": "",
"def": "Starting from an outcome the organisation could not accept, such as breaching minimum capital or running out of liquid assets, and working backwards to identify the scenarios that would cause it."
},
{
"slug": "review-trigger",
"term": "Review trigger",
"abbr": "",
"def": "An event or piece of information, set out in a target market determination, that means the issuer must review whether the TMD is still appropriate, such as a spike in complaints or significant dealings outside the target market."
},
{
"slug": "risk",
"term": "Risk",
"abbr": "",
"def": "Uncertainty about what will happen and how it will affect what you are trying to achieve. ISO 31000 describes risk as the effect of uncertainty on objectives, which can be negative or positive. In everyday use, \"a risk\" usually means something that could go wrong."
},
{
"slug": "risk-acceptance",
"term": "Risk acceptance",
"abbr": "",
"def": "A deliberate, documented decision by someone with the right authority to live with a risk rather than reduce it further, usually for a set period."
},
{
"slug": "rcsa",
"term": "Risk and control self-assessment",
"abbr": "RCSA",
"def": "A process where the business (first line) regularly assesses its own risks and how well its controls are working, usually with support and challenge from the risk function."
},
{
"slug": "risk-appetite",
"term": "Risk appetite",
"abbr": "",
"def": "The amount and types of risk an organisation is willing to take on to achieve its objectives. It is set by the board and guides everyday decisions."
},
{
"slug": "risk-appetite-statement",
"term": "Risk appetite statement",
"abbr": "RAS",
"def": "The written, board-approved document that sets out risk appetite, usually with qualitative statements and measurable limits for each major risk category. APRA-regulated entities must have one."
},
{
"slug": "risk-assessment",
"term": "Risk assessment",
"abbr": "",
"def": "The overall process of identifying risks, analysing how likely and severe they are, and evaluating which need action."
},
{
"slug": "risk-capacity",
"term": "Risk capacity",
"abbr": "",
"def": "The maximum amount of risk an organisation could absorb before it failed, breached its regulatory minimums or could no longer meet its obligations. Risk appetite should sit well inside risk capacity."
},
{
"slug": "risk-culture",
"term": "Risk culture",
"abbr": "",
"def": "The shared values, beliefs and behaviours that shape how people in an organisation think about and handle risk, for example whether people speak up about problems and whether bad news travels upward."
},
{
"slug": "risk-management",
"term": "Risk management",
"abbr": "",
"def": "Coordinated activities to direct and control an organisation with regard to risk: identifying what could affect objectives, deciding what to do about it, and monitoring the results."
},
{
"slug": "risk-management-framework",
"term": "Risk management framework",
"abbr": "RMF",
"def": "The full set of structures, policies, processes, people and systems an organisation uses to manage risk. Under APRA's CPS 220 it includes the risk appetite statement and risk management strategy."
},
{
"slug": "risk-matrix",
"term": "Risk matrix",
"abbr": "",
"def": "A grid with likelihood on one axis and consequence on the other, used to give each risk a rating such as low, medium, high or extreme."
},
{
"slug": "risk-owner",
"term": "Risk owner",
"abbr": "",
"def": "The person accountable for managing a particular risk, including making sure controls and actions are in place."
},
{
"slug": "risk-profile",
"term": "Risk profile",
"abbr": "",
"def": "A description of all the risks an organisation (or part of it) currently faces and their levels, at a point in time."
},
{
"slug": "risk-register",
"term": "Risk register",
"abbr": "",
"def": "A record of identified risks, with their causes, consequences, ratings, controls, owners and any actions."
},
{
"slug": "risk-taxonomy",
"term": "Risk taxonomy",
"abbr": "",
"def": "A structured, hierarchical classification of the types of risk an organisation faces (for example Level 1 categories, Level 2 sub-types and Level 3 specific risks), used consistently across the organisation so risks can be linked, compared and rolled up."
},
{
"slug": "risk-tolerance",
"term": "Risk tolerance",
"abbr": "",
"def": "The acceptable amount of variation around risk appetite, usually expressed as measurable limits or thresholds that trigger escalation when crossed. The terms are used differently by different frameworks."
},
{
"slug": "risk-treatment",
"term": "Risk treatment",
"abbr": "",
"def": "What you decide to do about a risk: avoid it, reduce it (with controls), share or transfer it (for example with insurance), or accept it. Taking on more risk to pursue an opportunity is also a treatment option."
},
{
"slug": "root-cause-analysis",
"term": "Root cause analysis",
"abbr": "",
"def": "Working out the underlying reason something went wrong, not just the immediate trigger, so the fix stops it from happening again. The \"5 whys\" and fishbone diagrams are common techniques."
},
{
"slug": "rse-licensee",
"term": "RSE licensee",
"abbr": "",
"def": "A registrable superannuation entity licensee: the trustee company licensed by APRA to operate one or more APRA-regulated super funds."
},
{
"slug": "run-rule",
"term": "Run rule",
"abbr": "",
"def": "A statistical process control test that flags a sustained shift, such as a number of consecutive values above the average, even when no single value crosses a threshold. Useful for spotting gradual drift in key risk indicators."
},
{
"slug": "sampling",
"term": "Sampling (control testing)",
"abbr": "",
"def": "Testing a selection of items from a population (for example 25 transactions out of thousands) to draw a conclusion about whether a control operated effectively across the whole period. Sample size usually depends on how often the control runs and how much assurance is needed."
},
{
"slug": "scams-prevention-framework",
"term": "Scams Prevention Framework",
"abbr": "SPF",
"def": "A law passed in 2025 that places obligations on businesses in designated sectors (starting with banks, telcos and digital platforms) to prevent, detect, report, disrupt and respond to scams, with external dispute resolution for consumers. Obligations apply as sectors are designated and codes are made."
},
{
"slug": "scenario-analysis",
"term": "Scenario analysis",
"abbr": "",
"def": "Exploring \"what if\" situations, usually severe but plausible, to understand how an organisation would be affected and whether it could cope."
},
{
"slug": "second-line",
"term": "Second line",
"abbr": "",
"def": "In the Three Lines model, specialist functions such as risk management and compliance that set frameworks, give expert advice, and monitor and challenge how the first line manages risk."
},
{
"slug": "segregation-of-duties",
"term": "Segregation of duties",
"abbr": "",
"def": "Splitting key steps of a task between different people so no single person can both make and hide an error or fraud, for example one person sets up a payment and another approves it."
},
{
"slug": "smsf",
"term": "Self-managed super fund",
"abbr": "SMSF",
"def": "A small super fund, with up to six members, where the members are also the trustees (or directors of the corporate trustee). SMSFs are regulated by the ATO rather than APRA."
},
{
"slug": "significant-dealing",
"term": "Significant dealing",
"abbr": "",
"def": "Under the design and distribution obligations, a dealing in a product that is not consistent with its target market determination and is significant (for example because of the number of customers or the harm involved). Issuers must notify ASIC within 10 business days of becoming aware."
},
{
"slug": "sfi",
"term": "Significant financial institution",
"abbr": "SFI",
"def": "APRA's label for larger regulated entities that must meet the full set of certain prudential requirements, including parts of CPS 230, CPS 511 and CPS 190. For example, an ADI with total assets over $20 billion, or an RSE licensee whose funds hold over $30 billion in total assets. APRA can also designate an entity as an SFI because of its complexity or group membership."
},
{
"slug": "social-amplification-of-risk",
"term": "Social amplification of risk",
"abbr": "",
"def": "A framework explaining how media, institutions and social groups can make a risk seem larger or smaller than technical estimates suggest, with ripple effects such as loss of trust and regulatory change."
},
{
"slug": "sps-515",
"term": "SPS 515 Strategic Planning and Member Outcomes",
"abbr": "",
"def": "APRA's prudential standard requiring super trustees to have a business plan and to assess each year whether they are delivering good outcomes for members, including by comparing fees, returns and services with other products."
},
{
"slug": "soa",
"term": "Statement of Advice",
"abbr": "SOA",
"def": "The document an adviser must generally give a retail client when providing personal advice, setting out the advice, the basis for it, and fees and conflicts."
},
{
"slug": "stewardship-theory",
"term": "Stewardship theory",
"abbr": "",
"def": "A theory of governance that sees managers as stewards who are motivated to act in the organisation's interests, so trust and empowerment may work better than tight control. Often contrasted with agency theory."
},
{
"slug": "strategic-risk",
"term": "Strategic risk",
"abbr": "",
"def": "The risk that an organisation's strategy is wrong, poorly executed or overtaken by changes in its environment."
},
{
"slug": "stress-testing",
"term": "Stress testing",
"abbr": "",
"def": "Testing how an organisation's finances or operations would hold up under extreme but plausible conditions, such as a sharp rise in unemployment or a market crash."
},
{
"slug": "substitutability",
"term": "Substitutability",
"abbr": "",
"def": "How easily a service provider could be replaced by another provider or by bringing the service in-house. Low substitutability calls for a more detailed, tested exit plan."
},
{
"slug": "successor-fund-transfer",
"term": "Successor fund transfer (SFT)",
"abbr": "SFT",
"def": "A transfer of super members' benefits from one fund to another without each member's consent, permitted where the successor fund confers equivalent rights in respect of their benefits. The usual mechanism for super fund mergers."
},
{
"slug": "smr",
"term": "Suspicious matter report",
"abbr": "SMR",
"def": "A report a reporting entity must give AUSTRAC when it forms a suspicion about a customer or transaction on certain grounds, such as possible money laundering. Due within 3 business days (24 hours for terrorism financing)."
},
{
"slug": "tmd",
"term": "Target market determination",
"abbr": "TMD",
"def": "A public document an issuer must make under the design and distribution obligations, describing the consumers a product is designed for and any conditions on how it can be distributed."
},
{
"slug": "third-line",
"term": "Third line",
"abbr": "",
"def": "In the Three Lines model, internal audit: the independent function that gives assurance and advice to the board on how well the first and second lines are working."
},
{
"slug": "third-party-risk",
"term": "Third-party risk",
"abbr": "",
"def": "The risk that comes from relying on other organisations, such as suppliers, outsourcers, administrators and technology providers, to deliver part of your service."
},
{
"slug": "three-lines-model",
"term": "Three Lines model",
"abbr": "",
"def": "A model published by the Institute of Internal Auditors describing how the governing body, management (first and second line roles) and internal audit (third line) work together on governance and risk. Updated in 2020 from the earlier \"three lines of defence\"."
},
{
"slug": "tolerable-deviation-rate",
"term": "Tolerable deviation rate",
"abbr": "",
"def": "In control testing, the highest rate at which a control can fail while still being relied on. Together with the confidence level, it sets the sample size."
},
{
"slug": "tolerance-level",
"term": "Tolerance level (CPS 230)",
"abbr": "",
"def": "Under APRA's CPS 230, the board-approved maximum level of disruption to a critical operation the entity is prepared to accept, including the maximum period of disruption, data loss and minimum service levels."
},
{
"slug": "tone-at-the-top",
"term": "Tone at the top",
"abbr": "",
"def": "The example set by the board and senior leaders through what they say, reward and tolerate. It strongly shapes culture and whether controls are respected."
},
{
"slug": "transition-risk",
"term": "Transition risk (climate)",
"abbr": "",
"def": "Financial risk from the move to a low-carbon economy, such as new policy, technology or changing preferences that reduce the value of emissions-heavy assets."
},
{
"slug": "twin-peaks",
"term": "Twin peaks",
"abbr": "",
"def": "The name for Australia's financial regulation model, which splits responsibilities between two main regulators: APRA for prudential soundness and ASIC for conduct and disclosure."
},
{
"slug": "uct",
"term": "Unfair contract term",
"abbr": "",
"def": "A term in a standard form consumer or small business contract that causes a significant imbalance, isn't reasonably necessary to protect the business, and would cause detriment. Since 9 November 2023, using such terms can attract penalties."
},
{
"slug": "unit-price",
"term": "Unit price",
"abbr": "",
"def": "The value of one unit in an investment option: net assets (after fees and tax provisions) divided by units on issue. Members' balances and transactions are calculated using unit prices, so pricing errors move value between members."
},
{
"slug": "utmost-good-faith",
"term": "Utmost good faith",
"abbr": "",
"def": "A duty on both insurers and policyholders to act honestly and fairly with each other, implied into every insurance contract by the Insurance Contracts Act 1984 (Cth). An insurer that breaches it, for example by unreasonably handling a claim, can face ASIC action."
},
{
"slug": "var",
"term": "Value-at-risk",
"abbr": "VaR",
"def": "The loss that is expected to be exceeded only with a small, stated probability over a period. For example, a one-year 99% VaR of $10 million means losses are expected to be worse than $10 million in only about 1 year in 100. It says nothing about how bad those worst years are."
},
{
"slug": "variable-remuneration",
"term": "Variable remuneration",
"abbr": "",
"def": "Pay that depends on performance or other conditions, such as bonuses and long-term incentives, as opposed to fixed salary."
},
{
"slug": "vulnerable-customer",
"term": "Vulnerable customer",
"abbr": "",
"def": "A customer who, because of personal circumstances such as illness, disability, family violence, age, language or financial stress, is at greater risk of harm. Regulators and industry codes expect firms to identify vulnerability and adjust how they deal with these customers."
},
{
"slug": "whistleblower",
"term": "Whistleblower",
"abbr": "",
"def": "A person who reports suspected wrongdoing inside an organisation. Australian law gives eligible whistleblowers legal protections, for example under Part 9.4AAA of the Corporations Act 2001 (Cth)."
}
];
