// Question bank for /learn/quizzes.html (rendered by quiz-runner.js).
// Each question: q (text), options (array), answer (index of the right option),
// explain (why), page (root-relative link to the page that covers it).
// Options are shuffled when shown; set fixed: true to keep their order (e.g. "All of the above").
// Keep questions consistent with the linked page; update both together.
window.QUIZ_BANK = [
  {
    id: "foundations",
    title: "Foundations",
    questions: [
      { q: "What is a risk always tied to?", options: ["A dollar amount", "An objective", "A regulator", "A control"], answer: 1,
        explain: "A risk is uncertainty that could affect what you're trying to achieve, so it only makes sense relative to an objective.", page: "/foundations/what-is-risk-management.html" },
      { q: "Which of these is NOT one of the standard ways to respond to a threat?", options: ["Avoid it", "Share it", "Ignore it without a decision", "Accept it"], answer: 2,
        explain: "Accepting a risk is a deliberate, informed decision. Ignoring it without a decision is not a risk response.", page: "/foundations/what-is-risk-management.html" },
      { q: "Compliance risk is best described as:", options: ["The risk of failing to meet an obligation", "The cost of the compliance team", "The risk of a market fall", "The risk that a regulator changes"], answer: 0,
        explain: "Compliance risk is the risk of failing to meet obligations. It is one type of risk within the wider risk management framework.", page: "/foundations/what-is-compliance.html" },
      { q: "Regulator guidance such as an ASIC Regulatory Guide is generally:", options: ["Legislation", "Not law, but a strong signal of what the regulator expects", "Irrelevant to compliance", "Only for listed companies"], answer: 1,
        explain: "Guidance is usually not law itself (unless made enforceable), but it shows how the regulator reads the law and what it will look for.", page: "/foundations/what-is-compliance.html" },
      { q: "In good governance, who runs the organisation day to day?", options: ["The board", "Management", "Internal audit", "The regulator"], answer: 1,
        explain: "The board sets direction and oversees. Management runs the organisation. Blurring the two is a common source of trouble.", page: "/foundations/what-is-governance.html" },
      { q: "In the Three Lines model, which line gives independent assurance to the board?", options: ["First line", "Second line", "Third line (internal audit)", "External auditor only"], answer: 2,
        explain: "Internal audit is the third line, independent of management, reporting to the board (usually through the audit committee).", page: "/foundations/three-lines-model.html" },
      { q: "A risk and compliance function that sets frameworks, monitors and challenges the business is usually described as:", options: ["First line", "Second line", "Third line", "Fourth line"], answer: 1,
        explain: "Second-line specialist functions set frameworks, advise, monitor and challenge. The business (first line) owns its risks.", page: "/foundations/three-lines-model.html" },
      { q: "Australia's \"twin peaks\" model means:", options: ["APRA for financial soundness, ASIC for conduct", "ASIC and the ACCC share all regulation", "Two separate super regulators", "The RBA and Treasury regulate banks"], answer: 0,
        explain: "APRA handles prudential (financial soundness) regulation and ASIC handles conduct and disclosure.", page: "/foundations/regulatory-landscape.html" },
      { q: "Which regulator is responsible for anti-money laundering and counter-terrorism financing?", options: ["ASIC", "APRA", "AUSTRAC", "OAIC"], answer: 2,
        explain: "AUSTRAC regulates reporting entities under the AML/CTF Act.", page: "/foundations/regulatory-landscape.html" },
      { q: "Which framework is short, general risk management guidance that is NOT certifiable?", options: ["ISO 31000", "ISO/IEC 27001", "CPS 230", "COSO Internal Control"], answer: 0,
        explain: "ISO 31000 is guidance. Unlike ISO/IEC 27001, organisations can't be certified against it.", page: "/foundations/core-frameworks-compared.html" },
      { q: "Do APRA's risk management standards require an organisation to use a specific external framework such as COSO or ISO 31000?", options: ["Yes, COSO ERM", "Yes, ISO 31000", "No, they set outcomes and don't mandate a framework", "Only for banks"], answer: 2,
        explain: "APRA sets requirements and outcomes. Entities can use any framework (or their own) that meets them.", page: "/foundations/core-frameworks-compared.html" }
    ]
  },
  {
    id: "risk",
    title: "Risk management",
    questions: [
      { q: "Which is the correct order, from largest to smallest?", options: ["Appetite, capacity, tolerance", "Capacity, appetite, tolerance and limits", "Tolerance, appetite, capacity", "Limits, capacity, appetite"], answer: 1,
        explain: "Capacity is the most risk you could bear. Appetite is how much you choose to take. Tolerances and limits are the measurable boundaries within that.", page: "/risk-management/risk-appetite-and-tolerance.html" },
      { q: "A risk appetite statement is most useful when:", options: ["It is approved and filed", "It cascades into limits, KRIs and decisions, and breaches lead to action", "It is only qualitative", "It is reviewed every five years"], answer: 1,
        explain: "Appetite only works if it shapes real decisions and limits, and breaches actually trigger a response.", page: "/risk-management/risk-appetite-and-tolerance.html" },
      { q: "Residual risk is the level of risk:", options: ["Before any controls", "After existing controls", "After planned future actions", "That the board will accept"], answer: 1,
        explain: "Inherent risk is before controls. Residual is after current controls. Target risk is after planned actions.", page: "/risk-management/risk-assessment-methodologies.html" },
      { q: "What is a well-documented weakness of heat maps?", options: ["They can't show likelihood", "Ratings can look more precise than the judgement behind them", "They are illegal under ISO 31000", "They only work for financial risks"], answer: 1,
        explain: "Heat maps are good for communication, but the ratings are structured judgement and can hide uncertainty and range effects.", page: "/risk-management/risk-assessment-methodologies.html" },
      { q: "Testing whether a control actually worked, consistently, over a period is testing its:", options: ["Design effectiveness", "Operating effectiveness", "Inherent risk", "Risk appetite"], answer: 1,
        explain: "Design effectiveness asks whether it would work if performed as designed. Operating effectiveness asks whether it did work over time.", page: "/risk-management/control-design-and-testing.html" },
      { q: "A monthly reconciliation that spots unmatched payments after they happen is mainly a:", options: ["Preventive control", "Detective control", "Directive control", "Risk appetite"], answer: 1,
        explain: "It finds problems after they occur, so it is detective. A preventive control stops the problem happening at all.", page: "/risk-management/control-design-and-testing.html" },
      { q: "What is the backbone that lets risks be compared and aggregated across an enterprise?", options: ["A shared risk taxonomy", "A single heat map colour", "The annual report", "A whistleblower policy"], answer: 0,
        explain: "A common taxonomy (list of risk categories) means risks from different areas can be compared and added up.", page: "/risk-management/enterprise-risk-management.html" },
      { q: "Which of these is a driver of operational risk?", options: ["People", "Processes", "Systems and external events", "All of the above"], answer: 3, fixed: true,
        explain: "Operational risk comes from people, processes, systems and external events.", page: "/risk-management/operational-risk.html" },
      { q: "Under CPS 230, how quickly must APRA be told about a disruption to a critical operation that goes outside tolerance?", options: ["24 hours", "72 hours", "10 business days", "30 days"], answer: 0,
        explain: "24 hours for disruptions to critical operations outside tolerance. 72 hours for material operational risk incidents.", page: "/risk-management/operational-risk.html" },
      { q: "Expected credit loss is often estimated as:", options: ["PD × LGD × EAD", "Capital ÷ risk-weighted assets", "Likelihood + consequence", "Assets − liabilities"], answer: 0,
        explain: "Probability of default × loss given default × exposure at default.", page: "/risk-management/credit-market-and-liquidity-risk.html" },
      { q: "Which risk can sink an otherwise solvent institution very quickly?", options: ["Liquidity risk", "Strategic risk", "Reputational risk only", "Model risk only"], answer: 0,
        explain: "If an institution can't meet cash outflows on time, it can fail even with positive net assets.", page: "/risk-management/credit-market-and-liquidity-risk.html" },
      { q: "When does the ASIC reportable situations clock generally start?", options: ["When the investigation is complete", "When the licensee first knows of, or is reckless about, reasonable grounds", "When a customer complains", "At the end of the financial year"], answer: 1,
        explain: "The 30-day clock runs from awareness (or recklessness) of reasonable grounds, not from certainty.", page: "/risk-management/incident-and-breach-management.html" },
      { q: "One event can be:", options: ["Only an incident or a breach, never both", "Both an incident and a breach, triggering several reporting regimes", "Reported to one regulator only", "Ignored if it was a near miss"], answer: 1,
        explain: "Incidents and breaches overlap, and a single event can trigger reports to several regulators.", page: "/risk-management/incident-and-breach-management.html" },
      { q: "A business impact analysis mainly works out:", options: ["Who to blame for an outage", "How quickly harm builds up and what each service depends on", "The cost of insurance", "The board's remuneration"], answer: 1,
        explain: "A BIA shows how harm grows over time and what each service depends on, which drives RTOs and RPOs.", page: "/risk-management/business-continuity.html" },
      { q: "Under CPS 230, how long do entities have to notify APRA after entering into or materially changing a material service provider arrangement?", options: ["24 hours", "72 hours", "20 business days", "90 days"], answer: 2,
        explain: "APRA must be notified within 20 business days.", page: "/risk-management/third-party-risk.html" },
      { q: "If a super fund outsources administration, who stays accountable to members and regulators?", options: ["The administrator", "The fund's trustee", "APRA", "Nobody"], answer: 1,
        explain: "Outsourcing a task doesn't outsource accountability.", page: "/risk-management/third-party-risk.html" }
    ]
  },
  {
    id: "compliance",
    title: "Compliance",
    questions: [
      { q: "What is the \"backbone\" of a compliance program?", options: ["The obligations register", "The annual report", "The website", "The incident log alone"], answer: 0,
        explain: "The obligations register maps every obligation to an owner, the processes it affects and the controls that meet it.", page: "/compliance/designing-a-compliance-program.html" },
      { q: "Which section of the Corporations Act sets AFS licensees' general obligations, such as acting efficiently, honestly and fairly?", options: ["s 180", "s 912A", "s 601FC", "s 1041H"], answer: 1,
        explain: "Section 912A sets the general obligations, including adequate compliance arrangements.", page: "/compliance/licensing-basics.html" },
      { q: "Who issues an Australian credit licence?", options: ["APRA", "ASIC", "AUSTRAC", "The RBA"], answer: 1,
        explain: "ASIC issues both AFS licences and Australian credit licences. APRA authorises banks, insurers and super trustees.", page: "/compliance/licensing-basics.html" },
      { q: "Before a retail client acquires most financial products, they must usually receive a:", options: ["Product Disclosure Statement", "Annual report", "Target market determination", "Compliance plan"], answer: 0,
        explain: "A PDS is generally required before acquisition. An FSG and, for personal advice, an SoA are the other key documents.", page: "/compliance/disclosure-obligations.html" },
      { q: "Does the rule against misleading or deceptive conduct apply to sustainability (\"green\") claims?", options: ["No, only to fees", "Yes, as ASIC's greenwashing cases show", "Only for listed companies", "Only in advertising on TV"], answer: 1,
        explain: "Everything an organisation says must not be misleading, including sustainability claims.", page: "/compliance/disclosure-obligations.html" },
      { q: "What is the general maximum IDR timeframe for complaints (outside super)?", options: ["5 business days", "30 calendar days", "45 calendar days", "90 calendar days"], answer: 1,
        explain: "Generally 30 calendar days. Most super complaints get 45 days.", page: "/compliance/consumer-protection.html" },
      { q: "Since 9 November 2023, unfair contract terms can:", options: ["Attract penalties", "Only be voided by AFCA", "Only apply to business customers", "Be approved by ASIC"], answer: 0,
        explain: "Unfair contract terms have attracted civil penalties since 9 November 2023.", page: "/compliance/consumer-protection.html" },
      { q: "The ASIC reportable situations deadline for significant breaches is:", options: ["72 hours", "10 business days", "30 calendar days", "90 days"], answer: 2,
        explain: "30 calendar days from first knowing of, or being reckless about, reasonable grounds.", page: "/compliance/breach-reporting.html" },
      { q: "Under the Notifiable Data Breaches scheme, which breaches must be notified to the OAIC and affected people?", options: ["All breaches", "Those likely to result in serious harm", "Only breaches over 1,000 records", "Only cyber attacks"], answer: 1,
        explain: "An eligible data breach is one likely to result in serious harm to the people affected.", page: "/compliance/privacy-law.html" },
      { q: "How many Australian Privacy Principles are there?", options: ["7", "10", "13", "20"], answer: 2,
        explain: "There are 13 APPs, covering the whole life cycle of personal information.", page: "/compliance/privacy-law.html" },
      { q: "Knowing your customer under AML/CTF law is called:", options: ["Customer due diligence", "Target market determination", "Fit and proper", "Material service provider review"], answer: 0,
        explain: "Customer due diligence (KYC) is a core AML/CTF obligation.", page: "/compliance/aml-ctf-fundamentals.html" },
      { q: "From 1 July 2026, the AML/CTF reforms (\"tranche 2\") brought in:", options: ["Only banks", "Lawyers, accountants, real estate professionals and others", "Only super funds", "No new sectors"], answer: 1,
        explain: "Tranche 2 extends the regime to lawyers, accountants, real estate professionals and others.", page: "/compliance/aml-ctf-fundamentals.html" }
    ]
  },
  {
    id: "governance",
    title: "Governance",
    questions: [
      { q: "Can a board delegate its accountability to management?", options: ["Yes, fully", "No. It can delegate authority, but it stays accountable", "Only to the CEO", "Only with APRA approval"], answer: 1,
        explain: "Boards delegate authority, not accountability. Clear delegations and good information are how they keep control.", page: "/governance/board-structure-and-accountability.html" },
      { q: "Directors' duties of care and diligence, good faith and not misusing position are in which part of the Corporations Act?", options: ["ss 180–184", "s 912A", "Part 9.4AAA", "Chapter 5C"], answer: 0,
        explain: "Sections 180–184 set out directors' core duties.", page: "/governance/board-structure-and-accountability.html" },
      { q: "When is the FAR's minimum deferral met for an accountable person's variable pay?", options: ["10% for one year", "At least 40% for at least four years", "100% for ten years", "There is no deferral"], answer: 1,
        explain: "FAR requires at least 40% of variable remuneration to be deferred for at least four years (subject to exceptions).", page: "/governance/financial-accountability-regime.html" },
      { q: "When did FAR start for super trustees and insurers?", options: ["15 March 2024", "15 March 2025", "1 July 2025", "It doesn't apply to them"], answer: 1,
        explain: "Banks from 15 March 2024. Insurers and super trustees from 15 March 2025.", page: "/governance/financial-accountability-regime.html" },
      { q: "Which is often NOT enough on its own to manage a serious conflict of interest?", options: ["Avoiding it", "Controlling it", "Disclosing it", "Declining the transaction"], answer: 2,
        explain: "Disclosure alone often doesn't fix the underlying conflict. Avoidance or controls may be needed.", page: "/governance/conflicts-of-interest.html" },
      { q: "Where a super trustee faces a conflict, whose interests must it prioritise?", options: ["The trustee's shareholders", "Members", "The fund's promoters", "The administrator"], answer: 1,
        explain: "The SIS Act requires trustees to give priority to members' interests.", page: "/governance/conflicts-of-interest.html" },
      { q: "Under CPS 511, the CEO of a significant financial institution must have at least 60% of variable pay deferred over:", options: ["Two years", "Four years", "Six years", "Ten years"], answer: 2,
        explain: "CPS 511 sets minimum deferral of 60% over six years for the CEO of an SFI.", page: "/governance/remuneration-governance.html" },
      { q: "Which kind of report is generally NOT protected under the Corporations Act whistleblower regime?", options: ["Suspected fraud", "A purely personal work-related grievance", "Misconduct about the company's financial services", "An anonymous disclosure of an improper state of affairs"], answer: 1,
        explain: "Personal work-related grievances are generally excluded unless they also involve wider matters.", page: "/governance/whistleblower-protections.html" },
      { q: "Can a whistleblower disclosure be made anonymously and still be protected?", options: ["Yes", "No", "Only to ASIC", "Only if the person later reveals their identity"], answer: 0,
        explain: "Disclosures can be anonymous and still qualify for protection.", page: "/governance/whistleblower-protections.html" },
      { q: "Conduct risk is the risk that:", options: ["Market prices move", "Behaviour causes poor customer outcomes or harms markets", "A server fails", "A borrower defaults"], answer: 1,
        explain: "Conduct risk is about behaviour, of the organisation or its people, that causes poor outcomes.", page: "/governance/culture-and-conduct.html" },
      { q: "Which inquiry identified culture as a root cause of misconduct at a major bank in 2018?", options: ["APRA's CBA Prudential Inquiry", "The Wallis Inquiry", "The Murray Inquiry", "The HIH Royal Commission"], answer: 0,
        explain: "APRA's 2018 Prudential Inquiry into CBA focused heavily on culture, governance and accountability.", page: "/governance/culture-and-conduct.html" }
    ]
  },
  {
    id: "standards",
    title: "Standards and regulatory guides",
    questions: [
      { q: "When did CPS 230 come into force?", options: ["1 January 2024", "1 July 2025", "15 March 2025", "1 July 2026"], answer: 1,
        explain: "CPS 230 has applied since 1 July 2025.", page: "/standards/cps-230.html" },
      { q: "Above what size is an RSE licensee a \"significant financial institution\" for CPS 230?", options: ["$3 billion", "$10 billion", "$20 billion", "$30 billion"], answer: 3,
        explain: "$30 billion for RSE licensees. ADIs are $20 billion, general and life insurers $10 billion, and private health insurers $3 billion.", page: "/standards/cps-230.html" },
      { q: "CPS 220 requires APRA-regulated entities to have a:", options: ["Risk appetite statement and risk management strategy", "Compliance plan audit", "Target market determination", "Financial Services Guide"], answer: 0,
        explain: "CPS 220 requires a risk management framework including a risk appetite statement and a risk management strategy.", page: "/standards/cps-220.html" },
      { q: "Under CPS 234, a material information security incident must be notified to APRA:", options: ["As soon as possible and no later than 72 hours", "Within 10 business days", "Within 30 days", "Annually"], answer: 0,
        explain: "72 hours for material incidents. Material control weaknesses that can't be fixed in time are 10 business days.", page: "/standards/cps-234.html" },
      { q: "Under ASIC relief, how long can an investigation into a possible significant breach run before it becomes reportable?", options: ["30 days", "60 days", "90 days", "There is no limit"], answer: 1,
        explain: "The Act says 30 days, but ASIC relief extended this to 60 days from 27 June 2025.", page: "/standards/asic-rg-78.html" },
      { q: "Most super complaints must be resolved or answered at IDR within:", options: ["21 days", "30 days", "45 days", "90 days"], answer: 2,
        explain: "45 calendar days for most super complaints (30 for most others).", page: "/standards/asic-rg-271.html" },
      { q: "Under the DDO, significant dealings inconsistent with the TMD must be notified to ASIC within:", options: ["72 hours", "10 business days", "30 days", "No notification needed"], answer: 1,
        explain: "Issuers must notify ASIC within 10 business days of becoming aware.", page: "/standards/asic-rg-274.html" },
      { q: "Which product is excluded from the design and distribution obligations?", options: ["Choice super products", "MySuper products", "Credit cards", "Managed funds"], answer: 1,
        explain: "MySuper products are excluded. Choice products are covered.", page: "/standards/asic-rg-274.html" },
      { q: "RG 277 says that where data is missing in a remediation, a licensee should use:", options: ["Assumptions that favour the licensee", "Beneficial assumptions that favour consumers", "No assumptions and exclude those consumers", "The regulator's data"], answer: 1,
        explain: "Beneficial assumptions stop people falling out of scope or being underpaid.", page: "/standards/asic-rg-277.html" },
      { q: "ISO/IEC 27001:2022 Annex A has how many reference controls?", options: ["14", "93", "114", "133"], answer: 1,
        explain: "93 controls in four themes: organisational, people, physical and technological. The 2013 edition had 114.", page: "/standards/iso-27001.html" },
      { q: "The ISO/IEC 27001 document that lists each Annex A control and whether it applies is the:", options: ["Risk register", "Statement of Applicability", "Compliance plan", "Business impact analysis"], answer: 1,
        explain: "The Statement of Applicability links risk treatment to controls and records inclusions and exclusions.", page: "/standards/iso-27001.html" },
      { q: "How many components and principles does COSO ERM (2017) have?", options: ["5 components, 17 principles", "5 components, 20 principles", "8 components, 20 principles", "3 components, 11 principles"], answer: 1,
        explain: "COSO ERM has 5 components and 20 principles. COSO Internal Control (2013) has 5 components and 17 principles.", page: "/standards/coso.html" },
      { q: "Which COSO Internal Control component covers the tone, integrity and accountability of an organisation?", options: ["Control environment", "Control activities", "Monitoring activities", "Information and communication"], answer: 0,
        explain: "The control environment is the foundation, covering integrity, oversight, structure, competence and accountability.", page: "/standards/coso.html" },
      { q: "ISO 31000 is best described as:", options: ["A certifiable requirements standard", "Guidance with principles, a framework and a process", "Australian legislation", "An APRA prudential standard"], answer: 1,
        explain: "ISO 31000 is guidance built around principles, a framework and a process. It isn't certifiable.", page: "/standards/iso-31000.html" }
    ]
  },
  {
    id: "sectors",
    title: "Sectors",
    questions: [
      { q: "Under the SIS Act, super trustees must act in members' best:", options: ["Interests of any kind", "Financial interests", "Social interests", "Tax interests"], answer: 1,
        explain: "Since 1 July 2021, the covenant refers to members' best financial interests, with a reversed evidential burden.", page: "/sectors/superannuation.html" },
      { q: "Who runs the annual super performance test?", options: ["The trustee", "APRA", "ASIC", "The ATO"], answer: 1,
        explain: "APRA runs the performance test. The trustee makes the separate member outcomes assessment.", page: "/sectors/superannuation.html" },
      { q: "What is the Financial Claims Scheme limit for deposits?", options: ["$100,000 per account", "$250,000 per account holder per ADI", "$1 million per bank", "Unlimited"], answer: 1,
        explain: "Up to $250,000 per account holder per ADI.", page: "/sectors/banking.html" },
      { q: "APRA's debt-to-income limit, from February 2026, caps new mortgage lending at a DTI of six or more at:", options: ["5%", "20%", "50%", "No cap; it's a ban"], answer: 1,
        explain: "No more than 20% of new lending, measured separately for owner-occupier and investor lending.", page: "/sectors/banking.html" },
      { q: "Since 1 January 2021, handling and settling an insurance claim has been:", options: ["Exempt from ASIC oversight", "A financial service", "Regulated only by the codes", "Only APRA's concern"], answer: 1,
        explain: "Because it is a financial service, the efficiently, honestly and fairly obligation applies to claims handling.", page: "/sectors/insurance.html" },
      { q: "For consumer insurance since 5 October 2021, customers have a duty to:", options: ["Disclose everything relevant", "Take reasonable care not to make a misrepresentation", "Nothing at all", "Get advice first"], answer: 1,
        explain: "Section 20B replaced the old duty of disclosure for consumer contracts.", page: "/sectors/insurance.html" },
      { q: "A responsible entity must set up a compliance committee when:", options: ["Always", "Fewer than half its directors are external", "It has over 100 members", "ASIC asks"], answer: 1,
        explain: "Section 601JA requires a compliance committee unless at least half the RE's directors are external.", page: "/sectors/managed-investment-schemes.html" },
      { q: "Which regulator is the main regulator of managed investment schemes?", options: ["APRA", "ASIC", "AUSTRAC", "The RBA"], answer: 1,
        explain: "Managed investment schemes are regulated by ASIC under the Corporations Act, not APRA.", page: "/sectors/managed-investment-schemes.html" }
    ]
  },
  {
    id: "case-studies",
    title: "Case studies",
    questions: [
      { q: "The Hayne Royal Commission linked much of the misconduct it found to:", options: ["Incentives and putting profit ahead of basic honesty", "Too little technology", "Interest rate changes", "Foreign competition"], answer: 0,
        explain: "The final report linked much misconduct to incentives and to prioritising profit over basic standards of honesty and fairness.", page: "/case-studies/hayne-royal-commission.html" },
      { q: "APRA's prudential inquiry into CBA found weaknesses mainly in managing:", options: ["Market risk", "Non-financial risks such as operational, compliance and conduct risk", "Credit risk", "Liquidity risk"], answer: 1,
        explain: "The panel found shortcomings in governance, culture and accountability, particularly around non-financial risks.", page: "/case-studies/apra-cba-prudential-inquiry.html" },
      { q: "CBA's AML/CTF failures began when it:", options: ["Hired too few staff", "Rolled out intelligent deposit machines without assessing their money laundering risk", "Moved to the cloud", "Changed auditors"], answer: 1,
        explain: "The machines were introduced without an ML/TF risk assessment, and criminals exploited them.", page: "/case-studies/austrac-cba-westpac.html" },
      { q: "Which lesson from the 2022 Optus and Medibank breaches is about data minimisation?", options: ["Keep all data in case it's useful later", "Destroy or de-identify personal information you no longer need", "Only encrypt new records", "Move data offshore"], answer: 1,
        explain: "Holding old identity documents and records increased the harm. The Australian Privacy Principles require destroying or de-identifying information no longer needed.", page: "/case-studies/optus-medibank-data-breaches.html" },
      { q: "A central financial problem behind HIH Insurance's collapse was:", options: ["Holding too much capital", "Under-reserving for future claims", "Too few policyholders", "High interest rates"], answer: 1,
        explain: "HIH did not set aside enough to pay future claims, so its true position was far worse than reported.", page: "/case-studies/hih-insurance-collapse.html" },
      { q: "In the Shield case, the Federal Court declared a platform trustee contravened the law by failing to:", options: ["Charge enough fees", "Place the Shield options on a watch list for heightened monitoring", "Advertise the fund", "Pay dividends"], answer: 1,
        explain: "The court declared Macquarie should have placed the Shield options on a watch list for further monitoring.", page: "/case-studies/shield-and-first-guardian.html" }
    ]
  }
];

// Page titles used in the "Pages to revisit" list.
window.QUIZ_PAGES = {
  "/compliance/aml-ctf-fundamentals.html": "AML/CTF fundamentals",
  "/compliance/breach-reporting.html": "Breach and incident reporting obligations",
  "/compliance/consumer-protection.html": "Consumer protection",
  "/compliance/designing-a-compliance-program.html": "Designing a compliance program",
  "/compliance/disclosure-obligations.html": "Disclosure obligations",
  "/compliance/licensing-basics.html": "Licensing basics (AFSL, RSE licence and more)",
  "/compliance/privacy-law.html": "Privacy law",
  "/foundations/core-frameworks-compared.html": "Core frameworks compared: ISO 31000, COSO and Three Lines",
  "/foundations/regulatory-landscape.html": "Regulatory landscape map: who regulates what",
  "/foundations/three-lines-model.html": "The Three Lines model (and internal audit's role)",
  "/foundations/what-is-compliance.html": "What is compliance?",
  "/foundations/what-is-governance.html": "What is governance?",
  "/foundations/what-is-risk-management.html": "What is risk management?",
  "/governance/board-structure-and-accountability.html": "Board structure and accountability",
  "/governance/conflicts-of-interest.html": "Conflicts of interest",
  "/governance/culture-and-conduct.html": "Culture and conduct risk",
  "/governance/financial-accountability-regime.html": "Financial Accountability Regime (FAR)",
  "/governance/remuneration-governance.html": "Remuneration governance",
  "/governance/whistleblower-protections.html": "Whistleblower protections",
  "/risk-management/business-continuity.html": "Business continuity",
  "/risk-management/control-design-and-testing.html": "Control design and testing",
  "/risk-management/credit-market-and-liquidity-risk.html": "Credit, market and liquidity risk (the basics)",
  "/risk-management/enterprise-risk-management.html": "Enterprise risk management (ERM)",
  "/risk-management/incident-and-breach-management.html": "Incident and breach management",
  "/risk-management/operational-risk.html": "Operational risk",
  "/risk-management/risk-appetite-and-tolerance.html": "Risk appetite and tolerance",
  "/risk-management/risk-assessment-methodologies.html": "Risk assessment methodologies",
  "/risk-management/third-party-risk.html": "Third-party, vendor and outsourcing risk",
  "/sectors/banking.html": "Banking and ADIs",
  "/sectors/insurance.html": "Insurance",
  "/sectors/managed-investment-schemes.html": "Managed investment schemes",
  "/sectors/superannuation.html": "Superannuation trustee governance",
  "/standards/asic-rg-271.html": "ASIC RG 271 Internal dispute resolution",
  "/standards/asic-rg-274.html": "ASIC RG 274 Product design and distribution obligations",
  "/standards/asic-rg-277.html": "ASIC RG 277 Consumer remediation",
  "/standards/asic-rg-78.html": "ASIC RG 78 Breach reporting by AFS and credit licensees",
  "/standards/coso.html": "COSO ERM and Internal Control frameworks",
  "/standards/cps-220.html": "CPS 220 Risk Management",
  "/standards/cps-230.html": "CPS 230 Operational Risk Management",
  "/standards/cps-234.html": "CPS 234 Information Security",
  "/standards/iso-27001.html": "ISO/IEC 27001 Information security management",
  "/standards/iso-31000.html": "ISO 31000 Risk management",
  "/case-studies/hayne-royal-commission.html": "The Hayne Royal Commission (2019)",
  "/case-studies/apra-cba-prudential-inquiry.html": "APRA Prudential Inquiry into CBA (2018)",
  "/case-studies/austrac-cba-westpac.html": "AUSTRAC v CBA (2018) and AUSTRAC v Westpac (2020)",
  "/case-studies/optus-medibank-data-breaches.html": "The Optus and Medibank data breaches (2022)",
  "/case-studies/hih-insurance-collapse.html": "The HIH Insurance collapse (2001)",
  "/case-studies/shield-and-first-guardian.html": "The Shield and First Guardian collapses"
};
