// Question bank for /learn/quizzes.html (rendered by quiz-runner.js).
// Each question: q (text), options (array), answer (index of the right option),
// explain (why), page (root-relative link to the page that covers it).
// Options are shuffled when shown; set fixed: true to keep their order (e.g. "All of the above").
// Keep questions consistent with the linked page; update both together.
window.QUIZ_BANK = [
  {
    id: "foundations",
    title: "Foundations",
    questions: [
      { q: "What is a risk always tied to?", options: ["A dollar amount", "An objective", "A regulator", "A control"], answer: 1,
        explain: "A risk is uncertainty that could affect what you're trying to achieve, so it only makes sense relative to an objective.", page: "/foundations/what-is-risk-management.html" },
      { q: "Which of these is NOT one of the standard ways to respond to a threat?", options: ["Avoid it", "Share it", "Ignore it without a decision", "Accept it"], answer: 2,
        explain: "Accepting a risk is a deliberate, informed decision. Ignoring it without a decision is not a risk response.", page: "/foundations/what-is-risk-management.html" },
      { q: "Compliance risk is best described as:", options: ["The risk of failing to meet an obligation", "The cost of the compliance team", "The risk of a market fall", "The risk that a regulator changes"], answer: 0,
        explain: "Compliance risk is the risk of failing to meet obligations. It is one type of risk within the wider risk management framework.", page: "/foundations/what-is-compliance.html" },
      { q: "Regulator guidance such as an ASIC Regulatory Guide is generally:", options: ["Legislation", "Not law, but a strong signal of what the regulator expects", "Irrelevant to compliance", "Only for listed companies"], answer: 1,
        explain: "Guidance is usually not law itself (unless made enforceable), but it shows how the regulator reads the law and what it will look for.", page: "/foundations/what-is-compliance.html" },
      { q: "In good governance, who runs the organisation day to day?", options: ["The board", "Management", "Internal audit", "The regulator"], answer: 1,
        explain: "The board sets direction and oversees. Management runs the organisation. Blurring the two is a common source of trouble.", page: "/foundations/what-is-governance.html" },
      { q: "In the Three Lines model, which line gives independent assurance to the board?", options: ["First line", "Second line", "Third line (internal audit)", "External auditor only"], answer: 2,
        explain: "Internal audit is the third line, independent of management, reporting to the board (usually through the audit committee).", page: "/foundations/three-lines-model.html" },
      { q: "A risk and compliance function that sets frameworks, monitors and challenges the business is usually described as:", options: ["First line", "Second line", "Third line", "Fourth line"], answer: 1,
        explain: "Second-line specialist functions set frameworks, advise, monitor and challenge. The business (first line) owns its risks.", page: "/foundations/three-lines-model.html" },
      { q: "Australia's \"twin peaks\" model means:", options: ["APRA for financial soundness, ASIC for conduct", "ASIC and the ACCC share all regulation", "Two separate super regulators", "The RBA and Treasury regulate banks"], answer: 0,
        explain: "APRA handles prudential (financial soundness) regulation and ASIC handles conduct and disclosure.", page: "/foundations/regulatory-landscape.html" },
      { q: "Which regulator is responsible for anti-money laundering and counter-terrorism financing?", options: ["ASIC", "APRA", "AUSTRAC", "OAIC"], answer: 2,
        explain: "AUSTRAC regulates reporting entities under the AML/CTF Act.", page: "/foundations/regulatory-landscape.html" },
      { q: "Which framework is short, general risk management guidance that is NOT certifiable?", options: ["ISO 31000", "ISO/IEC 27001", "CPS 230", "COSO Internal Control"], answer: 0,
        explain: "ISO 31000 is guidance. Unlike ISO/IEC 27001, organisations can't be certified against it.", page: "/foundations/core-frameworks-compared.html" },
      { q: "Do APRA's risk management standards require an organisation to use a specific external framework such as COSO or ISO 31000?", options: ["Yes, COSO ERM", "Yes, ISO 31000", "No, they set outcomes and don't mandate a framework", "Only for banks"], answer: 2,
        explain: "APRA sets requirements and outcomes. Entities can use any framework (or their own) that meets them.", page: "/foundations/core-frameworks-compared.html" }
    ]
  },
  {
    id: "risk",
    title: "Risk management",
    questions: [
      { q: "Which is the correct order, from largest to smallest?", options: ["Appetite, capacity, tolerance", "Capacity, appetite, tolerance and limits", "Tolerance, appetite, capacity", "Limits, capacity, appetite"], answer: 1,
        explain: "Capacity is the most risk you could bear. Appetite is how much you choose to take. Tolerances and limits are the measurable boundaries within that.", page: "/risk-management/risk-appetite-and-tolerance.html" },
      { q: "A risk appetite statement is most useful when:", options: ["It is approved and filed", "It cascades into limits, KRIs and decisions, and breaches lead to action", "It is only qualitative", "It is reviewed every five years"], answer: 1,
        explain: "Appetite only works if it shapes real decisions and limits, and breaches actually trigger a response.", page: "/risk-management/risk-appetite-and-tolerance.html" },
      { q: "Residual risk is the level of risk:", options: ["Before any controls", "After existing controls", "After planned future actions", "That the board will accept"], answer: 1,
        explain: "Inherent risk is before controls. Residual is after current controls. Target risk is after planned actions.", page: "/risk-management/risk-assessment-methodologies.html" },
      { q: "What is a well-documented weakness of heat maps?", options: ["They can't show likelihood", "Ratings can look more precise than the judgement behind them", "They are illegal under ISO 31000", "They only work for financial risks"], answer: 1,
        explain: "Heat maps are good for communication, but the ratings are structured judgement and can hide uncertainty and range effects.", page: "/risk-management/risk-assessment-methodologies.html" },
      { q: "Testing whether a control actually worked, consistently, over a period is testing its:", options: ["Design effectiveness", "Operating effectiveness", "Inherent risk", "Risk appetite"], answer: 1,
        explain: "Design effectiveness asks whether it would work if performed as designed. Operating effectiveness asks whether it did work over time.", page: "/risk-management/control-design-and-testing.html" },
      { q: "A monthly reconciliation that spots unmatched payments after they happen is mainly a:", options: ["Preventive control", "Detective control", "Directive control", "Risk appetite"], answer: 1,
        explain: "It finds problems after they occur, so it is detective. A preventive control stops the problem happening at all.", page: "/risk-management/control-design-and-testing.html" },
      { q: "What is the backbone that lets risks be compared and aggregated across an enterprise?", options: ["A shared risk taxonomy", "A single heat map colour", "The annual report", "A whistleblower policy"], answer: 0,
        explain: "A common taxonomy (list of risk categories) means risks from different areas can be compared and added up.", page: "/risk-management/enterprise-risk-management.html" },
      { q: "Which of these is a driver of operational risk?", options: ["People", "Processes", "Systems and external events", "All of the above"], answer: 3, fixed: true,
        explain: "Operational risk comes from people, processes, systems and external events.", page: "/risk-management/operational-risk.html" },
      { q: "Under CPS 230, how quickly must APRA be told about a disruption to a critical operation that goes outside tolerance?", options: ["24 hours", "72 hours", "10 business days", "30 days"], answer: 0,
        explain: "24 hours for disruptions to critical operations outside tolerance. 72 hours for material operational risk incidents.", page: "/risk-management/operational-risk.html" },
      { q: "Expected credit loss is often estimated as:", options: ["PD × LGD × EAD", "Capital ÷ risk-weighted assets", "Likelihood + consequence", "Assets − liabilities"], answer: 0,
        explain: "Probability of default × loss given default × exposure at default.", page: "/risk-management/credit-market-and-liquidity-risk.html" },
      { q: "Which risk can sink an otherwise solvent institution very quickly?", options: ["Liquidity risk", "Strategic risk", "Reputational risk only", "Model risk only"], answer: 0,
        explain: "If an institution can't meet cash outflows on time, it can fail even with positive net assets.", page: "/risk-management/credit-market-and-liquidity-risk.html" },
      { q: "When does the ASIC reportable situations clock generally start?", options: ["When the investigation is complete", "When the licensee first knows of, or is reckless about, reasonable grounds", "When a customer complains", "At the end of the financial year"], answer: 1,
        explain: "The 30-day clock runs from awareness (or recklessness) of reasonable grounds, not from certainty.", page: "/risk-management/incident-and-breach-management.html" },
      { q: "One event can be:", options: ["Only an incident or a breach, never both", "Both an incident and a breach, triggering several reporting regimes", "Reported to one regulator only", "Ignored if it was a near miss"], answer: 1,
        explain: "Incidents and breaches overlap, and a single event can trigger reports to several regulators.", page: "/risk-management/incident-and-breach-management.html" },
      { q: "A business impact analysis mainly works out:", options: ["Who to blame for an outage", "How quickly harm builds up and what each service depends on", "The cost of insurance", "The board's remuneration"], answer: 1,
        explain: "A BIA shows how harm grows over time and what each service depends on, which drives RTOs and RPOs.", page: "/risk-management/business-continuity.html" },
      { q: "Under CPS 230, how long do entities have to notify APRA after entering into or materially changing an agreement for a service they rely on to undertake a critical operation?", options: ["24 hours", "72 hours", "20 business days", "90 days"], answer: 2,
        explain: "APRA must be notified within 20 business days.", page: "/risk-management/third-party-risk.html" },
      { q: "If a super fund outsources administration, who stays accountable to members and regulators?", options: ["The administrator", "The fund's trustee", "APRA", "Nobody"], answer: 1,
        explain: "Outsourcing a task doesn't outsource accountability.", page: "/risk-management/third-party-risk.html" },
      { q: "An assurance map mainly helps a board see:", options: ["Which assurance providers cover each key risk, revealing gaps and duplication", "The organisation's share price", "Staff leave balances", "Which regulator to call first"], answer: 0,
        explain: "An assurance map shows who checks each key risk and how well, exposing gaps and duplication.", page: "/risk-management/assurance-mapping.html" },
      { q: "Why is change risk treated seriously in super funds?", options: ["Changes are always cheap", "Mergers and administration migrations are among the highest-risk changes and can break existing controls", "APRA bans system changes", "Change risk only affects IT teams"], answer: 1,
        explain: "Many major failures happen during change. Fund mergers and administration migrations are among the riskiest.", page: "/risk-management/change-project-and-reputational-risk.html" },
      { q: "The two main sources of climate risk are:", options: ["Physical risk and transition risk", "Credit risk and market risk", "Fraud risk and cyber risk", "Legal risk and tax risk"], answer: 0,
        explain: "Physical risk comes from weather and climate change; transition risk from moving to a lower-emissions economy. Both drive existing risk types.", page: "/risk-management/climate-risk.html" },
      { q: "Testing 59 items and finding no deviations gives 95% confidence that the true deviation rate is no more than:", options: ["1%", "5%", "10%", "20%"], answer: 1,
        explain: "(0.95)^59 is just under 0.05, so 59 clean items support 95% confidence that the rate is no more than 5%.", page: "/risk-management/control-testing-sampling.html" },
      { q: "Which of these is a baseline set of cyber mitigation strategies from the Australian Signals Directorate?", options: ["The Essential Eight", "The Big Four", "CPS 220", "The Three Lines model"], answer: 0,
        explain: "The Essential Eight is ASD's set of baseline mitigation strategies, assessed against maturity levels.", page: "/risk-management/cyber-risk.html" },
      { q: "The fraud triangle says fraud is driven by:", options: ["Pressure, opportunity and rationalisation", "Cost, time and quality", "Likelihood, consequence and velocity", "People, process and systems"], answer: 0,
        explain: "Controls mainly work by removing opportunity, one side of the triangle.", page: "/risk-management/fraud-risk.html" },
      { q: "What is the difference between closing and validating an issue?", options: ["There is none", "Closure is the owner saying it's done; validation is someone independent confirming the fix works", "Validation happens before the issue is raised", "Closure is done by the regulator"], answer: 1,
        explain: "Separating closure from independent validation, especially for high-rated issues, stops issues being closed before they're really fixed.", page: "/risk-management/issue-and-action-management.html" },
      { q: "Which of these is a core model risk control?", options: ["Independent validation of models", "Letting each developer approve their own model", "Avoiding any model inventory", "Only testing models after an incident"], answer: 0,
        explain: "Core controls include a complete inventory, risk-based tiering, independent validation, effective challenge and monitoring.", page: "/risk-management/model-risk.html" },
      { q: "Expected shortfall is:", options: ["The average year's losses", "The average of the losses in years worse than the VaR level", "The largest loss ever recorded", "The capital required by APS 110"], answer: 1,
        explain: "Expected loss is the average year; VaR is a bad year at a confidence level; expected shortfall averages the years worse than that.", page: "/risk-management/quantitative-operational-risk.html" },
      { q: "Why can't you simply add up or average heat-map scores to get total risk?", options: ["The scores are rankings, not measurements", "Spreadsheets can't add them", "APRA prohibits it", "Scores are always zero"], answer: 0,
        explain: "Heat-map scores are ordinal rankings. Adding them gives numbers that look precise but don't measure total risk.", page: "/risk-management/risk-aggregation-and-correlation.html" },
      { q: "Reverse stress testing starts from:", options: ["A mild scenario", "Failure, then asks what could cause it", "Last year's budget", "The most likely outcome"], answer: 1,
        explain: "Reverse stress testing works backwards from failure to identify the scenarios that could cause it.", page: "/risk-management/scenario-analysis-and-stress-testing.html" },
      { q: "Under CPS 230, tolerance levels for each critical operation cover:", options: ["Maximum period of disruption, maximum data loss, and minimum service levels under alternative arrangements", "Only the maximum cost", "Only staff numbers", "Only the time to notify APRA"], answer: 0,
        explain: "CPS 230 requires board-approved tolerance levels for all three.", page: "/risk-management/setting-cps-230-tolerance-levels.html" },
      { q: "If testing shows an entity can't stay within a tolerance level, good practice is to:", options: ["Loosen the tolerance to match current capability", "Improve recovery or contingency arrangements to close the gap", "Stop testing", "Remove the operation from the critical list"], answer: 1,
        explain: "Tolerances are set from the harm outside in. Closing the capability gap, not moving the goalposts, is the expected response.", page: "/risk-management/setting-cps-230-tolerance-levels.html" }
    ]
  },
  {
    id: "compliance",
    title: "Compliance",
    questions: [
      { q: "What is the \"backbone\" of a compliance program?", options: ["The obligations register", "The annual report", "The website", "The incident log alone"], answer: 0,
        explain: "The obligations register maps every obligation to an owner, the processes it affects and the controls that meet it.", page: "/compliance/designing-a-compliance-program.html" },
      { q: "Which section of the Corporations Act sets AFS licensees' general obligations, such as acting efficiently, honestly and fairly?", options: ["s 180", "s 912A", "s 601FC", "s 1041H"], answer: 1,
        explain: "Section 912A sets the general obligations, including adequate compliance arrangements.", page: "/compliance/licensing-basics.html" },
      { q: "Who issues an Australian credit licence?", options: ["APRA", "ASIC", "AUSTRAC", "The RBA"], answer: 1,
        explain: "ASIC issues both AFS licences and Australian credit licences. APRA authorises banks, insurers and super trustees.", page: "/compliance/licensing-basics.html" },
      { q: "Before a retail client acquires most financial products, they must usually receive a:", options: ["Product Disclosure Statement", "Annual report", "Target market determination", "Compliance plan"], answer: 0,
        explain: "A PDS is generally required before acquisition. An FSG and, for personal advice, an SoA are the other key documents.", page: "/compliance/disclosure-obligations.html" },
      { q: "Does the rule against misleading or deceptive conduct apply to sustainability (\"green\") claims?", options: ["No, only to fees", "Yes, as ASIC's greenwashing cases show", "Only for listed companies", "Only in advertising on TV"], answer: 1,
        explain: "Everything an organisation says must not be misleading, including sustainability claims.", page: "/compliance/disclosure-obligations.html" },
      { q: "What is the general maximum IDR timeframe for complaints (outside super)?", options: ["5 business days", "30 calendar days", "45 calendar days", "90 calendar days"], answer: 1,
        explain: "Generally 30 calendar days. Most super complaints get 45 days.", page: "/compliance/consumer-protection.html" },
      { q: "Since 9 November 2023, unfair contract terms can:", options: ["Attract penalties", "Only be voided by AFCA", "Only apply to business customers", "Be approved by ASIC"], answer: 0,
        explain: "Unfair contract terms have attracted civil penalties since 9 November 2023.", page: "/compliance/consumer-protection.html" },
      { q: "The ASIC reportable situations deadline for significant breaches is:", options: ["72 hours", "10 business days", "30 calendar days", "90 days"], answer: 2,
        explain: "30 calendar days from first knowing of, or being reckless about, reasonable grounds.", page: "/compliance/breach-reporting.html" },
      { q: "Under the Notifiable Data Breaches scheme, which breaches must be notified to the OAIC and affected people?", options: ["All breaches", "Those likely to result in serious harm", "Only breaches over 1,000 records", "Only cyber attacks"], answer: 1,
        explain: "An eligible data breach is one likely to result in serious harm to the people affected.", page: "/compliance/privacy-law.html" },
      { q: "How many Australian Privacy Principles are there?", options: ["7", "10", "13", "20"], answer: 2,
        explain: "There are 13 APPs, covering the whole life cycle of personal information.", page: "/compliance/privacy-law.html" },
      { q: "Knowing your customer under AML/CTF law is called:", options: ["Customer due diligence", "Target market determination", "Fit and proper", "Material service provider review"], answer: 0,
        explain: "Customer due diligence (KYC) is a core AML/CTF obligation.", page: "/compliance/aml-ctf-fundamentals.html" },
      { q: "From 1 July 2026, the AML/CTF reforms (\"tranche 2\") brought in:", options: ["Only banks", "Lawyers, accountants, real estate professionals and others", "Only super funds", "No new sectors"], answer: 1,
        explain: "Tranche 2 extends the regime to lawyers, accountants, real estate professionals and others.", page: "/compliance/aml-ctf-fundamentals.html" },
      { q: "Under the failure to prevent foreign bribery offence (from 8 September 2024), a company's only defence is:", options: ["That the bribe was small", "Having adequate procedures in place", "That the associate was overseas", "That the board didn't know"], answer: 1,
        explain: "The offence applies to bribery by associates. Adequate procedures are the only defence.", page: "/compliance/anti-bribery-and-corruption.html" },
      { q: "When assessing whether a breach of a core obligation is significant, what should you check first?", options: ["The deemed-significance tests in s 912D(4)", "The size of the compliance team", "Whether the media knows", "The weighing factors in s 912D(5)"], answer: 0,
        explain: "If any deemed test applies, the breach is significant whatever its size. Only then weigh the other factors.", page: "/compliance/breach-significance-analysis.html" },
      { q: "Under mandatory climate reporting, super funds and registered schemes with $5 billion or more in assets fall into:", options: ["Group 1", "Group 2", "Group 3", "They are exempt"], answer: 1,
        explain: "They are in Group 2, reporting from financial years starting on or after 1 July 2026.", page: "/compliance/climate-related-financial-disclosures.html" },
      { q: "What makes advice 'personal advice'?", options: ["It's given face to face", "The adviser considered, or should have considered, the client's objectives, financial situation or needs", "It's about shares", "It's in writing"], answer: 1,
        explain: "Personal advice carries the best interests duty and other heavier obligations.", page: "/compliance/financial-advice-regulation.html" },
      { q: "Under the Modern Slavery Act 2018, which entities must publish a modern slavery statement?", options: ["Every business", "Entities with annual consolidated revenue of more than $100 million", "Only listed companies", "Only charities"], answer: 1,
        explain: "Reporting entities with more than $100 million revenue must publish an annual statement against seven mandatory criteria.", page: "/compliance/modern-slavery.html" },
      { q: "For a company, breaching Australian sanctions is:", options: ["Only a civil matter", "A strict liability offence, with a defence of reasonable precautions and due diligence", "Legal if unintentional", "Only an issue for banks"], answer: 1,
        explain: "No intent is needed for a company. It must show it took reasonable precautions and exercised due diligence.", page: "/compliance/sanctions-compliance.html" }
    ]
  },
  {
    id: "governance",
    title: "Governance",
    questions: [
      { q: "Can a board delegate its accountability to management?", options: ["Yes, fully", "No. It can delegate authority, but it stays accountable", "Only to the CEO", "Only with APRA approval"], answer: 1,
        explain: "Boards delegate authority, not accountability. Clear delegations and good information are how they keep control.", page: "/governance/board-structure-and-accountability.html" },
      { q: "Directors' duties of care and diligence, good faith and not misusing position are in which part of the Corporations Act?", options: ["ss 180–184", "s 912A", "Part 9.4AAA", "Chapter 5C"], answer: 0,
        explain: "Sections 180–184 set out directors' core duties.", page: "/governance/board-structure-and-accountability.html" },
      { q: "When is the FAR's minimum deferral met for an accountable person's variable pay?", options: ["10% for one year", "At least 40% for at least four years", "100% for ten years", "There is no deferral"], answer: 1,
        explain: "FAR requires at least 40% of variable remuneration to be deferred for at least four years (subject to exceptions).", page: "/governance/financial-accountability-regime.html" },
      { q: "When did FAR start for super trustees and insurers?", options: ["15 March 2024", "15 March 2025", "1 July 2025", "It doesn't apply to them"], answer: 1,
        explain: "Banks from 15 March 2024. Insurers and super trustees from 15 March 2025.", page: "/governance/financial-accountability-regime.html" },
      { q: "Which is often NOT enough on its own to manage a serious conflict of interest?", options: ["Avoiding it", "Controlling it", "Disclosing it", "Declining the transaction"], answer: 2,
        explain: "Disclosure alone often doesn't fix the underlying conflict. Avoidance or controls may be needed.", page: "/governance/conflicts-of-interest.html" },
      { q: "Where a super trustee faces a conflict, whose interests must it prioritise?", options: ["The trustee's shareholders", "Members", "The fund's promoters", "The administrator"], answer: 1,
        explain: "The SIS Act requires trustees to give priority to members' interests.", page: "/governance/conflicts-of-interest.html" },
      { q: "Under CPS 511, the CEO of a significant financial institution must have at least 60% of variable pay deferred over:", options: ["Two years", "Four years", "Six years", "Ten years"], answer: 2,
        explain: "CPS 511 sets minimum deferral of 60% over six years for the CEO of an SFI.", page: "/governance/remuneration-governance.html" },
      { q: "Which kind of report is generally NOT protected under the Corporations Act whistleblower regime?", options: ["Suspected fraud", "A purely personal work-related grievance", "Misconduct about the company's financial services", "An anonymous disclosure of an improper state of affairs"], answer: 1,
        explain: "Personal work-related grievances are generally excluded unless they also involve wider matters.", page: "/governance/whistleblower-protections.html" },
      { q: "Can a whistleblower disclosure be made anonymously and still be protected?", options: ["Yes", "No", "Only to ASIC", "Only if the person later reveals their identity"], answer: 0,
        explain: "Disclosures can be anonymous and still qualify for protection.", page: "/governance/whistleblower-protections.html" },
      { q: "Conduct risk is the risk that:", options: ["Market prices move", "Behaviour causes poor customer outcomes or harms markets", "A server fails", "A borrower defaults"], answer: 1,
        explain: "Conduct risk is about behaviour, of the organisation or its people, that causes poor outcomes.", page: "/governance/culture-and-conduct.html" },
      { q: "Which inquiry identified culture as a root cause of misconduct at a major bank in 2018?", options: ["APRA's CBA Prudential Inquiry", "The Wallis Inquiry", "The Murray Inquiry", "The HIH Royal Commission"], answer: 0,
        explain: "APRA's 2018 Prudential Inquiry into CBA focused heavily on culture, governance and accountability.", page: "/governance/culture-and-conduct.html" },
      { q: "How is AI regulated in Australia as at 2026?", options: ["A standalone AI Act", "Mainly through existing, technology-neutral laws and sector regulators", "It isn't regulated at all", "Only through ISO/IEC 42001"], answer: 1,
        explain: "The December 2025 National AI Plan confirmed reliance on existing laws and regulators, supported by voluntary guidance.", page: "/governance/ai-governance.html" },
      { q: "The core question every board risk report should answer is:", options: ["How many risks are in the register?", "Are we operating within risk appetite, and if not, what are we doing about it?", "How long is the pack?", "Which staff attended training?"], answer: 1,
        explain: "Good reports lead with the conclusion and decisions needed, focused on the position against appetite.", page: "/governance/board-risk-reporting.html" },
      { q: "Internal audit reports functionally to:", options: ["The CFO", "The board audit committee", "The external auditor", "The regulator"], answer: 1,
        explain: "The audit committee approves internal audit's plan, protects its independence and oversees its findings.", page: "/governance/internal-audit.html" },
      { q: "A good risk culture assessment:", options: ["Relies on one staff survey", "Triangulates what people say, what they do and what the organisation has built", "Counts policies", "Is done once every ten years"], answer: 1,
        explain: "No single measure captures culture, so good assessments combine several sources of evidence.", page: "/governance/risk-culture-assessment.html" }
    ]
  },
  {
    id: "standards",
    title: "Standards and regulatory guides",
    questions: [
      { q: "When did CPS 230 come into force?", options: ["1 January 2024", "1 July 2025", "15 March 2025", "1 July 2026"], answer: 1,
        explain: "CPS 230 has applied since 1 July 2025.", page: "/standards/cps-230.html" },
      { q: "Above what total assets is an RSE licensee a \"significant financial institution\" (SFI) under APRA's standards?", options: ["$3 billion", "$10 billion", "$20 billion", "$30 billion"], answer: 3,
        explain: "$30 billion for RSE licensees. Since 1 July 2026 banks are also SFIs above $30 billion; general and life insurers are $10 billion, and private health insurers $3 billion.", page: "/standards/cps-230.html" },
      { q: "CPS 220 requires APRA-regulated entities to have a:", options: ["Risk appetite statement and risk management strategy", "Compliance plan audit", "Target market determination", "Financial Services Guide"], answer: 0,
        explain: "CPS 220 requires a risk management framework including a risk appetite statement and a risk management strategy.", page: "/standards/cps-220.html" },
      { q: "Under CPS 234, a material information security incident must be notified to APRA:", options: ["As soon as possible and no later than 72 hours", "Within 10 business days", "Within 30 days", "Annually"], answer: 0,
        explain: "72 hours for material incidents. Material control weaknesses that can't be fixed in time are 10 business days.", page: "/standards/cps-234.html" },
      { q: "Under ASIC relief, how long can an investigation into a possible significant breach run before it becomes reportable?", options: ["30 days", "60 days", "90 days", "There is no limit"], answer: 1,
        explain: "The Act says 30 days, but ASIC relief extended this to 60 days from 27 June 2025.", page: "/standards/asic-rg-78.html" },
      { q: "Most super complaints must be resolved or answered at IDR within:", options: ["21 days", "30 days", "45 days", "90 days"], answer: 2,
        explain: "45 calendar days for most super complaints (30 for most others).", page: "/standards/asic-rg-271.html" },
      { q: "Under the DDO, significant dealings inconsistent with the TMD must be notified to ASIC within:", options: ["72 hours", "10 business days", "30 days", "No notification needed"], answer: 1,
        explain: "Issuers must notify ASIC within 10 business days of becoming aware.", page: "/standards/asic-rg-274.html" },
      { q: "Which product is excluded from the design and distribution obligations?", options: ["Choice super products", "MySuper products", "Credit cards", "Managed funds"], answer: 1,
        explain: "MySuper products are excluded. Choice products are covered.", page: "/standards/asic-rg-274.html" },
      { q: "RG 277 says that where data is missing in a remediation, a licensee should use:", options: ["Assumptions that favour the licensee", "Beneficial assumptions that favour consumers", "No assumptions and exclude those consumers", "The regulator's data"], answer: 1,
        explain: "Beneficial assumptions stop people falling out of scope or being underpaid.", page: "/standards/asic-rg-277.html" },
      { q: "ISO/IEC 27001:2022 Annex A has how many reference controls?", options: ["14", "93", "114", "133"], answer: 1,
        explain: "93 controls in four themes: organisational, people, physical and technological. The 2013 edition had 114.", page: "/standards/iso-27001.html" },
      { q: "The ISO/IEC 27001 document that lists each Annex A control and whether it applies is the:", options: ["Risk register", "Statement of Applicability", "Compliance plan", "Business impact analysis"], answer: 1,
        explain: "The Statement of Applicability links risk treatment to controls and records inclusions and exclusions.", page: "/standards/iso-27001.html" },
      { q: "How many components and principles does COSO ERM (2017) have?", options: ["5 components, 17 principles", "5 components, 20 principles", "8 components, 20 principles", "3 components, 11 principles"], answer: 1,
        explain: "COSO ERM has 5 components and 20 principles. COSO Internal Control (2013) has 5 components and 17 principles.", page: "/standards/coso.html" },
      { q: "Which COSO Internal Control component covers the tone, integrity and accountability of an organisation?", options: ["Control environment", "Control activities", "Monitoring activities", "Information and communication"], answer: 0,
        explain: "The control environment is the foundation, covering integrity, oversight, structure, competence and accountability.", page: "/standards/coso.html" },
      { q: "ISO 31000 is best described as:", options: ["A certifiable requirements standard", "Guidance with principles, a framework and a process", "Australian legislation", "An APRA prudential standard"], answer: 1,
        explain: "ISO 31000 is guidance built around principles, a framework and a process. It isn't certifiable.", page: "/standards/iso-31000.html" },
      { q: "Under APS 110, the minimum Common Equity Tier 1 ratio before buffers is:", options: ["2%", "4.5%", "8%", "10.5%"], answer: 1,
        explain: "CET1 must be at least 4.5% of risk-weighted assets before buffers.", page: "/standards/aps-110-and-aps-210.html" },
      { q: "ASIC regulatory guides are generally:", options: ["Legislation passed by Parliament", "Not law, but a guide to how ASIC interprets the law, with some paragraphs made enforceable", "Optional for everyone", "Written by industry bodies"], answer: 1,
        explain: "Some RG paragraphs, such as parts of RG 271, are made enforceable by legislative instrument.", page: "/standards/asic-regulatory-guides.html" },
      { q: "RG 105 is mainly about:", options: ["Organisational competence, often shown through responsible managers", "Fee disclosure", "Whistleblowers", "Climate reporting"], answer: 0,
        explain: "Licensees must have people with the knowledge and skills to provide their financial services.", page: "/standards/asic-rg-104-and-rg-105.html" },
      { q: "Under RG 181, disclosure of a conflict of interest is:", options: ["Always enough on its own", "Often not enough on its own; it usually supplements controls", "Prohibited", "Only needed for directors"], answer: 1,
        explain: "Conflicts are managed by controlling, avoiding or disclosing them, matched to the risk.", page: "/standards/asic-rg-181.html" },
      { q: "RG 259 expects fund operators to stress test each fund's liquidity:", options: ["Never", "At least annually, and more often where needed", "Every ten years", "Only when ASIC asks"], answer: 1,
        explain: "ASIC singles out liquidity risk for pooled funds.", page: "/standards/asic-rg-259.html" },
      { q: "RG 270 gives guidance on:", options: ["Whistleblower policies", "Capital adequacy", "Climate statements", "Model validation"], answer: 0,
        explain: "Covered companies must have a whistleblower policy covering matters set out in the Act.", page: "/standards/asic-rg-270.html" },
      { q: "RG 97 requires super PDSs to show a worked example of annual costs on a balance of:", options: ["$10,000", "$50,000", "$100,000", "$1 million"], answer: 1,
        explain: "The fees and costs summary includes a $50,000 worked example and a cost of product figure for each option.", page: "/standards/asic-rg-97.html" },
      { q: "CPS 190 requires APRA-regulated entities to have:", options: ["A marketing plan", "A recovery and exit plan", "A tax plan", "An IPO plan"], answer: 1,
        explain: "CPS 190 covers recovery and exit planning; CPS 900 covers supporting APRA's resolution planning.", page: "/standards/cps-190-and-cps-900.html" },
      { q: "CPS 520 requires 'responsible persons' to be assessed as fit and proper:", options: ["Once, at appointment", "Before appointment and at least annually", "Only if a complaint is made", "Every five years"], answer: 1,
        explain: "Entities must assess competence, character, diligence, honesty and integrity before appointment and at least annually.", page: "/standards/cps-510-and-cps-520.html" },
      { q: "Under CPS 511, significant financial institutions must defer at least what share of the CEO's variable pay?", options: ["20%", "40%", "60%", "100%"], answer: 2,
        explain: "At least 60% of the CEO's variable pay must be deferred, over six years.", page: "/standards/cps-511.html" },
      { q: "Essential Eight maturity levels range from:", options: ["One to Five", "Zero to Three", "A to F", "Low to Extreme"], answer: 1,
        explain: "Aim for the same level across all eight strategies before moving higher.", page: "/standards/essential-eight.html" },
      { q: "The IIA's Global Internal Audit Standards took effect on:", options: ["1 July 2020", "9 January 2025", "1 January 2027", "They are still a draft"], answer: 1,
        explain: "They have five domains and fifteen principles, plus topical requirements such as cybersecurity.", page: "/standards/global-internal-audit-standards.html" },
      { q: "Which is a core step in ISO 22301 business continuity management?", options: ["Business impact analysis", "Credit scoring", "Tax planning", "Remuneration review"], answer: 0,
        explain: "Its core steps include business impact analysis, risk assessment, strategies, plans and exercising.", page: "/standards/iso-22301.html" },
      { q: "Can ISO 37001 certification by itself be a legal defence to the failure to prevent foreign bribery offence?", options: ["Yes, always", "No, but a well-run system can help show adequate procedures", "Only for listed companies", "Only outside Australia"], answer: 1,
        explain: "Certification isn't a defence on its own, but it can support an adequate procedures argument.", page: "/standards/iso-37001.html" },
      { q: "ISO 37301 built on which pioneering Australian standard?", options: ["AS 3806", "AS/NZS 4360", "APS 110", "CPS 230"], answer: 0,
        explain: "AS 3806 was an early Australian compliance standard.", page: "/standards/iso-37301.html" },
      { q: "Beyond common management system clauses, ISO/IEC 42001 requires:", options: ["AI risk assessment and AI system impact assessment", "A minimum capital ratio", "Annual financial statements", "A whistleblower hotline only"], answer: 0,
        explain: "Impact assessment looks at effects on individuals, groups and society.", page: "/standards/iso-42001.html" },
      { q: "SPS 515 requires super trustees to:", options: ["Set strategic objectives supporting member outcomes and assess outcomes regularly", "Guarantee returns", "Hold a set amount of cash", "Report to AUSTRAC"], answer: 0,
        explain: "It links strategy, spending and member outcomes, including the annual outcomes assessment.", page: "/standards/sps-515.html" },
      { q: "Which is a core requirement of SPS 530?", options: ["A comprehensive liquidity stress-testing program", "A minimum number of members", "Quarterly TV advertising", "A ban on unlisted assets"], answer: 0,
        explain: "Valuation governance and liquidity management, including stress testing, are core requirements.", page: "/standards/sps-530.html" }
    ]
  },
  {
    id: "sectors",
    title: "Sectors",
    questions: [
      { q: "Under the SIS Act, super trustees must act in members' best:", options: ["Interests of any kind", "Financial interests", "Social interests", "Tax interests"], answer: 1,
        explain: "Since 1 July 2021, the covenant refers to members' best financial interests, with a reversed evidential burden.", page: "/sectors/superannuation.html" },
      { q: "Who runs the annual super performance test?", options: ["The trustee", "APRA", "ASIC", "The ATO"], answer: 1,
        explain: "APRA runs the performance test. The trustee makes the separate member outcomes assessment.", page: "/sectors/superannuation.html" },
      { q: "What is the Financial Claims Scheme limit for deposits?", options: ["$100,000 per account", "$250,000 per account holder per ADI", "$1 million per bank", "Unlimited"], answer: 1,
        explain: "Up to $250,000 per account holder per ADI.", page: "/sectors/banking.html" },
      { q: "APRA's debt-to-income limit, from February 2026, caps new mortgage lending at a DTI of six or more at:", options: ["5%", "20%", "50%", "No cap; it's a ban"], answer: 1,
        explain: "No more than 20% of new lending, measured separately for owner-occupier and investor lending.", page: "/sectors/banking.html" },
      { q: "Since 1 January 2021, handling and settling an insurance claim has been:", options: ["Exempt from ASIC oversight", "A financial service", "Regulated only by the codes", "Only APRA's concern"], answer: 1,
        explain: "Because it is a financial service, the efficiently, honestly and fairly obligation applies to claims handling.", page: "/sectors/insurance.html" },
      { q: "For consumer insurance since 5 October 2021, customers have a duty to:", options: ["Disclose everything relevant", "Take reasonable care not to make a misrepresentation", "Nothing at all", "Get advice first"], answer: 1,
        explain: "Section 20B replaced the old duty of disclosure for consumer contracts.", page: "/sectors/insurance.html" },
      { q: "A responsible entity must set up a compliance committee when:", options: ["Always", "Fewer than half its directors are external", "It has over 100 members", "ASIC asks"], answer: 1,
        explain: "Section 601JA requires a compliance committee unless at least half the RE's directors are external.", page: "/sectors/managed-investment-schemes.html" },
      { q: "Which regulator is the main regulator of managed investment schemes?", options: ["APRA", "ASIC", "AUSTRAC", "The RBA"], answer: 1,
        explain: "Managed investment schemes are regulated by ASIC under the Corporations Act, not APRA.", page: "/sectors/managed-investment-schemes.html" },
      { q: "Buy now pay later became regulated credit from:", options: ["1 January 2020", "10 June 2025", "1 July 2027", "It isn't regulated"], answer: 1,
        explain: "BNPL is now regulated credit with modified responsible lending obligations.", page: "/sectors/credit-and-non-bank-lenders.html" },
      { q: "Advice licensees must:", options: ["Supervise and monitor their advisers, and report certain misconduct", "Only check advisers when they join", "Leave supervision to ASIC", "Only supervise advisers who give general advice"], answer: 0,
        explain: "Licensees are responsible for their advisers' conduct and have specific reporting and remediation duties.", page: "/sectors/financial-advice-licensees.html" },
      { q: "Continuous disclosure requires listed entities to:", options: ["Report once a year", "Tell the market immediately about information that would materially affect the share price, subject to limited exceptions", "Publish all board minutes", "Disclose staff salaries"], answer: 1,
        explain: "It is a cornerstone of listed-company obligations.", page: "/sectors/listed-companies.html" },
      { q: "How many ACNC Governance Standards must registered charities meet?", options: ["Three", "Five", "Seven", "Ten"], answer: 1,
        explain: "There are five Governance Standards, plus External Conduct Standards for those operating overseas.", page: "/sectors/not-for-profits-and-charities.html" },
      { q: "From 1 October 2026, the RBA is removing:", options: ["All credit cards", "Card surcharges on designated card networks", "Cash", "Direct debits"], answer: 1,
        explain: "Surcharges on designated networks are being removed and interchange fees reduced.", page: "/sectors/payments-and-fintech.html" },
      { q: "Section 16 of the PGPA Act requires Commonwealth entities to:", options: ["Maintain appropriate systems of risk oversight and management and internal control", "Hold a banking licence", "Publish a modern slavery statement", "Use ISO 31000 certification"], answer: 0,
        explain: "The accountable authority must establish and maintain these systems.", page: "/sectors/public-sector.html" }
    ]
  },
  {
    id: "case-studies",
    title: "Case studies",
    questions: [
      { q: "The Hayne Royal Commission linked much of the misconduct it found to:", options: ["Incentives and putting profit ahead of basic honesty", "Too little technology", "Interest rate changes", "Foreign competition"], answer: 0,
        explain: "The final report linked much misconduct to incentives and to prioritising profit over basic standards of honesty and fairness.", page: "/case-studies/hayne-royal-commission.html" },
      { q: "APRA's prudential inquiry into CBA found weaknesses mainly in managing:", options: ["Market risk", "Non-financial risks such as operational, compliance and conduct risk", "Credit risk", "Liquidity risk"], answer: 1,
        explain: "The panel found shortcomings in governance, culture and accountability, particularly around non-financial risks.", page: "/case-studies/apra-cba-prudential-inquiry.html" },
      { q: "CBA's AML/CTF failures began when it:", options: ["Hired too few staff", "Rolled out intelligent deposit machines without assessing their money laundering risk", "Moved to the cloud", "Changed auditors"], answer: 1,
        explain: "The machines were introduced without an ML/TF risk assessment, and criminals exploited them.", page: "/case-studies/austrac-cba-westpac.html" },
      { q: "Which lesson from the 2022 Optus and Medibank breaches is about data minimisation?", options: ["Keep all data in case it's useful later", "Destroy or de-identify personal information you no longer need", "Only encrypt new records", "Move data offshore"], answer: 1,
        explain: "Holding old identity documents and records increased the harm. The Australian Privacy Principles require destroying or de-identifying information no longer needed.", page: "/case-studies/optus-medibank-data-breaches.html" },
      { q: "A central financial problem behind HIH Insurance's collapse was:", options: ["Holding too much capital", "Under-reserving for future claims", "Too few policyholders", "High interest rates"], answer: 1,
        explain: "HIH did not set aside enough to pay future claims, so its true position was far worse than reported.", page: "/case-studies/hih-insurance-collapse.html" },
      { q: "In the Shield case, the Federal Court declared a platform trustee contravened the law by failing to:", options: ["Charge enough fees", "Place the Shield options on a watch list for heightened monitoring", "Advertise the fund", "Pay dividends"], answer: 1,
        explain: "The court declared Macquarie should have placed the Shield options on a watch list for further monitoring.", page: "/case-studies/shield-and-first-guardian.html" }
    ]
  },
  {
    id: "news",
    title: "News and current affairs (2026)",
    questions: [
      { q: "Which of these started on 1 July 2026?", options: ["Payday Super, AML/CTF tranche 2 and APRA's targeted CPS 230 amendments", "CPS 230 itself", "The Hayne Royal Commission", "The Essential Eight"], answer: 0,
        explain: "1 July 2026 was a big start date. CPS 230 itself started a year earlier, on 1 July 2025.", page: "/news/2026-09-regulatory-roundup.html" },
      { q: "Under Payday Super, contributions must generally reach the fund within:", options: ["Seven business days of payday", "One quarter", "30 days of year end", "24 hours"], answer: 0,
        explain: "Employers now pay super with wages rather than quarterly.", page: "/news/2026-09-regulatory-roundup.html" },
      { q: "APRA's draft CPS 510 proposes a default tenure limit for non-executive directors of:", options: ["6 years", "9 years", "12 years", "No limit"], answer: 2,
        explain: "The draft would also extend the minimum of five directors to super trustees. It is a draft and may change.", page: "/news/draft-cps-510-governance-overhaul.html" },
      { q: "Draft CPS 510 would replace how many existing standards?", options: ["One", "Three", "Five", "Ten"], answer: 2,
        explain: "CPS 510, SPS 510, CPS 520, SPS 520 and SPS 521 would become one cross-industry standard.", page: "/news/draft-cps-510-governance-overhaul.html" },
      { q: "ASIC's Report 833 (June 2026) reviewed:", options: ["Six super platform trustees", "All banks", "Charities", "Payday lenders"], answer: 0,
        explain: "It found persistent gaps in monitoring advice fees, unusual patterns and high-risk switching.", page: "/news/super-platform-trustees-asic-rep-833.html" },
      { q: "What does the 13-month delay case in Report 833 illustrate?", options: ["Reporting clocks run from awareness, so slow escalation is risky", "Trustees should wait for certainty", "Advice fees are always fine", "ASIC doesn't review trustees"], answer: 0,
        explain: "Clear escalation rules and a recorded awareness date protect members and the organisation.", page: "/news/super-platform-trustees-asic-rep-833.html" },
      { q: "From 10 December 2026, privacy policies must explain:", options: ["When personal information is used in substantially automated decisions that significantly affect individuals", "Staff salaries", "The entity's share price", "Every data field held"], answer: 0,
        explain: "The automated decision-making transparency obligations start by 10 December 2026.", page: "/governance/ai-governance.html" },
      { q: "APRA's phase-out of Additional Tier 1 capital begins on:", options: ["1 July 2025", "1 January 2027", "1 July 2030", "It has been cancelled"], answer: 1,
        explain: "APRA decided to phase out AT1 capital from 1 January 2027.", page: "/standards/aps-110-and-aps-210.html" }
    ]
  },
  {
    id: "advanced",
    title: "Advanced topics",
    questions: [
      { q: "An ad's headline says 'Australia's top fund'; the qualification is in small print at the bottom. Which case is most relevant?", options: ["ACCC v TPG Internet (dominant message)", "Daniels v Anderson", "Project Blue Sky", "Shafron v ASIC"], answer: 0,
        explain: "TPG confirmed fine print may not correct a misleading dominant message.", page: "/compliance/misleading-or-deceptive-conduct.html" },
      { q: "Which ASIC Act provisions carried the civil penalties in ASIC's greenwashing cases?", options: ["s 12DA only", "ss 12DB and 12DF", "s 12BB", "s 1041H"], answer: 1,
        explain: "Sections 12DB and 12DF are civil penalty provisions; s 12DA and s 1041H are not.", page: "/compliance/misleading-or-deceptive-conduct.html" },
      { q: "In ASIC v Bekier (2026), what did the Federal Court find?", options: ["All directors breached s 180", "The former CEO and Chief Legal and Risk Officer breached s 180; claims against non-executive directors failed", "No one breached their duties", "Only the auditor was liable"], answer: 1,
        explain: "The executives failed to act on and escalate serious risks.", page: "/governance/directors-duties-case-law.html" },
      { q: "Which of these is NOT a condition of the business judgment rule in s 180(2)?", options: ["Good faith and proper purpose", "No material personal interest", "The decision turned out well", "Rational belief it was in the company's best interests"], answer: 2,
        explain: "The rule protects the decision process, not the outcome.", page: "/governance/directors-duties-case-law.html" },
      { q: "A company's benefit from a contravention was $5 million and its annual turnover is $2 billion. What is the maximum civil penalty per contravention under s 1317G?", options: ["$18.2 million", "$15 million", "$200 million", "$910 million"], answer: 2,
        explain: "Greatest of 50,000 penalty units ($18.2m), 3 × benefit ($15m) and 10% of turnover ($200m, below the 2.5 million penalty unit cap).", page: "/compliance/enforcement-and-penalties.html" },
      { q: "An ADI's business indicator is $10 billion. What is its APS 115 operational risk capital?", options: ["$1.2 billion", "$1.455 billion", "$1.5 billion", "$1.8 billion"], answer: 1,
        explain: "12% × $1.5bn + 15% × $8.5bn = $0.18bn + $1.275bn = $1.455bn.", page: "/standards/aps-115.html" },
      { q: "In a fault tree, a cause (30%) must combine with a failed detective control (50%) through an AND gate. What is the path probability, assuming independence?", options: ["80%", "15%", "35%", "60%"], answer: 1,
        explain: "Probabilities multiply through AND gates: 0.3 × 0.5 = 0.15.", page: "/risk-management/root-cause-analysis.html" },
      { q: "A KRI drifts upward for eight months but never crosses its 3σ limit. Which technique would flag it?", options: ["A run rule", "A higher threshold", "Removing the KRI", "Averaging across KRIs"], answer: 0,
        explain: "Run rules detect sustained shifts that single-point thresholds miss.", page: "/risk-management/kri-design-and-thresholds.html" },
      { q: "Ratings in a risk workshop barely change year to year and follow the most senior person's view. Which technique helps most?", options: ["Longer workshops", "Independent private ratings before discussion", "Removing the register", "Using only last year's ratings"], answer: 1,
        explain: "Private first ratings counter anchoring and authority effects.", page: "/risk-management/human-factors-and-bias.html" },
      { q: "Under CPS 230, which resources must be documented for critical operations?", options: ["Only technology", "People, technology, information, facilities and service providers, and their interdependencies", "Only service providers", "Only premises"], answer: 1,
        explain: "CPS 230 requires documenting processes and resources, and the risks, obligations, key data and controls.", page: "/risk-management/mapping-critical-operations.html" },
      { q: "What most defines a stressed exit from a service provider?", options: ["A long, cooperative migration", "The provider may not cooperate and time is very short", "A cheaper contract", "A change in pricing"], answer: 1,
        explain: "Stressed exits rely on contingency arrangements rather than planned migration.", page: "/risk-management/service-provider-exit-and-concentration.html" },
      { q: "Listed markets fall 30% and unlisted valuations barely move. What happens to the unlisted share of a Balanced option?", options: ["It falls", "It rises, possibly above the strategic range", "It is unchanged", "It becomes zero"], answer: 1,
        explain: "The denominator effect, made worse when outflows are paid from liquid assets.", page: "/risk-management/super-liquidity-stress-testing.html" },
      { q: "Under s 15AB of the Acts Interpretation Act, explanatory memoranda can be used to:", options: ["Override clear words", "Confirm ordinary meaning or resolve ambiguity or absurdity", "Replace regulations", "Nothing"], answer: 1,
        explain: "Extrinsic materials help confirm or determine meaning in defined circumstances.", page: "/compliance/interpreting-legislation.html" },
      { q: "Which case first held a licensee breached s 912A through inadequate cyber security risk management?", options: ["ASIC v RI Advice (2022)", "ASIC v Healey (2011)", "Campomar v Nike (2000)", "Pattinson (2022)"], answer: 0,
        explain: "RI Advice was ASIC's first cyber test case; FIIG (2026) brought the first civil penalty.", page: "/case-studies/asic-cyber-cases-ri-advice-and-fiig.html" },
      { q: "Under FAR Act s 22, reasonable steps include all of these EXCEPT:", options: ["Appropriate governance, control and risk management", "Safeguards against inappropriate delegation", "Procedures to identify and remediate problems", "Guaranteeing no breach ever occurs"], answer: 3,
        explain: "Reasonable steps is an objective standard, not a guarantee.", page: "/governance/reasonable-steps-and-consequence-management.html" },
      { q: "Which technique best suits testing whether every member's premium was deducted correctly?", options: ["Mystery shopping", "Full-population data analytics", "A walkthrough", "Call listening"], answer: 1,
        explain: "High-volume, rules-based obligations suit full-population testing.", page: "/compliance/compliance-monitoring-and-testing.html" },
      { q: "Where a licensee can't determine a consumer's actual foregone returns, RG 277 gives this rate as an example that may be fair and reasonable if justified:", options: ["CPI", "RBA cash rate + 6% a year", "0%", "The bank bill rate"], answer: 1,
        explain: "RG 277 allows actual returns, prescribed rates or reasonably justified beneficial assumptions; it gives the RBA cash rate + 6% as an example rate where justified.", page: "/compliance/remediation-calculations.html" },
      { q: "A unit price was overstated. Who is disadvantaged?", options: ["Members who withdrew", "Members who invested, and members who stayed while others withdrew", "Only the trustee", "No one"], answer: 1,
        explain: "Incoming members got too few units; leavers were overpaid at the expense of those who stayed.", page: "/sectors/unit-pricing.html" },
      { q: "Under the SFT rule, the successor fund must confer on members:", options: ["Identical rights", "Equivalent rights in respect of their benefits", "Better fees", "A choice of fund"], answer: 1,
        explain: "Equivalent, not equal, assessed as a bundle of rights.", page: "/sectors/fund-mergers-and-successor-fund-transfers.html" }
    ]
  },
  {
    id: "research",
    title: "University-level research",
    questions: [
      { q: "Ayres and Braithwaite's enforcement pyramid suggests regulators should usually start with:", options: ["The harshest sanction", "Persuasion and education, escalating only if needed", "Licence cancellation", "Doing nothing"], answer: 1,
        explain: "Responsive regulation starts at the base of the pyramid and escalates when cooperation fails.", page: "/compliance/theories-of-regulation.html" },
      { q: "Agency theory assumes managers:", options: ["Always act in owners' interests", "May pursue their own interests, so owners need monitoring and incentives", "Have no interests", "Are elected by customers"], answer: 1,
        explain: "Stewardship theory offers a contrasting view of managers as pro-organisational.", page: "/governance/corporate-governance-theories.html" },
      { q: "Normal accident theory argues that serious accidents are more likely in systems that are:", options: ["Simple and loosely coupled", "Complex and tightly coupled", "Small", "Well documented"], answer: 1,
        explain: "Perrow argued interactive complexity and tight coupling make some accidents 'normal'.", page: "/risk-management/theories-of-risk.html" },
      { q: "The empirical evidence on whether ERM increases firm value is best described as:", options: ["Conclusive that it always does", "Mixed, with measurement problems and possible reverse causality", "Conclusive that it never does", "Non-existent"], answer: 1,
        explain: "Some studies find a positive association, but measuring ERM and proving cause are hard.", page: "/risk-management/does-erm-work.html" },
      { q: "A common academic critique of the three lines model is that it:", options: ["Has been rigorously proven effective", "Can blur accountability and has limited evidence of effectiveness", "Applies only to banks", "Removes internal audit"], answer: 1,
        explain: "Researchers note its untested effectiveness and coordination problems in practice.", page: "/governance/three-lines-research-and-critique.html" },
      { q: "Madrian and Shea's study of automatic enrolment showed that:", options: ["Defaults have little effect", "Defaults strongly shape participation and contribution choices", "Everyone actively chooses", "Disclosure removes inertia"], answer: 1,
        explain: "Participation jumped under automatic enrolment, and many stayed at the default rate.", page: "/sectors/behavioural-economics-of-super.html" },
      { q: "Egan, Matvos and Seru found that financial advisers with past misconduct:", options: ["Always leave the industry", "Are more likely to reoffend and often find new jobs", "Are never hired again", "Are rare and random"], answer: 1,
        explain: "Misconduct is concentrated and persistent, and some firms specialise in hiring such advisers.", page: "/compliance/misconduct-in-financial-services-research.html" },
      { q: "Fahlenbrach and Stulz found that, in the 2008 crisis, banks whose CEOs' incentives were better aligned with shareholders:", options: ["Performed much better", "Performed no better, and on some evidence worse", "Were all rescued", "Had no losses"], answer: 1,
        explain: "Aligning pay with shareholders did not protect banks, which challenges simple fixes to incentive design.", page: "/governance/remuneration-incentives-and-risk-taking.html" },
      { q: "In Dyck, Morse and Zingales's study of large US corporate frauds, which group revealed the largest share?", options: ["The securities regulator", "Employees", "Auditors", "Short sellers"], answer: 1,
        explain: "Employees revealed about 19% of frauds, more than auditors, the media or the securities regulator.", page: "/governance/whistleblowing-research.html" },
      { q: "Free and Murphy's research on co-offending found that group fraud depends on:", options: ["Random chance", "The type of bond between offenders", "Only financial pressure", "Weak IT systems"], answer: 1,
        explain: "Bonds such as loyalty and friendship shape collusion, which defeats segregation of duties.", page: "/compliance/fraud-theory.html" },
      { q: "Roussy's study of internal auditors described their independence as:", options: ["Absolute", "'Grey', as auditors often help and protect top management", "Irrelevant", "Set by external auditors"], answer: 1,
        explain: "Auditors moved between watchdog, helper and protector roles.", page: "/governance/internal-audit-effectiveness.html" },
      { q: "A database has an expected annual breach loss of $2 million. Under the Gordon-Loeb result, the optimal annual security investment is at most about:", options: ["$2 million", "$740,000", "$200,000", "$5 million"], answer: 1,
        explain: "About 37% (1/e) of the expected loss, under the model's assumptions.", page: "/risk-management/economics-of-cyber-risk.html" },
      { q: "Bernstein, Gustafson and Lewis found US homes exposed to projected sea level rise:", options: ["Sell at a premium", "Sell at about a 7% discount", "Are not affected", "Cannot be sold"], answer: 1,
        explain: "Evidence that some physical climate risk is reflected in prices.", page: "/risk-management/climate-risk-research.html" },
      { q: "Takáts's 'crying wolf' model shows that very high fines for failing to report can:", options: ["Improve every report", "Lead banks to over-report, diluting the value of reports", "Stop all laundering", "Reduce reporting"], answer: 1,
        explain: "Defensive reporting floods the system with weakly suspicious reports.", page: "/compliance/aml-ctf-effectiveness.html" }
    ]
  },
  {
    id: "grc",
    title: "GRC systems",
    questions: [
      { q: "In a typical three-level risk taxonomy, where do an APRA-regulated entity's material risks usually sit?", options: ["Level 3, in business unit registers", "Level 1, as the top-level risk categories", "Only in the internal audit plan", "Outside the taxonomy"], answer: 1,
        explain: "Level 1 categories usually match the material risks, and carry the risk appetite and metrics.", page: "/grc/risk-taxonomy-and-hierarchy.html" },
      { q: "Which is the best-written Level 3 risk?", options: ["Cyber", "Staff turnover", "Unauthorised access to member data through a compromised administrator account", "Reputational damage"], answer: 2,
        explain: "A good Level 3 risk describes an event; the others are a category, a cause and an impact.", page: "/grc/risk-taxonomy-and-hierarchy.html" },
      { q: "What links risks and obligations to controls in a well-designed GRC system?", options: ["Control objectives", "The org chart", "Board minutes", "The audit plan"], answer: 0,
        explain: "Risks and obligations map to control objectives, which are achieved by controls.", page: "/grc/control-framework-architecture.html" },
      { q: "What does ‘assess once, use many times’ mean in GRC?", options: ["Each team tests its own copy of a control", "One control, recorded and tested once, provides evidence for every risk and obligation it supports", "Risks are assessed only once ever", "Only the board assesses risk"], answer: 1,
        explain: "Reuse is the main benefit of integration.", page: "/grc/what-is-a-grc-system.html" },
      { q: "What should normally come first when establishing a GRC system?", options: ["Buying a GRC platform", "Designing taxonomies, rating scales, the data model and the operating model", "Migrating all existing spreadsheets", "Writing procedures"], answer: 1,
        explain: "Design comes before technology, so the tool fits the organisation rather than the other way around.", page: "/grc/establishing-a-grc-system.html" },
      { q: "In a hybrid GRC model for a complex group, who usually owns each regulated entity's risk appetite?", options: ["The group's external auditor", "The regulated entity's own board, within group standards", "The GRC software vendor", "Nobody"], answer: 1,
        explain: "Groups set standards and taxonomies, but each regulated entity's board keeps its own responsibilities.", page: "/grc/grc-for-complex-groups.html" }
    ]
  }
];

// Page titles used in the "Pages to revisit" list.
window.QUIZ_PAGES = {
  "/compliance/aml-ctf-fundamentals.html": "AML/CTF fundamentals",
  "/compliance/breach-reporting.html": "Breach and incident reporting obligations",
  "/compliance/consumer-protection.html": "Consumer protection",
  "/compliance/designing-a-compliance-program.html": "Designing a compliance program",
  "/compliance/disclosure-obligations.html": "Disclosure obligations",
  "/compliance/licensing-basics.html": "Licensing basics (AFSL, RSE licence and more)",
  "/compliance/privacy-law.html": "Privacy law",
  "/foundations/core-frameworks-compared.html": "Core frameworks compared: ISO 31000, COSO and Three Lines",
  "/foundations/regulatory-landscape.html": "Regulatory landscape map: who regulates what",
  "/foundations/three-lines-model.html": "The Three Lines model (and internal audit's role)",
  "/foundations/what-is-compliance.html": "What is compliance?",
  "/foundations/what-is-governance.html": "What is governance?",
  "/foundations/what-is-risk-management.html": "What is risk management?",
  "/governance/board-structure-and-accountability.html": "Board structure and accountability",
  "/governance/conflicts-of-interest.html": "Conflicts of interest",
  "/governance/culture-and-conduct.html": "Culture and conduct risk",
  "/governance/financial-accountability-regime.html": "Financial Accountability Regime (FAR)",
  "/governance/remuneration-governance.html": "Remuneration governance",
  "/governance/whistleblower-protections.html": "Whistleblower protections",
  "/risk-management/business-continuity.html": "Business continuity",
  "/risk-management/control-design-and-testing.html": "Control design and testing",
  "/risk-management/credit-market-and-liquidity-risk.html": "Credit, market and liquidity risk (the basics)",
  "/risk-management/enterprise-risk-management.html": "Enterprise risk management (ERM)",
  "/risk-management/incident-and-breach-management.html": "Incident and breach management",
  "/risk-management/operational-risk.html": "Operational risk",
  "/risk-management/risk-appetite-and-tolerance.html": "Risk appetite and tolerance",
  "/risk-management/risk-assessment-methodologies.html": "Risk assessment methodologies",
  "/risk-management/third-party-risk.html": "Third-party, vendor and outsourcing risk",
  "/sectors/banking.html": "Banking and ADIs",
  "/sectors/insurance.html": "Insurance",
  "/sectors/managed-investment-schemes.html": "Managed investment schemes",
  "/sectors/superannuation.html": "Superannuation trustee governance",
  "/standards/asic-rg-271.html": "ASIC RG 271 Internal dispute resolution",
  "/standards/asic-rg-274.html": "ASIC RG 274 Product design and distribution obligations",
  "/standards/asic-rg-277.html": "ASIC RG 277 Consumer remediation",
  "/standards/asic-rg-78.html": "ASIC RG 78 Breach reporting by AFS and credit licensees",
  "/standards/coso.html": "COSO ERM and Internal Control frameworks",
  "/standards/cps-220.html": "CPS 220 Risk Management",
  "/standards/cps-230.html": "CPS 230 Operational Risk Management",
  "/standards/cps-234.html": "CPS 234 Information Security",
  "/standards/iso-27001.html": "ISO/IEC 27001 Information security management",
  "/standards/iso-31000.html": "ISO 31000 Risk management",
  "/case-studies/hayne-royal-commission.html": "The Hayne Royal Commission (2019)",
  "/case-studies/apra-cba-prudential-inquiry.html": "APRA Prudential Inquiry into CBA (2018)",
  "/case-studies/austrac-cba-westpac.html": "AUSTRAC v CBA (2018) and AUSTRAC v Westpac (2020)",
  "/case-studies/optus-medibank-data-breaches.html": "The Optus and Medibank data breaches (2022)",
  "/case-studies/hih-insurance-collapse.html": "The HIH Insurance collapse (2001)",
  "/case-studies/shield-and-first-guardian.html": "The Shield and First Guardian collapses",
  "/risk-management/assurance-mapping.html": "Assurance mapping and combined assurance",
  "/risk-management/change-project-and-reputational-risk.html": "Change, project and reputational risk",
  "/risk-management/climate-risk.html": "Climate risk management",
  "/risk-management/control-testing-sampling.html": "Control testing: sampling and assurance confidence",
  "/risk-management/cyber-risk.html": "Cyber risk management",
  "/risk-management/fraud-risk.html": "Fraud risk management",
  "/risk-management/issue-and-action-management.html": "Issue and action management",
  "/risk-management/model-risk.html": "Model risk management",
  "/risk-management/quantitative-operational-risk.html": "Quantitative operational risk: loss distributions, VaR and expected shortfall",
  "/risk-management/risk-aggregation-and-correlation.html": "Risk aggregation and correlation",
  "/risk-management/scenario-analysis-and-stress-testing.html": "Scenario analysis and stress testing",
  "/risk-management/setting-cps-230-tolerance-levels.html": "Setting CPS 230 tolerance levels",
  "/compliance/anti-bribery-and-corruption.html": "Anti-bribery and corruption",
  "/compliance/breach-significance-analysis.html": "Breach significance analysis in practice",
  "/compliance/climate-related-financial-disclosures.html": "Climate-related financial disclosures and sustainability reporting",
  "/compliance/financial-advice-regulation.html": "Financial advice regulation",
  "/compliance/modern-slavery.html": "Modern slavery reporting",
  "/compliance/sanctions-compliance.html": "Sanctions compliance",
  "/governance/ai-governance.html": "AI governance",
  "/governance/board-risk-reporting.html": "Board risk reporting design",
  "/governance/internal-audit.html": "Internal audit",
  "/governance/risk-culture-assessment.html": "Assessing and changing risk culture",
  "/standards/aps-110-and-aps-210.html": "APS 110 capital and APS 210 liquidity basics",
  "/standards/asic-regulatory-guides.html": "Key ASIC regulatory guides",
  "/standards/asic-rg-104-and-rg-105.html": "ASIC RG 104 and RG 105 licensee obligations explained",
  "/standards/asic-rg-181.html": "ASIC RG 181 Managing conflicts of interest explained",
  "/standards/asic-rg-259.html": "ASIC RG 259 Risk management for fund operators explained",
  "/standards/asic-rg-270.html": "ASIC RG 270 Whistleblower policies explained",
  "/standards/asic-rg-97.html": "ASIC RG 97 Fees and costs disclosure explained",
  "/standards/cps-190-and-cps-900.html": "CPS 190 and CPS 900 recovery and resolution explained",
  "/standards/cps-510-and-cps-520.html": "CPS 510 Governance and CPS 520 Fit and Proper explained",
  "/standards/cps-511.html": "CPS 511 Remuneration explained",
  "/standards/essential-eight.html": "ASD Essential Eight explained",
  "/standards/global-internal-audit-standards.html": "IIA Global Internal Audit Standards explained",
  "/standards/iso-22301.html": "ISO 22301 Business continuity management explained",
  "/standards/iso-37001.html": "ISO 37001 Anti-bribery management systems explained",
  "/standards/iso-37301.html": "ISO 37301 Compliance management systems explained",
  "/standards/iso-42001.html": "ISO/IEC 42001 AI management systems explained",
  "/standards/sps-515.html": "SPS 515 Strategic Planning and Member Outcomes explained",
  "/standards/sps-530.html": "SPS 530 Investment Governance explained",
  "/sectors/credit-and-non-bank-lenders.html": "Credit licensees and non-bank lenders",
  "/sectors/financial-advice-licensees.html": "Financial advice licensees",
  "/sectors/listed-companies.html": "Listed companies",
  "/sectors/not-for-profits-and-charities.html": "Not-for-profits and charities",
  "/sectors/payments-and-fintech.html": "Payments and fintech",
  "/sectors/public-sector.html": "Public sector risk and governance",
  "/news/2026-09-regulatory-roundup.html": "Regulatory roundup: winter 2026",
  "/news/draft-cps-510-governance-overhaul.html": "APRA's governance reset: draft CPS 510",
  "/news/super-platform-trustees-asic-rep-833.html": "Platform trustees in the spotlight: ASIC Report 833",
  "/compliance/misleading-or-deceptive-conduct.html": "Misleading or deceptive conduct: the legal tests",
  "/governance/directors-duties-case-law.html": "Directors' and officers' duties: key Australian cases",
  "/compliance/enforcement-and-penalties.html": "Enforcement and penalties: how regulators respond",
  "/standards/aps-115.html": "APS 115 Operational risk capital",
  "/risk-management/root-cause-analysis.html": "Root cause analysis: techniques and pitfalls",
  "/risk-management/kri-design-and-thresholds.html": "KRI design and statistical thresholds",
  "/risk-management/human-factors-and-bias.html": "Human factors and cognitive bias in risk decisions",
  "/risk-management/mapping-critical-operations.html": "Mapping critical operations end to end",
  "/risk-management/service-provider-exit-and-concentration.html": "Service provider concentration, fourth parties and exit planning",
  "/risk-management/super-liquidity-stress-testing.html": "Liquidity stress testing for super funds",
  "/compliance/interpreting-legislation.html": "Interpreting legislation for compliance professionals",
  "/case-studies/asic-cyber-cases-ri-advice-and-fiig.html": "ASIC v RI Advice and ASIC v FIIG: cyber security as a licensee obligation",
  "/governance/reasonable-steps-and-consequence-management.html": "Reasonable steps and consequence management",
  "/compliance/compliance-monitoring-and-testing.html": "Designing a compliance monitoring and testing program",
  "/compliance/remediation-calculations.html": "Remediation calculations in practice",
  "/sectors/unit-pricing.html": "Unit pricing and unit pricing errors",
  "/sectors/fund-mergers-and-successor-fund-transfers.html": "Fund mergers and successor fund transfers",
  "/compliance/theories-of-regulation.html": "Theories of regulation: responsive, risk-based and principles-based",
  "/governance/corporate-governance-theories.html": "Corporate governance theories: agency, stewardship and stakeholder",
  "/risk-management/theories-of-risk.html": "Theories of risk: perception, amplification, normal accidents and high reliability",
  "/risk-management/does-erm-work.html": "Does enterprise risk management work? The evidence",
  "/governance/three-lines-research-and-critique.html": "The Three Lines model: research and critique",
  "/sectors/behavioural-economics-of-super.html": "Behavioural economics of super: defaults, inertia and choice",
  "/compliance/misconduct-in-financial-services-research.html": "Misconduct in financial services: what the research shows",
  "/governance/remuneration-incentives-and-risk-taking.html": "Remuneration, incentives and risk-taking: the evidence",
  "/governance/whistleblowing-research.html": "Whistleblowing: research on who speaks up and why",
  "/compliance/fraud-theory.html": "Fraud theory beyond the triangle",
  "/governance/internal-audit-effectiveness.html": "Internal audit effectiveness: the research",
  "/risk-management/economics-of-cyber-risk.html": "The economics of cyber risk",
  "/risk-management/climate-risk-research.html": "Climate risk: the research",
  "/compliance/aml-ctf-effectiveness.html": "Does AML/CTF work? The research",
  "/grc/risk-taxonomy-and-hierarchy.html": "Risk taxonomy and the risk hierarchy",
  "/grc/control-framework-architecture.html": "Control framework architecture",
  "/grc/what-is-a-grc-system.html": "What is a GRC system?",
  "/grc/establishing-a-grc-system.html": "Establishing a GRC system: a step-by-step roadmap",
  "/grc/grc-for-complex-groups.html": "GRC for complex groups: design choices and the research"
};
