"""Obligation checklists: single source for /tools/obligation-checklists.html and the
downloadable assets/templates/obligation-checklists.xlsx. Items are plain-English summaries
in our own words, consistent with the linked site pages; they are not the legal text.
Build with:  python3 _scripts/templates/build_checklists.py
"""

CHECKLISTS = [
    {
        "id": "cps-230",
        "title": "CPS 230 Operational risk management",
        "applies": "APRA-regulated banks, insurers and super trustees (in force since 1 July 2025).",
        "page": "/standards/cps-230.html",
        "items": [
            ("The board is ultimately accountable for operational risk and oversees it; senior management is responsible for implementation.", "CPS 230: roles"),
            ("Operational risk management is part of the CPS 220 / SPS 220 risk management framework.", "CPS 230, CPS 220"),
            ("Operational risks are identified and assessed, including legal, regulatory, compliance, conduct, technology, data and change risks.", "CPS 230: operational risk"),
            ("Key controls are designed and embedded, and regularly monitored, reviewed and tested for design and operating effectiveness.", "CPS 230: controls"),
            ("Control weaknesses stay in the risk profile until fixed, and root causes are addressed.", "CPS 230: controls"),
            ("Operational risk incidents and near misses are identified, escalated, recorded and addressed.", "CPS 230: incidents"),
            ("A process exists to notify APRA of material operational risk incidents within 72 hours of becoming aware.", "CPS 230: notification"),
            ("Critical operations are identified, including those APRA deems critical unless justified otherwise.", "CPS 230: critical operations"),
            ("The board has approved tolerance levels for each critical operation (e.g. maximum disruption period, data loss and minimum service levels).", "CPS 230: tolerance levels"),
            ("A credible business continuity plan is maintained for staying within tolerance through severe disruption.", "CPS 230: BCP"),
            ("There is a systematic testing program, including an annual exercise with severe but plausible scenarios (including a service provider failure).", "CPS 230: BCP testing"),
            ("A process exists to notify APRA within 24 hours of a disruption to a critical operation outside tolerance.", "CPS 230: notification"),
            ("There is a comprehensive service provider management policy.", "CPS 230: service providers"),
            ("Material service providers are identified, and a register is maintained and submitted to APRA annually.", "CPS 230: service providers"),
            ("Due diligence is done before entering or materially changing material arrangements.", "CPS 230: service providers"),
            ("Formal, legally binding agreements cover the matters CPS 230 specifies.", "CPS 230: service providers"),
            ("Service provider performance and risk are monitored on an ongoing basis.", "CPS 230: service providers"),
            ("APRA is notified within 20 business days of entering into or materially changing an agreement for a service relied on to undertake a critical operation, and before material offshoring.", "CPS 230: notification"),
        ],
    },
    {
        "id": "breach-reporting",
        "title": "Breach reporting readiness (ASIC reportable situations)",
        "applies": "AFS licensees and Australian credit licensees, including super trustees.",
        "page": "/standards/asic-rg-78.html",
        "items": [
            ("There is a documented process to identify, record and escalate possible breaches promptly.", "RG 78"),
            ("Staff are trained to recognise possible breaches and know how to report them internally.", "RG 78"),
            ("The date the licensee became aware (or had reasonable grounds) is recorded for every matter.", "RG 78; s 912D"),
            ("Each matter is assessed against the core obligations, the deemed significance tests and the significance factors.", "RG 78; s 912D"),
            ("Significance reasoning is documented, including for matters assessed as not reportable.", "RG 78"),
            ("Reportable situations are lodged through the ASIC Regulatory Portal within 30 calendar days.", "s 912DAA; RG 78"),
            ("Investigations are tracked, and reported if they run longer than the period allowed (currently 60 days under ASIC relief).", "RG 78; ASIC relief"),
            ("Obligations to report about other licensees' individual advisers or mortgage brokers are understood where relevant.", "RG 78"),
            ("ASIC is updated as facts change after the initial report.", "RG 78"),
            ("For super trustees, APRA notification requirements (SIS Act s 29JA) are coordinated with ASIC reporting.", "SIS Act s 29JA"),
            ("Personal advice licensees notify, investigate and remediate affected clients where required.", "ss 912EA–912EB"),
            ("A breach register is maintained, and breach trends are reported to management and the board.", "Good practice"),
            ("Root causes and remediation are tracked to closure.", "Good practice; RG 277"),
        ],
    },
    {
        "id": "idr",
        "title": "Complaints handling (IDR, RG 271)",
        "applies": "AFS licensees and credit licensees serving retail clients, super trustees and other firms required to have IDR.",
        "page": "/standards/asic-rg-271.html",
        "items": [
            ("Staff can recognise a complaint however it is made, including verbally and on social media where appropriate.", "RG 271"),
            ("The complaints policy is published and easy to find, and the process is free for customers.", "RG 271"),
            ("Complaints are acknowledged within 24 hours or one business day, or as soon as practicable.", "RG 271"),
            ("Complaints are resolved, or an IDR response is given, within the maximum timeframes: generally 30 calendar days, or 45 days for most super complaints.", "RG 271 (enforceable)"),
            ("Super death benefit objections are handled within their separate timeframe.", "RG 271"),
            ("IDR responses are in writing, explain the outcome and reasons, and tell the customer about their right to go to AFCA.", "RG 271 (enforceable)"),
            ("Every complaint is recorded, including those resolved on first contact.", "RG 271"),
            ("People who need extra help (e.g. vulnerable customers) get appropriate support.", "RG 271"),
            ("Complaints data is analysed to find systemic issues and root causes, which are escalated and fixed.", "RG 271"),
            ("The board and senior management receive regular complaints reporting.", "RG 271"),
            ("IDR data is reported to ASIC as required.", "ASIC IDR data reporting"),
        ],
    },
    {
        "id": "ddo",
        "title": "Design and distribution obligations (RG 274)",
        "applies": "Issuers and distributors of most retail financial products (MySuper products and some others are excluded).",
        "page": "/standards/asic-rg-274.html",
        "items": [
            ("A target market determination is made and published before distributing each in-scope product.", "Part 7.8A; RG 274"),
            ("Each TMD describes the target market, distribution conditions, review triggers, review periods and distributor reporting.", "RG 274"),
            ("The target market is specific enough to guide distribution, including who the product is not suitable for where helpful.", "RG 274"),
            ("Reasonable steps are taken so that distribution, including marketing, is consistent with the TMD.", "s 994E; RG 274"),
            ("Distributors report complaints and dealings outside the target market to the issuer as the TMD requires.", "RG 274"),
            ("TMDs are reviewed when a review trigger occurs and within the maximum review period.", "RG 274"),
            ("Significant dealings inconsistent with the TMD are notified to ASIC within 10 business days.", "s 994G; RG 274"),
            ("Distribution information and decisions are recorded.", "RG 274"),
            ("Product outcomes (e.g. complaints, claims, cancellations, performance) are monitored and reported to governance forums.", "RG 274"),
        ],
    },
    {
        "id": "whistleblower",
        "title": "Whistleblower program (Part 9.4AAA, RG 270)",
        "applies": "Public companies, large proprietary companies and super trustee companies must have a policy. The protections apply more widely.",
        "page": "/governance/whistleblower-protections.html",
        "items": [
            ("A whistleblower policy is in place and available to officers and employees.", "s 1317AI; RG 270"),
            ("The policy explains which disclosures are protected and who can receive them.", "RG 270"),
            ("The policy explains the protections, including identity confidentiality and protection from detriment.", "RG 270"),
            ("The policy explains how disclosures are investigated, and how people mentioned in them are treated fairly.", "RG 270"),
            ("There is a channel for anonymous disclosures.", "Part 9.4AAA; RG 270"),
            ("Eligible recipients know their role and are trained to handle disclosures.", "RG 270"),
            ("Records are secure, and processes protect whistleblowers' identities.", "Part 9.4AAA"),
            ("The risk of detriment is assessed and monitored for each disclosure.", "RG 270"),
            ("Whistleblowers receive appropriate updates on progress and outcomes.", "RG 270"),
            ("The board receives reporting on the program without identifying whistleblowers.", "RG 270"),
            ("The policy and program are reviewed periodically.", "RG 270"),
        ],
    },
    {
        "id": "privacy",
        "title": "Privacy and data breach readiness",
        "applies": "Organisations covered by the Privacy Act 1988 (Cth), generally including businesses with turnover over $3 million.",
        "page": "/compliance/privacy-law.html",
        "items": [
            ("An up-to-date APP privacy policy is published.", "APP 1"),
            ("The organisation knows what personal information it holds, where, why and for how long.", "APP 1, APP 11"),
            ("Collection notices tell people what is collected and why.", "APP 5"),
            ("Personal information is used and disclosed only for permitted purposes.", "APP 6"),
            ("Disclosures to overseas recipients are identified and managed.", "APP 8"),
            ("Reasonable security safeguards are in place, and information is destroyed or de-identified when no longer needed.", "APP 11"),
            ("Access and correction requests are handled within required timeframes.", "APPs 12 and 13"),
            ("A data breach response plan sets out roles, escalation and decision-making.", "OAIC guidance"),
            ("Suspected eligible data breaches are assessed quickly, generally within 30 days.", "Part IIIC"),
            ("Eligible data breaches are notified to the OAIC and affected individuals as soon as practicable.", "Part IIIC"),
            ("Service provider contracts cover data handling, security and breach notification.", "APP 11; good practice"),
            ("Staff receive privacy and data security training.", "Good practice"),
        ],
    },
]
